### ISSUE TITLE
Purchase Request APP: Add version to Purchase Request archived

### ISSUE THREAD

**Issue by AndreaDiCeglie** [EOS-Solutions/IDEAS#1]
Current archive feature let the user to move the selected purchase request document to archived PRQ table.
Suggested IDEA is to :

- Add Version No_ field to "Archived PRQ"
- Add an action "Copy in archived PRQ"
- Rename existing "Archive" action in  "Move in archived PRQ"

**Comment by MatCive** [comment]
In order to align the PRQ functionlities to the BC standard ones, I suggest to rename the "Archive" action in "Archive Document"; that action creates then the new version of the PRQ.
The suggested "Move in archived PRQ" could be done using the "Delete" action.

**Comment by AndreaDiCeglie** [comment]
Implemented, will be released in next version
