### ISSUE TITLE
 DocSolutions for Sharepoint - EOS069 Fields Mapping - Configure a field as required (WI 10698)

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#100]
Add a "required field" setup regardless of whether it is a field of bc or entered by the user

![image](https://user-images.githubusercontent.com/88732191/159127908-4c802240-07a6-4028-88a6-169f736f2db0.png)

**Comment by alessandrovecchio** [comment]
Grazie, segnalazione chiara. Valuteremo se implemetare un flag o altro controllo

**Comment by massimocisco** [comment]
Ciao, giusto per avere un'idea, che tempi di rilascio prevedi ? Grazie Massimo

**Comment by alessandrovecchio** [comment]
Ciao, la modifica è inserita nel backlog ma con priorità bassa. Al momento non sappiamo indicare una possibile data di rilascio

**Comment by massimocisco** [comment]
Va bene. Grazie. Massimo

**Comment by Carlobrus** [comment]
Si potrebbe aggiungere anche una seconda opzione:
**Campo non modificabile**
quindi se il realtivo campo (impostato come non modificabile) sarà visualizzato nella pagina di upload, non consentire all’utente di modificarne il valore!
nota: questo sarebbe utile per avere riscontro prima dell’upload, e costringere l’utente a modificare il dato in BC e non nella finestra di upload solamente.

**Comment by Carlobrus** [comment]
Non è stato nemmeno preso in considerazione il mio commento precedente del 14 Dicembre.
