### ISSUE TITLE
Add Extended Text to PRQ - Purchase Request (WI 10701)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#101]
Alcuni clienti ci richiedono la gestione dei Testi Estesi nelle PRQ per diversi motivi
- Poter applicare i testi anche in fase di richiesta di acquisto
- All'inserimento delle righe PRQ nell'ordine di acquisto, i testi estesi non vengono aggiunti in automatico

La nostra proposta è di aggiungere un nuovo campo alla gestione dei Testi Estesi per le PRQ e, quando attivo il flag "Testi predefiniti" nell'anagrafica articolo, esploderli in automatico nelle righe PRQ.
Lasciare, invece, invariato l'attuale comportamento in fase di importazione righe nell'ordine in quanto, ovviamente, devono avere priorità i Testi Estesi della PRQ.
Aggiungere anche una action "Inserisci testi estesi" nelle righe PRQ.

Matteo e Gianni

**Comment by Stefano-Primo-EOS** [comment]
È stata rilasciata una nuova app "Advanced Document Reporting for Purchase Request". 
È in corso di pubblicazione su AppSource ma ci vorrà almeno una settimana, per onPrem è già disponibile
