### ISSUE TITLE
ECS - Extended Combine Shipment - Funzioni avanzate Clienti Trade\GDO (WI 10730, 10733, 10736)

### ISSUE THREAD

**Issue by agtmartino** [EOS-Solutions/IDEAS#102]
Si richiedono le seguenti funzionalità che sono sempre state implementate nelle versioni precedenti (sia pure come custom) sui clienti con elevati volumi di fatturazione

1) Possibilità di non interrompere il processo di fatturazione in caso di errore
L'attuale funzione procedura ECS nel caso di errore su una fattura interrompe l'intero processo lasciando "a meta" la fattura che si sta creando. 
Qualora si rilanci il processo il sistema duplica le fatture esistenti e poichè a volte è difficile  farlo ripartire da dove è rimasto è necessario eliminare le fatture provvisorie (una ad una manualmente).
A volte sono presenti differenti tipologie di fatture inserite anche manualmente per cui è difficile raccapezzarsi

2) Possibilità di gestire uno stato di datasecurity nel caso la fattura si creata senza errori e uno nel caso di errore sulla fattura

3) Possibilità di spaccare la fatturazione per le classi documento Ordine

4) Possibilità di assegnare una classe documento specifica alle fatture generate con la procedura

**Comment by alessandrovecchio** [comment]
Grazie, la segnalazione è stata valutata positivamente. Per l'impatto sull'app e la sua portata sarà sviluppata con priorità bassa.

**Comment by Luca-Maritano-EOS** [comment]
Rilasciate su:
BC23
BC24
BC25
