### ISSUE TITLE
Withholding Tax Certificazioni Uniche for Italy - Certificazione Unica percipienti esteri (WI 8605)

### ISSUE THREAD

**Issue by CristianCorega-Lutech** [EOS-Solutions/IDEAS#104]
Ciao,
un cliente nuovo in BC, ci ha segnalato la necessità di certificare le ritenute versate per un percipiente estero. Con la versione attuale non è purtroppo possibile. Per quest'anno hanno provveduto diversamente tramite commercialista, ma il prossimo vorrebbero procedere in autonomia.
Sarebbe possibile implementare tale gestione?
Grazie, Cristian

**Comment by alessandrovecchio** [comment]
Ciao, dopo aver valutato internamente lo sviluppo in questione, ti volevo informare che purtroppo non si è deciso di procedere con l'integrazione nell'app standard.

Ciao
