### ISSUE TITLE
Manutenzione Impianti PLM

### ISSUE THREAD

**Issue by apezzano** [EOS-Solutions/IDEAS#105]
Per il modulo Manutenzione Impianti (PLM) si richiede la possibilità di generare una grafica (immagine, per esempio) della struttura ad albero di macchina e corrispettivi componenti, come allegato.

![struttura BC PLM](https://user-images.githubusercontent.com/99964320/162155251-e73ee5b5-682b-4041-bc97-fe5f66c9d65c.PNG)
![Struttura](https://user-images.githubusercontent.com/99964320/162155123-aa242358-b3ae-490c-bd82-a1118943c13f.png)

Ciao e grazie in anticipo.

**Comment by alessandrovecchio** [comment]
Grazie per la proposta, ma visti i limiti tecnici abbiamo deciso di non processarla.
