### ISSUE TITLE
DocFinance - Pagamento fatture acquisto non registrate

### ISSUE THREAD

**Issue by ClaudiaMarzocchi** [EOS-Solutions/IDEAS#106]
Buongiorno,
un cliente per le fatture di San Marino non può registrarle in definitiva prima di avere la copia delle fatture vidimate dall’ufficio tributario, ma nel frattempo queste fatture devono essere pagate tramite DocFinance. Non è possibile usare le fatture proforma perchè specifiche della gestione ritenuta acconto. Sarebbe bello poter avere un flag in testata fattura acquisto per l'invio del debito verso DocFinance prima della registrazione effettiva del documento.

Grazie

**Comment by AndreaDiCeglie** [comment]
No other request were collected on this. Closed as "low interest"
