### ISSUE TITLE
Download Massivo Fatture Acquisto Registrate

### ISSUE THREAD

**Issue by VCagliero** [EOS-Solutions/IDEAS#107]
Si richiede la possibilità di abilitare il download massivo xml anche nelle fatture di acquisto registrate così come presente nelle fatture vendita registrate tramite la funzione "Azioni" - "Documento elettronico"

Grazie

**Comment by alessandrovecchio** [comment]
Richiesta approvata con issue https://github.com/EOS-Solutions/IDEAS/issues/108
