### ISSUE TITLE
Documento Elettronico: Azione "Scarica XML" in Lista Fatture Acquisto Registrate e Note Cr. Acquisto Registrate. (WI 9279)

### ISSUE THREAD

**Issue by Daniele-Corona-EOS** [EOS-Solutions/IDEAS#108]
Introdurre le azioni sopra indicate nella fatture d'acquisto registrate e nelle note di credito registrate. Esporre anche un metodo per poterlo utilizzare in eventuali personalizzazioni, come già fatto per le vendite.
In aggiunta, con una nuova azione "Crea & Scarica XML", dare la possibilità eventualmente sia per l'attivo che per il passivo di eseguire contemporaneamente sia la creazione che lo scarico dei file.

**Comment by alessandrovecchio** [comment]
Ciao,
procederemo con l'aggiunta di un'azione "Scarica XML" sulla lista di fatture e note credito registrate. Sarà scaricato un file per ogni documento selezionato e inserito inuno zip. Il file scaricato è quello prodotto dal documento per invio autofattura/integrazione.
Non aggiungeremo invece la voce "crea e scarica", mantenendo i processi separati.

**Comment by Chuucommie** [comment]
La modifica è stata effettuata e pubblicata OnPrem per BC19 e BC20, nelle versioni 19.0.143 e 20.0.30.

Saluti,
Ricardo
