### ISSUE TITLE
Sales Order: show net and gross weight in Infobox without setting qty to ship (WI 9723)

### ISSUE THREAD

**Issue by kurtmarschall** [EOS-Solutions/IDEAS#109]
**Is your feature request related to a problem? Please describe.**
The customer wants to see the weight (net and gross) for the sales line and for the whole sales order.

For now the weight is only calculated if the qty to ship is set.
![immagine](https://user-images.githubusercontent.com/78731376/164683161-5c479e3f-4d27-448d-804b-e06c1aa94e9a.png)

**Describe the solution you'd like**
Add the fields net weight and gross weight in sales line.
Add the fields in Doc. shipping info card.

**Describe alternatives you've considered**
nothing

**Additional context**
if an empty item is returned, this must not influence the weight of the sales order.

**Comment by Giuliano-Velludo-EOS** [comment]
@kurtmarschall per quale motivo richiedi di avere i peso netto e lordo anche a livello di riga ? Nella tabella Sales Line esistono già quei campi e sono unitari. E' quello il problema ?  Non basta mettere una visualizzazione eventuale del calcolo senza un capo fisico ?

**Comment by kurtmarschall** [comment]
@gvelludo: ok se inseriamo un campo calcolato nella subform

**Comment by Giuliano-Velludo-EOS** [comment]
EX066.04 DocShippingCDL rilasciate le versioni:
20.0.9
19.0.7
18.0.6

![image](https://user-images.githubusercontent.com/90828083/187878756-18ae2151-3277-476c-a1cc-cc089df6cd72.png)
