### ISSUE TITLE
Change the receipt date in the Purchase Order report

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#110]
Nella stampa dell'ordine di acquisto EOS (EOS Purchase Document (18122010, Richiesta report)) viene riportata, nelle righe, la "data di carico prevista".
Questa data, però, cumula i tempi di gestione warehouse e, pertanto, i clienti che usano tali tempi richiederanno, a standard, ai fornitori una data successiva all'effettivo bisogno.

La proposta è di cambiare la data nelle righe utilizzando la "data di carico richiesta" per avere una maggiore aderenza con le reali necessità di magazzino.

![image](https://user-images.githubusercontent.com/72971467/165983475-9cf5b39c-d677-45e3-a28a-4f7d775bf1fc.png)

**Comment by AndreaDiCeglie** [comment]
Ciao Matteo,

Questa modifica fatta a standard è un breaking change funzionale, che impatterebbe i clienti esistenti a cui magari sta bene il funzionameno attuale che (pur potrebbe essere minoritario).

I workaround sono di conseguenza:
- customizzare il report
- creare un report layout custom
- fare un custom con agganciarsi ad un evento dell'app e modificare il valore
- aggiungere un flag a setup nell'app solo per gestire questo switch (questa soluzione però non ci piace granché)...
