### ISSUE TITLE
License and All Object - Pages

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#111]
Mentre si fa un progetto, spesso e volentieri, accade (soprattutto lavorando con persone esterne al progetto) di prendere le stesse numerazioni degli oggetti, sarebbe comodo creare una pagina dove poter controllare gli oggetti liberi e in uso.

Allo stesso modo, sarebbe comodo avere una pagina che ti mostra tutti gli oggetti (soprattutto page extension), dato che le modifiche fatte in modalità progettazione creano le page-extension da 50000.

A mio parere sarebbe utile alla delivery, avere queste pagine in una App da installare con numerazione dedicata.

ho creato una pagina per vedere gli oggetti in licenza, se può essere utile --> [PageLicenseAndPermission.txt](https://github.com/EOS-Solutions/IDEAS/files/8660676/PageLicenseAndPermission.txt)

**Comment by alessandrovecchio** [comment]
Ciao, probabilmente la cosa migliore è mettere su sample (https://github.com/EOS-solutions/sample) la page in modo che sia pubblicata e tutti ne possano usufruire.
Non avremmo un'app in cui collocare tale page, che è più un tool che un prodotto da commercializzare.

Ciao
