### ISSUE TITLE
SPB - Calcolo Mov Bonus in modo massivo (WI 9586)

### ISSUE THREAD

**Issue by MarkusMoserEOS** [EOS-Solutions/IDEAS#112]
Ciao, 

nel modulo bonus (SPB) quando voglio fare un calcolo massivo e seleziono i record non mi riprende i record nel filtro:

![image](https://user-images.githubusercontent.com/101793608/168110739-c12c267f-933a-4e89-840d-402a509ebe15.png)
![image](https://user-images.githubusercontent.com/101793608/168110841-16edcd46-ef7b-45d9-a579-9be28faf4ea8.png)

la richiesta sarebbe di riportare quello che si seleziona anche nel filtro e che poi si calcolano tutte le righe selezionate.

**Comment by hemisphera** [comment]
Tecnicamente non è possibile trasportare il filtro di selezione da una page a un report.
L'alternativa qui sarebbe di trovare qualche criterio su un campo fisico per filtrare i contratti, come in questo esempio mettere A*|B* su campo codice.
Valutiamo di implementare una funzionalità tipo "batch" che consente di comporre una lista di contratti da calcolare e poi eseguire il calcolo sui record composti.

**Comment by MarkusMoserEOS** [comment]
Ok Grazie mille per la risposta!
Ciao
Markus

Von: The Dumb ***@***.***>
Gesendet: Mittwoch, 22. Juni 2022 11:19
An: EOS-Solutions/IDEAS ***@***.***>
Cc: Markus Moser ***@***.***>; Author ***@***.***>
Betreff: Re: [EOS-Solutions/IDEAS] SPB - Calcolo Mov Bonus in modo massivo (Issue #112)


Tecnicamente non è possibile trasportare il filtro di selezione da una page a un report.
L'alternativa qui sarebbe di trovare qualche criterio su un campo fisico per filtrare i contratti, come in questo esempio mettere A*|B* su campo codice.
Valutiamo di implementare una funzionalità tipo "batch" che consente di comporre una lista di contratti da calcolare e poi eseguire il calcolo sui record composti.

-
