### ISSUE TITLE
DocSolutions for Sharepoint - EOS069 Fields Mapping - Add Configuration Option that does not allow you to add manual values to the field visible in upload

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#113]
![image](https://user-images.githubusercontent.com/88732191/168957897-5d030f20-dd80-425c-8bf5-9f2cd28c5eda.png)

Add an option that does not allow you to add manual values to the field visible in upload

**Comment by AndreaDiCeglie** [comment]
The option "Visible in upload" is designed to allow user to change the values before uploading.
If the one field or function value must be set to Sharepoint with no modification the suggested setting is "Visible in upload=False".

Is not clear the need that this feature is satisfying

**Comment by massimocisco** [comment]
I would like to be able to configure, for each field visible in upload and mapped in Doc Solutions, if you can add or not during upload values not included in the list of values

**Comment by AndreaDiCeglie** [comment]
Cioè vorresti un setup per decidere se fare o no la validate sul campo evidenziato qui sotto ?

![image](https://user-images.githubusercontent.com/33353905/175273410-83829b27-406b-4594-a32a-8e2475e20f9a.png)

**Comment by massimocisco** [comment]
Si, esatto, 👌

**Comment by Carlobrus** [comment]
Avrei anche io una richiesta, non so se è la stessa o se può sostituire quella richiesta qui.
Si potrebbe aggiungere un nuovo flag:
Campo non modificabile
quindi se il realtivo campo (impostato come non modificabile) sarà visualizzato nella pagina di upload, non consentire all’utente di modificarne il valore!
nota: questo sarebbe utile per avere riscontro prima dell’upload, e costringere l’utente a modificare il dato in BC e non nella finestra di upload solamente.
