### ISSUE TITLE
FTE - Electronic Invoice for Italy - Gestione tag <AltriDatiGestionali> nei file in entrata

### ISSUE THREAD

**Issue by CristianCorega-Lutech** [EOS-Solutions/IDEAS#115]
Buongiorno, alcuni dei nostri clienti hanno richiesto ai loro fornitori l'indicazione di alcuni informazioni utili per la contabilizzazione del documento di acquisto all'interno del tag "AltriDatiGestionali". Sarebbe possibile gestire il dettaglio di tale tag in una struttura simile a quella dei DatiRiepilogo, DatiPagamento, etc.?
Una volta acquisiti, potrebbero essere facilmente sfruttabili per compilare, automaticamente o manualmente, informazioni come per esempio le dimensioni oppure campi custom sui documenti temporanei.
Grazie!

**Comment by matteomontanari** [comment]
Buongiorno Cristian
Ci siamo appuntati questa richiesta perché è interessante ma non l'abbiamo ancora pianificata a causa di altre attività urgenti.

Grazie del suggerimento

Matteo

**Comment by AndreaDiCeglie** [comment]
No other similar request were collected during last year. Closed as "low interest"
