### ISSUE TITLE
MDI - MS upgrade fields impact on synch profiles

### ISSUE THREAD

**Issue by HenrikAaen** [EOS-Solutions/IDEAS#117]
Hi Andrea,

Bellow is a new suggestion for a feature in EOS MDI.

Business scenario: Microsoft (as part of their upgrade) insert / remove / modify a field which are a part of MDi synch. profile.

Current solution: There is no indication and you will need manually to go through each synch. profile table everytime you have made a Microsoft patch / upgrade.

Suggested solution: A List of new/modified/deleted fields pr. data vs. the Synch. tables.
Example bellow field 52 are just been incl. in the table after last upgrade - We need to be able to spot it a mark it for [evaluation/Action.](url)

![image001 (1)](https://user-images.githubusercontent.com/86098729/170215253-46c15d8e-27d9-4634-9bc5-bfbc0bb2049e.png)

**Comment by AndreaDiCeglie** [comment]
Hi Henrik,

Thanks for your suggestion. In our dev team we have evaluated your request with attention.
Unfortunately the solution cannot be provided in the form you suggested.

Field table in Business central is a virtual table and we have no way "find new field" just running some query or function.

The field list in the screenshot above is showing all the fields available in BC (virtual table) and only the record modified in MDI setup are saved in DB.

We are evaluating something completely alternative that show the log history of all changes to tables and fields version by version. This require a centralized scheduled job that log modification for every single new release.

Andrea
