### ISSUE TITLE
OVR - EOS Line Closed dovrebbe annullare anche l'ordine di assemblaggio (WI 9647)

### ISSUE THREAD

**Issue by nmoreggio** [EOS-Solutions/IDEAS#118]
Utilizzo l'app Over- and Under-Delivery.

Nel caso di un ordine di vendita avente una riga con articolo con
- Sistema di rifornimento = Assemblaggio
- Criteri di assemblaggio = Assemblaggio su ordine
e quindi, in Sales Line, "Quantità per assemblaggio su ordine" >0, se imposto a true il flag "EOS Line Closed (18123300, Boolean)", l'ordine di assemblaggio rimane attivo.

A mio avviso sarebbe opportuno che in automatico l'ordine di assemblaggio venisse eliminato se il flag viene impostato a true, e ricreato se impostato a false.

Si può ottenere questo svuotando il campo Quantità per assemblaggio su ordine (cosa che faccio manualmente dopo aver chiuso la riga).

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciata EX047 Over delivery 
20.0.13
19.0.48
18.0.54
18.3.20
