### ISSUE TITLE
DocSolutions for Sharepoint - When deleting a record in BC ask whether to delete the related DCS documents as well

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#119]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreaDiCeglie** [comment]
From a functional perpesctive there are a lot of scenario in which this request can be considered valide, ther are also a lot of cases when this must no happen (I.E. when deleting ad document that is transformed / transfert to another table or document)

From a technical point of view DocSolutions cannot add code subscriber dynamically to tables
