### ISSUE TITLE
APP CFG Gestione caratteristiche di default sui livelli superiori al primo (WI 9752)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#121]
APP CFG
Sui livelli maggiori al primo le caratteristiche di default collegate agli articoli non vengono considerate
Secondo me, attiva da un setup può essere utile questa funzionalità 
•	nel caso una caratteristica non sia presente sul livello superiore assuma il valore di default
•	se una caratteristica è presente sul livello superiore, il livello “passato” dal livello superiore sia sovrascritto da quello di default dell’articolo

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciate versioni:
18.0.125
19.0.106
20.0.27
