### ISSUE TITLE
CAS-52158-P8G1H7 - EX061:Dimensions of the description fields (WI 9577)

### ISSUE THREAD

**Issue by KatrinaAmor-Robles-EOS** [EOS-Solutions/IDEAS#122]
CAS-52158-P8G1H7 

Un cliente ha la necessità di far estendere la descrizione per entrambe le tabelle (18006547 “EOS Inspection Plan Header” & 18006548 “EOS Inspection Plan Line”) a partire da 30 caratteri.
Sarebbe possibile aggiornare la dimensione del campo descrizione in modo che sia di almeno 50 - 100 caratteri?

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciate le seguenti versioni della EX061 PQA:
20.0.20
19.0.59
18.3.27
