### ISSUE TITLE
PRQ: Purchase request should support workflows with checks and rules on total amount (WI 10707)

### ISSUE THREAD

**Issue by AndreaDiCeglie** [EOS-Solutions/IDEAS#123]
Currently is not possibile to add a workflow with rules based on total cost of a purchase requeste because this information is not stored in a Physical field.

Step to implement:
- Add a stored field with total amount on Purchase Request Header
- Add one to "workflow Table relation" table
2000000000 /467/15 
454/22 
![image](https://user-images.githubusercontent.com/33353905/173015158-07877b95-4c4c-40d8-8b6f-f8c25e7922b0.png)

- Create or modify the workflow template in order to block PRQ based on amount tresholds

**Comment by hemisphera** [comment]
Released
