### ISSUE TITLE
Shipping agent service and time in purchase orders and MRP

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#124]
La gestione degli acquisti non prevede il calcolo della durata della spedizione, così come invece avviene per le vendite.
Questa mancanza diventa importante quando si creano acquisti con spedizioni ExWorks e lead time molto lunghi in quanto non è possibili indicare una data corretta al fornitore ed è necessario eseguire calcoli ed adattamenti manuali.

L'ideale, secondo me, sarebbe quello di implementare la gestione dei servizi spedizionieri e della durata della spedizione nei fornitori e nei documenti di acquisto così da avere il medesimo comportamento delle vendite.

**Comment by AndreaDiCeglie** [comment]
Ciao Matteo , 

Abbiamo visto e valutato la richiesta, al momento non abbiamo un app in cui metterla come feature e l'estensione lato acquisti di una feature esistente in vendita dovrebbe essere sottoposta a Microsoft qui: 

https://experience.dynamics.com/ideas/search-ideas/?q=shipping%20purchase&forum=e288ef32-82ed-e611-8101-5065f38b21f1&page=3

**Comment by MatCive** [comment]
Grazie, ho trovato la seguente proposta: https://experience.dynamics.com/ideas/idea/?ideaid=16918934-ea65-e911-b047-0003ff68c184
