### ISSUE TITLE
CMS: valori fissi per periodo

### ISSUE THREAD

**Issue by kurtmarschall** [EOS-Solutions/IDEAS#125]
Spesso i clienti chiedono un valore fisso in euro per un periodo. Attualmente questo non è gestito nella App CMS

**Comment by kurtmarschall** [comment]
Questa richiesta viene sviluppata con il TDE001038 "CMS: Fixbeträge pro Periode für Agenten"

**Comment by AndreaDiCeglie** [comment]
Ciao Kurt, ci risulta che la provvigione fissa sia già gestita dall'app. Servirebbero maggiori dettagli. Ho visto il TD ma non è chiaro, consiglio di parlarne con Finance circle
