### ISSUE TITLE
CWS: Metodo di cancellazione per carichi warehouse

### ISSUE THREAD

**Issue by danielwegleiter** [EOS-Solutions/IDEAS#126]
Replicare il funzionamento "Metodo di cancellazione documento warehouse", introdotto per le spedizioni anche per i carichi warehouse.
Attualmente una custom che abbiamo fatto da molti clienti e che viene spesso richiesto.

![image](https://user-images.githubusercontent.com/108135945/175545276-fa1f9c4d-bb6a-44c5-a53d-2698cba0bc27.png)

**Comment by AndreaDiCeglie** [comment]
Hi Daniel, could you send us the deployed customization ?

(Hint: fix page caption from Setup to Setup CWS)

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao @danielwegleiter riesci a farci avere il codice del custom ?

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciata funzionalità con altra IDEAS
