### ISSUE TITLE
Proposal for new APP - Import/Export dimensions

### ISSUE THREAD

**Issue by IlariaEos** [EOS-Solutions/IDEAS#127]
Buongiorno,

nelle versioni di NAV esisteva un tool che permetteva di esportare/reimportare le dimensioni, così da snellire di molto le procedure in fase di chiusura/apertura anno fiscale.

Infatti se presente l'obbligatorietà delle dimensioni nei conti C/G viene appesantita non solo la procedura che deve creare molte più righe ma anche il sistema rischiando il blocco degli altri utenti.

Sono quindi a proporre la creazione di un APP che svolga la stessa funzione.

Grazie della disponibilità, saluti.
Ilaria

**Comment by AndreaDiCeglie** [comment]
Thanks for suggestion it will be evaluated by competence circle.
Which existing tool are you referencing ?

**Comment by IlariaEos** [comment]
Ciao,
grazie dell'interesse.

Noi avevamo questo tool:

![image](https://user-images.githubusercontent.com/100845253/178773839-dc437b15-aba1-47cc-8c3d-5cc1bc3de25f.png)

In sostanza un semplice xml port che esporta/importa la tabella 352.

Sentiamoci per eventuali dubbi, grazie.
