### ISSUE TITLE
CVC: Add dedicated "Source Code" for compensation journal lines (10657)

### ISSUE THREAD

**Issue by hemisphera** [EOS-Solutions/IDEAS#128]
It would be useful if the CVC app allows specifying a dedicated "Source Code" for the journal lines that it creates. This "Source Code" would then be specified in the "Source Code Setup" table and all journal lines that are created by CVC have "Source Code" set to this value.
This would allow to identify journal lines that have been created from CVC in a later moment, for example when posting the journal lines.

**Comment by AndreaDiCeglie** [comment]
ok for BC19-20

**Comment by AndreaDiCeglie** [comment]
Add telemetry to measure most used functions

**Comment by EOSValerioBelenkov** [comment]
Avaliable on versions 14.0.18.0, 20.0.6.0 and 21.0.3.0
