### ISSUE TITLE
Tipo vendita Tutti i Clienti sulla matrice prezzi dell'APP CFG (WI 9720)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#129]
Al  momento è possibile creare righe di listino con tipo prezzo Cliente o Gruppo Prezzi. L'opzione Tutti i clienti , come sulla gestione listini standard, non è disponibile

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciate le versioni del CFG
18.0.138
19.0.119
20.0.38
