### ISSUE TITLE
EDS cascade renaming to User Group table (WI 7036)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#13]
This feature is related to a problem I recently had.
I changed many User Group names because of the internal naming policy change. Then I moved to the EDS authorizations but there I found the old naming!!

I'd like to have an automatic name update in the EDS User Permission table when I change a User Group name.

**Comment by AndreaDiCeglie** [comment]
Not renaming EDS groups is a bug, added in backlog

**Comment by Nyryus** [comment]
Delivered in version 

- 14.0.86
- 17.0.15
- 18.0.23
