### ISSUE TITLE
warehouse receipment

### ISSUE THREAD

**Issue by AnnalisaM77** [EOS-Solutions/IDEAS#130]
Si richiede che nella testata del carico warehouse, il campo "Nr. Destinazione documento" che contiene il nr cliente, si comporti con la stessa logica del campo di testata ordini. Ossia che accetti l'inserimento anche parziale della ragione sociale, compilando poi in automatico il nr. Cliente. Spesso infatti non ci si ricorda il codice cliente.

**Comment by AndreaDiCeglie** [comment]
With the current implementation is not possible to implement a native autocomplete.

We are evaluating if remove all the code that provide a customer filtered list using che full customer list

                        Rec."EOS Document Destination Type"::Customer:
                            begin
                                WhseShptHeader := Rec;
                                WhseShptHeader."EOS Combine Shipments" := false;
                                WhseShptHeader."EOS Document Destination Type" := WhseShptHeader."EOS Document Destination Type"::Customer;
                                WhseShptHeader."EOS Document Destination No." := '';

                                ActiveWhseRequest.SetRange(Location_Code, WhseShptHeader."Location Code");
                                ActiveWhseRequest.SetRange(Type, WhseRequest.Type::Outbound);
                                ActiveWhseRequest.SetRange(Destination_Type, WhseRequest."Destination Type"::Customer);
                                ActiveWhseRequest.Open();
                                while ActiveWhseRequest.Read() do
                                    if Customer.Get(ActiveWhseRequest.Destination_No_) then begin
                                        TempCustomer.Init();
                                        TempCustomer.TransferFields(Customer);
                                        if not TempCustomer.Insert() then;
                                    end;

                                if Page.RunModal(0, TempCustomer) = ACTION::LookupOK then begin
                                    Text := TempCustomer."No.";
                                    exit(true);
                                end else
                                    exit(false);
                            end;

**Comment by Giuliano-Velludo-EOS** [comment]
Abbiamo discusso la cosa con il competence circle di riferimento e la richiesta è stata scartata.
