### ISSUE TITLE
CDW: (miglioria) prendi righe da giornale (WI 10692)

### ISSUE THREAD

**Issue by Dario-Zaniboni-EOS** [EOS-Solutions/IDEAS#131]
Segnalo che la funzione “Prendi righe” (spedizione), presente all’interno della pagina “Giornale chiudi documenti”, riporta il nr. CWS solamente in corrispondenza delle righe di raggruppamento e non nelle righe di dettaglio del documento.
In questo modo, filtrando o cercando il nr. CWS, si visualizza la sola riga di raggruppamento.

![image](https://user-images.githubusercontent.com/106167410/177810123-8fc8b6c8-dac7-406a-b8a9-a0a2791f12d1.png)

![image](https://user-images.githubusercontent.com/106167410/177810040-019c87c0-fc14-4653-9282-9afaaf44d7a0.png)

NOTA La colonna “Nr. documento” è invece popolata correttamente.

**Comment by hemisphera** [comment]
Available in 22.0.13+
