### ISSUE TITLE
Suggerimento/Richiesta di implementazione (ADR) (WI 11539)

### ISSUE THREAD

**Issue by Tarcisio-Busato-EOS** [EOS-Solutions/IDEAS#132]
Buongiorno, nel setup di figura, è possibile selezionare da quale campo prendere l’indirizzo email.
Nel caso di ordini di vendita, sarebbe comodo poter selezionare come “Tipo origine E-Mail” il 36.5052 (ancora meglio con la logica Generale/Fatt/Sped).
Grazie per l’attenzione
Tarcisio
.

**Additional context**

![adr](https://user-images.githubusercontent.com/109072981/178239622-4fbabdbc-257f-4cda-a7ab-caa4d03964d8.png)

**Comment by AndreaDiCeglie** [comment]
E' possibile implementarlo, sia come standard che come custom (su github/Sample è disponbile un esempio)
Solitamente una valida alternativa è utilizzare il Ruolo professionale in modo da avere tutti i contatti utilizzati per la spedizione dei documenti raggruppati per ruolo.

L'implementazione viene comunque messa in backlog con priorità bassa

**Comment by Stefano-Primo-EOS** [comment]
Rilasciato nelle versioni:
 - 23.0.16
 - 24.0.17
