### ISSUE TITLE
PQA: Implementare ordini di controllo sui resi discriminando il tipo di ordine su eventi di carico e spedizione

### ISSUE THREAD

**Issue by stefanocastellani** [EOS-Solutions/IDEAS#133]
**Is your feature request related to a problem? Please describe.**
Non è possibile generare automaticamente ordini di controllo qualità alla registrazione di carichi da reso vendita, né manualmente da ordini di reso.

**Describe the solution you'd like**
Nella matrice di controllo qualità sarebbe bello differenziare gli eventi "Carico" e "Spedizione" per tipologia di documento di origine.
Nel carico differenziare tra: ordine di acquisto, ordine di trasferimento e ordine di reso vendita.
Nella spedizione differenziare tra: ordine di vendita, ordine di trasferimento e ordine di reso acquisto.

Si può inoltre aggiungere tra le opzioni degli eventi (Tipo di Controllo) l'ordine di reso vendita?

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreaDiCeglie** [comment]
Per quanto riguarda i resi se non sbaglio è possibile fare setup "incrociati".
Esempio: 
Spedizione - Fornitore
Carico - cliente

Per i trasferimenti invece credo serva uno sviluppo ad hoc
