### ISSUE TITLE
app VMI - Verifica Dichiarazione Intento

### ISSUE THREAD

**Issue by ErikaC82** [EOS-Solutions/IDEAS#134]
Nel vecchio Navision  c'era una funzione dentro la Dichiarazione Intento che consentiva di verificarne la validità sul sito dell'agenzia delle Entrate.

è possibile riportarlo anche in app?

**Comment by AndreaDiCeglie** [comment]
Abbiamo verificato ed è fattibile

**Comment by Chuucommie** [comment]
Ciao,

La modifica è stata effettuata e pubblicata per BC18, BC19, BC20 e BC21 nelle versioni 18.0.77 , 19.0.124, 20.0.63 e 21.0.5

Saluti,
Ricardo
