### ISSUE TITLE
Estensione app ECS a spedizioni assitenza registrate

### ISSUE THREAD

**Issue by MauroEOS** [EOS-Solutions/IDEAS#135]
Attualmente la app ECS permette la gestione di fatture cumulative basate solo su spedizioni vendita registrate.
Si richiede la possibilità di poter utilizzare l'app ECS anche nel caso di spedizioni assistenza registrate.

**Comment by AndreaDiCeglie** [comment]
Richiesta lecita che richiede una valutazione economica

**Comment by AndreaDiCeglie** [comment]
non sono previsti investimenti sul modulo assistenza di BC poichè strategicamente EOS persegue l'implementazione delle app di Dynamics CE in questi scenari
