### ISSUE TITLE
PQA: Rename "Test type" labes in order to align all of them (WI 10104)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#136]
La pagina "EOS Sample Size Test Type List (18006588, List)" viene estratta in italiano con due label differenti:
- Da menu, con "Campionatura (PQA)":

![image](https://user-images.githubusercontent.com/72971467/182168122-8e71e83f-dcdf-4235-a1b3-43a622b86978.png)

- Da "Setup matrice di controllo", con "Tipo test":

![image](https://user-images.githubusercontent.com/72971467/182168260-17b89ef6-c138-4e14-b417-2a7e83be6f2e.png)

Questo crea un po' di confusione in chi non ha dimistichezza con il prodotto.

**Comment by Giuliano-Velludo-EOS** [comment]
rilasciate le seguenti versioni:
20.0.31
19.0.69
18.3.38
