### ISSUE TITLE
FTE -  Ciclo passivo - Possibilità di aggiornamento anagrafica fornitore da file xml importato (WI 14877)

### ISSUE THREAD

**Issue by MauroEOS** [EOS-Solutions/IDEAS#137]
Sarebbe interessante poter avere una funzionalità che consenta l'aggiornamento  dell’anagrafica fornitore in BC tramite l’xml delle fatture di acquisto ricevute.

**Comment by AndreaDiCeglie** [comment]
In particolare di quali campi ?

**Comment by AndreaDiCeglie** [comment]
L'idea è quella di modificare questa action in Create or Modify

![image](https://user-images.githubusercontent.com/33353905/190161658-3eae60b4-25fe-40e6-ad0a-6d83cbe645c3.png)

**Comment by MauroEOS** [comment]
Ciao, grazie per il feedback. I campi interessati potrebbero essere la ragione sociale, la P.IVA.. i campi relativi all'indirizzo.

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno @MauroEOS , in Integration23 abbiamo rilasciato la funzionalità richiesta.
E' stata aggiunta una nuova azione "Aggiorna dati fornitore esistente" che va ad aggiornare i dati relativi all'anagrafica fornitore (Nome, Indirizzo, P.IVA) prendendoli dall'XML 

![image](https://github.com/EOS-Solutions/IDEAS/assets/100839302/03b5052d-c5e4-43f6-93e5-e5038be2bb3f)


http://labs.eos.it:8083/integration23/?company=LABS&dc=0

Potrebbe darci riscontro se quanto sviluppato è conforme a quanto atteso?
Saluti, Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno, confermo rilascio Ideas sviluppata a partire dalle versioni FTE  22.0.87, 23.0.75, 24.0.19
