### ISSUE TITLE
PQA: Grammar error correction

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#138]
In fase di creazione dell'ordine di controllo da Carico Whse, in caso di mancanza di setup viene esposto un errore.
"Un errore", però, deve essere scritto senza apostrofo:

![image](https://user-images.githubusercontent.com/72971467/182419381-cf484a55-8bfc-40c5-8ad8-8b7edb70fe10.png)

**Comment by f0ffee** [comment]
Ciao, per le traduzioni delle nostre app è disponibile un repository dove potete proporre le correzioni autonomamente

https://github.com/EOS-Solutions/Translations
