### ISSUE TITLE
DocSolutions for Sharepoint - Componente aggiuntivo di Outlook: aggiungere allegati di messaggi e-mail ai record Business Central

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#142]
Componente aggiuntivo di Outlook: aggiungere allegati di messaggi e-mail ai record Business Central.

Replicare la funzione:

https://docs.microsoft.com/it-it/dynamics365-release-plan/2022wave1/smb/dynamics365-business-central/outlook-add-in-add-attachments-emails-directly-business-central-documents

per allegare gli allegati e-mail a DocSolutions.

**Comment by AndreaDiCeglie** [comment]
Buona idea, è da capire cosa implica...
