### ISSUE TITLE
Show Comments on Documents - Reopen page (WI 10715)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#145]
Hi,

for now the comments are shown only when the customer is selected on the sales quote, sales order, etc.

![image](https://user-images.githubusercontent.com/107125213/194531150-14acb4ca-2be3-409f-944f-e87e685d67d7.png)

As soon as the page is closed the user is not able to reopen the page to see the comments shown initially.

![image](https://user-images.githubusercontent.com/107125213/194531530-d65f924a-d042-48f8-af84-358f20ef1b59.png)

Therefor my request is to create a subform that extends the pages sales quote, sales order, sales invoice, etc. to see. And in the subform are shown the comments according to the flags "Show on Orders", "Show on Invoices", etc.

![image](https://user-images.githubusercontent.com/107125213/194532146-ee990682-58e4-45d6-a304-b962071c6abe.png)

Thanks

**Comment by AndreaDiCeglie** [comment]
The idea is evaluated positively, but the implementation using a subform is not.
We will implement an action to recall the page instead of including a subform
