### ISSUE TITLE
Show Comments on Documents - CWS connector with Warehouse Shipment ( WI 10752 )

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#146]
Hi,

same request as #145 but for warehouse shipments.
Add a flag "Show on Warehouse Shipment" on the table of the comments.

![image](https://user-images.githubusercontent.com/107125213/194533345-7e59d645-5f45-4e64-899d-be5217c313e9.png)

Since it is possible to insert the customer on the warhouse shipment header add the subform of #145 also on the warehouse shipment to pass information to a logistics operator. The subform should show the comment lines linked to the customer which have the flag "Show on Warehouse Shipment" set.

![image](https://user-images.githubusercontent.com/107125213/194533158-2879f6f9-0626-4282-85f1-c6c57d4a44fa.png)

Cheers

**Comment by AndreaDiCeglie** [comment]
The sames as 145
