### ISSUE TITLE
Cliente AEB - App EPM - Saldo Vuoti: Visualizzazione MultiConto (WI 11059)

### ISSUE THREAD

**Issue by mattiaoggioni** [EOS-Solutions/IDEAS#149]
PUNTO 1:
Si richiede di modificare la funzionalità di "Saldo vuoti EPM" in modo che dal campo "Nr. Conto" sia possibile selezionare più codici cliente, fornitore, spedizioniere a seconda del tipo conto selezionato nel campo "Tipo conto":

Utilizzando la funzione di "Ricalcola" deve quindi essere presentato il calcolo di tutti i Nr conto inseriti, con spaccatura di riga per Nr conto.
 
PUNTO 2:
Utilizzando la funzione di "Ricalcola" con Nr conto vuoto, devono essere presentati i saldi di tutti i clienti (se diversi da 0). Allo stesso modo se utilizzo un tipo conto "Spedizioniere" o "Fornitore" devo avere il riepilogativo di saldi diversi da 0 rispettivamente per tutti gli spedizionieri o per tutti i fornitori.
 
PUNTO 3:
Riportare a livello di riga i campi "Nr conto", "Nome conto" e "Nr conto - Fatt", che si compilino nella seguente modalità:
Tipo conto = cliente
•	Nr conto = Nr cliente a cui è riferito il saldo
•	Nome conto = Nome cliente a cui è riferito il saldo
•	Nr conto - Fatt = Nr cliente di fatturazione associato al Nr cliente a cui si riferisce il saldo
Tipo conto = fornitore
•	Nr conto = Nr Fornitore a cui è riferito il saldo
•	Nome conto = Nome Fornitore a cui è riferito il saldo
•	Nr conto - Fatt = Nr fornitore - pagare a associato al Nr fornitore a cui si riferisce il saldo
Tipo conto = agente
•	Nr conto = Nr Spedizioniere inserito nella tabella degli spedizionieri associato all'agente a cui è riferito il saldo
•	Nome conto = Nome del fornitore associato a Nr spedizioniere
•	Nr conto - Fatt = Nr fornitore - pagare a associato al Nr spedizioniere della tabella spedizionieri
 
 
PUNTO 4
Creare all'interno della tabella movimenti contenitori il campo Nr spedizione CWS.
Per le righe il cui tipo documento è "Spedizioni di vendita", il "Nr spedizione CWS" deve essere valorizzato in base alla CWS che contiene la spedizione di vendita registrata. Come avviene per i movimenti contabili articolo.

**[AEB - SALDO VUOTI EPM - VISULAIZZAZIONE MULTICONTO.docx](https://github.com/EOS-Solutions/IDEAS/files/9838367/AEB.-.SALDO.VUOTI.EPM.-.VISULAIZZAZIONE.MULTICONTO.docx)**

**Comment by Giuliano-Velludo-EOS** [comment]
E' arrivata la conferma da parte del cliente AEB
