### ISSUE TITLE
APP PQA - Aggiunta factbox e link al documento di riferimento (7035)

### ISSUE THREAD

**Issue by MartaTremolada** [EOS-Solutions/IDEAS#15]
1.	Aggiungere la factbox per gli ordini di controllo con la possibilità di aggiungere note e allegati, in modo da allineare l'ordine di controllo a tutti gli altri documenti
2.	Creare il link per il documento di riferimento a cui è associato l’ordine di controllo per accedere direttamente al documento

![riferimento](https://user-images.githubusercontent.com/78031197/105856357-73d09400-5fe9-11eb-88a3-940252c84451.jpg)

**Comment by Chuucommie** [comment]
Added factbox with links and notes
