### ISSUE TITLE
Add "Document Class" to "Invoicing Method Fields" (app "Extended Combine Shipment")

### ISSUE THREAD

**Issue by rdemasi987** [EOS-Solutions/IDEAS#153]
In the report "Extended Combine Shipments (ECS)", I need to combine shipments by "Document Class":
![Extended Combine Shipments (ECS)](https://user-images.githubusercontent.com/75783517/200545092-eac0a70d-caaa-440d-985a-19db4308763b.png)

I was wondering if you could add "Document Class" to the "Invoicing Method Fields":
![image](https://user-images.githubusercontent.com/75783517/200545334-b4d4646d-2fe8-401e-a6b8-b6a85f21e70a.png)

Thanks

**Comment by AndreaDiCeglie** [comment]
La richiesta è fattibile a standard tuttavia è possibile farlo anche custom seguendo questo esempio fatto apposta per gestire campi aggiuntivi e custom.

https://github.com/EOS-Solutions/Sample/blob/master/EX050.CombineShipment/Codeunit%2050001%20EOS%20ECS%20Event%20Subscriber.al

**Comment by rdemasi987** [comment]
L'ho già fatto da alcuni clienti seguendo il vostro esempio.
Visto che mi è capitata diverse volte come richiesta ho pensato potesse essere utile.

Grazie
