### ISSUE TITLE
CFG Prices Matrix  Worksheet (WI 10666)

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#154]
**General / Requirement**
To maintain the sales prices of the configurator in the “Matrix prices (CFG)” table, a “sales price worksheet” with the functions “suggest retail price” and “accept price proposal” is required.

**Adjustments**
(1) new table “CFG Prices Matrix  Worksheet”
- Copy of table EOS028 CFG Prices Matrix (18091282) and an additional field “New Sales Price” -

(2) new Page “CFG Prices Matrix  Worksheet”

(3) "Suggest retail price" function
This function is intended to pull the selected records from the table EOS028 CFG Prices Matrix (18091282), calculate/propose a new retail price according to the specifications and enter it in the new table “CFG Prices Matrix Worksheet”.
- Similar to the function of the same name on the Sales Price Worksheet page (7023, Worksheet) -

(4) Key Code
If characteristics / characteristic values ​​are changed in the new “CFG Prices Matrix Worksheet” table, the KEY CODE must be generated again!

(5) Accept price proposal function
With this function, the selected data records from the new table "CFG Prices Matrix Worksheet" are to be transferred to the table EOS028 CFG Prices Matrix (18091282),
- Similar to the function of the same name on the Sales Price Worksheet page (7023, Worksheet) -

**Comment by Giuliano-Velludo-EOS** [comment]
Released version 21.0.26 e 20.0.98
