### ISSUE TITLE
CFG: Sales Type "Campaign" in the "Price Matrix (CFG) table (WI 10663)

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#155]
**Is your feature request related to a problem? Please describe.**
In the BC standard, sales prices can be maintained with the following sales types:
• Customer
• Customer price group
• All customers
• Campaign

The "Campaign" sales type is not available in the Matrix Price (CFG) of the EOS Product Configurator.

**Describe the solution you'd like**
Extension of price maintenance and pricing to include the "campaign" sales type.

**Describe alternatives you've considered**
no alternative

**Additional context**
![image](https://user-images.githubusercontent.com/90207505/201318487-c320343b-17be-4d54-ad02-0c93487c465a.png)
![image](https://user-images.githubusercontent.com/90207505/201318532-b9e88b0b-f6e3-4dd7-b95d-9f981d3c7539.png)

**Comment by Giuliano-Velludo-EOS** [comment]
Released in App Versions 21.0.27 20.0.100
