### ISSUE TITLE
OVR: Ignore Outstanding Quantity on Warehouse Shipment + Warehouse Receipt

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#156]
Aggiungere un campo in Warehouse Shipment Line + Warehouse Receipt Line. Mettendo il flag durante la registrazione viene chiuso la riga di origine tramite l'OVR.

chiedere a Davide Perez Cuevas per implementazioni precedenti.

**Comment by Giuliano-Velludo-EOS** [comment]
Scritta mail a Davide per avere il codice dell'implementazione

**Comment by Giuliano-Velludo-EOS** [comment]
Nessun feedback ricevuto.
