### ISSUE TITLE
EDS: EDS Function for payment release on posted purchase invoices

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#157]
When a purchase invoice is posted than the payment is not actually released.

Therefore add a setup-field where to enter a code which is brought to the field "On Hold" of the unposted purchase invoice header.

When posting the invoice the value will be writen onto the vendor ledger entries.

With a EDS-Function on the posted purchase invoice there should be cleared the value on the vendor ledger entries.

(Contact me for previous implementations)

**Comment by hemisphera** [comment]
This will not be implemented in EDS standard, as this is too process-specific.

We have, however, a open source library of EDS-functions that are hosted here on GitHub (https://github.com/EOS-Solutions/Sample) where we could integrate this one to facilitate implementations on customers. If you're ok with publishing it there, you can send me the code and we will publish it.
