### ISSUE TITLE
Storno CWS - HUM - miglioria

### ISSUE THREAD

**Issue by giovannileorin** [EOS-Solutions/IDEAS#158]
Nel caso di storno delle righe di una CWS con Hum presenti il "ricarico" delle hum

**Comment by Giuliano-Velludo-EOS** [comment]
Modifica non realizzabile. Una HUM potrebbe essere "composta" da n righe di CWS e se lo storno è parziale si romperebbero le "HUM". Piuttosto va pensata una funzione di riapertura di una HUM nel caso tutte le righe con cui è stata spedita risultino stornate.
