### ISSUE TITLE
Riepilogo/analisi magazzino/analisi spedizioni (WI 13227)

### ISSUE THREAD

**Issue by giovannileorin** [EOS-Solutions/IDEAS#159]
Riepilogo che consenta ai clienti di gestire un task di magazzino che abbini:
Item ledger entry
Whse led entry
Hum

Oltre ad un riepilogo sarebbero interessanti funzioni di rettifica/riclassifica/imballo (o disimballo) hum

Nella stessa modalità, per poter gestire velocemente le assegnazioni sarebbe utile un task che consenta di vedere le righe di vendita e che consenta di assegnare (o disassegnare) massivamente le hum sia nel caso di spedizioni da whse o sia nel caso di spedizione da ordine

**Comment by AndreaDiCeglie** [comment]
Le specifiche sono insufficienti e molto ampie. Da quanto si può capire sembra la descrizione di 3 app diversi

**Comment by AndreaDiCeglie** [comment]
> Le specifiche sono insufficienti e molto ampie. Da quanto si può capire sembra la descrizione di 3 app diversi

Data l'ampiezza degli sviluppi è argomento da portare al competence circle per discussione e raccolta delle esperienze fatte in delivery

**Comment by Giuliano-Velludo-EOS** [comment]
@giovannileorin per quanto riguarda i primo e il terzo punto potresti fornirmi degli esempi o nel caso le funzioni siano già state realizzate da una Delivery i sorgenti ?

Il secondo punto è da analizzare con il competence center di riferimento anche perchè è una funzionalità molto estesa. Anche in questo caso ti chiederei degli eventuali esempi se avete sviluppato qualcosa.

**Comment by AndreaDiCeglie** [comment]
La richiesta è chiusa poichè collegata a 

https://github.com/EOS-Solutions/IDEAS/issues/233 e verrà valutata / realizzata con quella
