### ISSUE TITLE
PDA - tool miglioria

### ISSUE THREAD

**Issue by giovannileorin** [EOS-Solutions/IDEAS#160]
Creazione di template che vengono caricati con l'installazione dell'app sulla base di modifiche più frequenti.

esempi:
1) modifica data documento fattura di acquisto
2) modifica data documento carico acquisto
3) modifica codice iva (vendita/acquisto)

etc......

come avviene per l'eds che alcuni template "standard" vengono caricati

**Comment by AndreaDiCeglie** [comment]
Esiste un repository GIT nato per contenere i template e consentire alla community di contribuire alla crescita e alla miglioria della libreria dei template https://github.com/EOS-Solutions/EX065-PostedDataAdministrationTool/tree/master/Templates 

L'idea originale era di poter caricare i template direttamente nel PDA tool tramite un integrazione Web Service. Per questioni di tempo ci siamo poi limitati a implementare una funzione di export ed import dei template.

Il caricamento di template hardcoded non verrà implementato
