### ISSUE TITLE
distinta fornitore - miglioria

### ISSUE THREAD

**Issue by giovannileorin** [EOS-Solutions/IDEAS#161]
Integrare la struttura della distinta fornitore per la creazione dell'XML-TXT per il pagamento in banca anche per le partite clienti.

**Comment by AndreaDiCeglie** [comment]
Da discutere con Finance competence circle (F. Petrera). Svilupparlo come extension può essere molto difficile per via delle sovrapposizioni allo standard

**Comment by AndreaDiCeglie** [comment]
Closer as "low interest"
