### ISSUE TITLE
Riepilogo righe trasferimento registrate

### ISSUE THREAD

**Issue by giovannileorin** [EOS-Solutions/IDEAS#162]
Come i riepiloghi PSU di acquisto/vendita potrebbe essere utile un riepilogo sulle righe di spedizione / carico di trasferimento registrato (nel caso delle spedizioni anche il riferimento CWS) con l'indicazione di ordine di produzione, ordine conto lavoro etc.

è una pagina che diversi clienti chiedono per sapere, nel caso di conto lavoro, qual'è il DDT di invio dei componenti

**Comment by AndreaDiCeglie** [comment]
A partire da BC21 i riepiloghi righe vendite e acquisti sono stati implementati da Microsoft stessa. hai controllato se esistono page per le tabelle indicate ?

**Comment by giovannileorin** [comment]
ciao Andrea,

non so perchè sia stata chiusa questa, ho verificato in ambiente Integration (che è una 21) e sinceramente mi sembra di non averle trovate.

grazie

**Comment by AndreaDiCeglie** [comment]
Ciao, è stata rifiutata. Mancava la label.
