### ISSUE TITLE
CFG: Extension of the neutral rules by the fields "To Characteristic Value x" (x = 1 - 10) (WI 10891)

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#163]
**Is your feature request related to a problem? Please describe.**
It is possible to enter "Structure" and "Dimension" type properties in the "Neutral Rules" on the item.
However, no from/to values or <= and > or >= can be entered for properties of the "Measure" type!

**Describe the solution you'd like**
The neutral rules are to be expanded in the same way as the matrix price table by the fields "to characteristic value 1" to "to characteristic value 10" and the functionality is to be adjusted in accordance with the matrix prices.

**Describe alternatives you've considered**
Alternatively, the use of <= and > or >= is conceivable.

**Additional context**
-

**Comment by Giuliano-Velludo-EOS** [comment]
Released versions 21.0.58 20.0.175.
We'll provide documentation in the next few days.
