### ISSUE TITLE
APP cfg Gestire le condizioni sulle formule di calcolo (WI 10888)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#164]
Si richiede la possibilità di gestire delle condizioni legate alle formule di calcolo utilizzate in distinta base nei cicli , formule trasferimento valore  dell'app CFG 
Nelle immagini allegate tre esempi 

![cond1](https://user-images.githubusercontent.com/74410047/207373603-0d42190d-928b-48f5-9968-647adf3e2750.jpg)

![image](https://user-images.githubusercontent.com/74410047/207373808-620a504f-00c5-46f3-8086-d6210a453858.png)

![image](https://user-images.githubusercontent.com/74410047/207373909-6bfd9467-c91d-492e-9c90-869a0721658a.png)

**Comment by Giuliano-Velludo-EOS** [comment]
Released versions 21.0.58 20.0.175.
We'll provide documentation in the next few days.
