### ISSUE TITLE
Add EOS custom fields to the "Posted Whse. Receipt Header"

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#165]
Aggiungere nella tabella "Posted Whse. Receipt Header (7318)" e nelle pagine "Posted Whse. Receipt (7330, Document)" e "Posted Whse. Receipt List (7333, List)" le informazioni EOS in riferimento alla destinazione del documento: 

![image](https://user-images.githubusercontent.com/72971467/208391318-60f3a0af-2e5c-4c8b-b12e-277389ceb316.png)

**Comment by AndreaDiCeglie** [comment]
E' da chiarire la cardinalità tra CWS e Posted Whse. Receipt Header ossia , come vengono riportate in caso di N spedizioni ? (ti contatterà Giuliano)
