### ISSUE TITLE
Calcolo delle provvigioni in base alle soglie di vendita totale

### ISSUE THREAD

**Issue by AG1GA** [EOS-Solutions/IDEAS#166]
Buongiorno.

Il mio cliente ha avuto la necessita di calcolare le provvigioni in base alle vendite totali, per esempio:
•	>=1 euro .. < 5000 euro di venduto – 10% di provvigioni;
•	>= 5000 euro .. < 10.000 euro di venduto – 12% di provvigioni;
•	>= 10.000 euro di venduto – 15% di provvigioni;
 
Quindi, l'idea per migliorare l'app CMS è di introdurre il calcolo per gli scaglioni delle vendite totali (tutte le vendite precedenti di quella liquidazione/ di quell'anno vengono sommate (la fattura di vendita da registrare inclusa) e così viene assegnata la provvigione in base allo scaglione impostato).

![image](https://user-images.githubusercontent.com/121032674/208427309-6fd19d5b-b708-4246-a3b8-8d79668b2829.png)

**Comment by AndreaDiCeglie** [comment]
Buongiorno Agne, questa modalità è quella supportata dai Bonus che precedentemente si era tentato di implementare sulle provvigioni con esiti negativi.
Il calcolo delle provvigioni di vendita è pensato per funzionare per singola riga, il cumulo di righe non è supportato e al momento non c'è intenzione di supportarlo.

**Comment by AG1GA** [comment]
Gentile Andrea,

Grazie per il riscontro.

Cordiali saluti
Agne Galinskaite

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
