### ISSUE TITLE
Add EOS transfer order custom fields in  Subcontracting Transfer orders (WI 10952)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#167]
Per avere omogeneità di funzionamento, aggiungere i campi e le funzionalità EOS presenti negli ordini di trasferimento anche negli ordini di trasferimento di conto lavoro:

![image](https://user-images.githubusercontent.com/72971467/209678783-f8d8bdc5-4172-4f39-a6be-319c243b9e55.png)

![image](https://user-images.githubusercontent.com/72971467/209678723-66ff86de-7f2b-49b5-9346-72951c8b4b26.png)

**Comment by EOSloresgara** [comment]
Released for Eos.EX066.05.DocShippingCDL.IT, versions 21.0.2 and 20.0.5
