### ISSUE TITLE
CFG: (1) Expand copy function, (2) Setting option for copy function for configured article (WI 10948)

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#168]
**Is your feature request related to a problem? Please describe.**
(1) With the function "Copy Item" in the menu under "Actions - Configurator" on the item card, not all selection points of the Business Central standard function "Copy item" are available.

The following choices are not available:
- Translations
- Text modules
- dimensions
- Remarks
- ... (see Excel spreadsheet)

(2) Likewise for the configured articles. If a new article is generated from a "Template article", not all information from the "Template article" is copied to the new article. Unfortunately, there is currently no facility for this.

**Describe the solution you'd like**
(1) The copy function should be based on the Business Central standard

(2) It should be possible to set up which information from the "Article template" is to be transferred to the new article

**Describe alternatives you've considered**

**Additional context**
[Artikel kopieren.xlsx](https://github.com/EOS-Solutions/IDEAS/files/10312513/Artikel.kopieren.xlsx)

**Comment by MartinSchnurrKUMAVISION** [comment]
Addition to (2)
This also applies to the  **standard item characteristics**

**Comment by Giuliano-Velludo-EOS** [comment]
Released versions 21.0.58 20.0.175.
We'll provide documentation in the next few days.
