### ISSUE TITLE
CFG: Generate text modules with properties and property values

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#169]
**Is your feature request related to a problem? Please describe.**
In the "Rules" the "Item" description (100 characters) and description (50 characters) 2 can be generated from properties and property values.

Unfortunately, this description is often not sufficient, so that a "long text (text module)" is required.

**Describe the solution you'd like**
Creation of a function, which makes it possible to create text modules with properties and property values as well as free text in the newly created article (not with variants) incl. translations.

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreaDiCeglie** [comment]
Adding longer text to Item master data would produce expectation of printing and copying this text to Sales documents.
We suggest to print directly the properties in documents instead of a longer text. An app (adv document reporting for prod configuratore) is already available for that.
