### ISSUE TITLE
Packing List: use specific serial number

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#170]
Al momento i documenti di packing list vengono generati usando un numero di serie legato al documento a cui sono associati.

La mia proposta è di gestire le packing list con un numero di serie dedicato in modo da poter identificare in modo più semplice il documento.
Il collegamento con i documenti di spedizione potrebbe avvenire tramite una tabella di relazione.

Questa opportunità renderebbe molto più semplice gestire la packing list soprattutto quando questa deve essere stampata prima della registrazione della spedizione perché in queste due fasi assume, ora, numeri differenti.

**Comment by AndreaDiCeglie** [comment]
Pensiamo di aver compreso l'esigenza, purtroppo al momento dato il design delle entità utilizzate per la stampa packing list non è possibile assegnare questo nuovo numero ad una "testata packing" in modo che tutti gli scenari siano opportunamente coperti.

E' possibile farlo custom in base al fatto che presso un cliente si supportino pochi scenari ben definiti
