### ISSUE TITLE
CFG: Rule test directly from the "Rules" page

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#171]
**Is your feature request related to a problem? Please describe.**
To test a newly created or changed rule, it is always necessary to switch from the "Rules" page to an item or a sales order.

**Describe the solution you'd like**
It should be possible to start the configuration directly from the "Rules" page, but WITHOUT creating a new item or item variant.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/90207505/212091129-6b3f8f3d-a7b1-4a7c-b2c9-67c3267ca385.png)

**Comment by Giuliano-Velludo-EOS** [comment]
Sorry @MartinSchnurrKUMAVISION  but by design the configurator cannot work without an item code. We could use a dummy item defined in a setup but routing ? production BOM ?. I don't like this feature.
