### ISSUE TITLE
CDF - Custom List Value Translation (WI 14937)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#172]
Hi,

As far as I understood it is not possible to use the CDL Gen. Translation Table for translation because it seems to allow only the usage for tables with a not-combined primary key. Therefor I ask you to add the possibility into CDF.

![image](https://user-images.githubusercontent.com/107125213/212294914-3537e564-9bf1-4337-aab2-6bce42fab742.png)

Thank you :)
Jakob

**Comment by AndreaDiCeglie** [comment]
Hi, The request is not clear.
 Please describe the basic need and not the possible implementation.
Custom Defined Fields app does not have any dependency to CDL.

**Comment by jellemundeos** [comment]
Hi,

I would like to insert translations for the values of a custom list.
