### ISSUE TITLE
Add to released production orders the finished status 

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#173]
Una cosa che ci chiedono in tanti è la possibilità di filtrare gli ordini di produzione rilasciati a seconda dello stato di avanzamento delle relative righe.
Nello specifico, lo stato nella testata dell'ordine di produzione deve essere:
- Completato, quando la somma delle quantità residue delle righe è zero;
- In progress, quando sia la somma delle quantità finite che quelle di quelleresidue è maggiore di zero.
Il campo potrebbe essere collegato alla App MPL ed essere un ulteriore elemento di filtro da inserire nella Pianificazione Sequenziale.

**Comment by AndreaDiCeglie** [comment]
L'enum standard non è opportuno modificarlo, potrebbe essere forse gestito con un campo aggiuntivo.

Ad ogni modo significa ricalcolare il nuovo "stato" ad ogni modifica di ogni singola riga ed eseguire quindi una modify sulla testata OdP.

Questa richiesta sarebbe da girare a Microsoft Ideas https://experience.dynamics.com/ideas/

**Comment by Giuliano-Velludo-EOS** [comment]
Ne abbiamo parlato con il competence circle e la richiesta viene ritenuta onerosa poi in termini di performance.
Si potrebbe immaginare di inserire due flowfield uno con la quantità residua e uno con la quantità finita da usare poi a piacimento nei custom o per filtrare.

**Comment by MatCive** [comment]
Da un cliente abbiamo implementato la soluzione con il flowfield e la troviamo molto comoda e funzionale:

![image](https://user-images.githubusercontent.com/72971467/214242188-08f63f2c-766f-421e-bbae-505d70b06c51.png)

Abbiamo aggiunto le stesse informazioni anche nella Pianificazione Sequenziale:

![image](https://user-images.githubusercontent.com/72971467/214242430-eb3662d6-bf2f-4a92-94ce-34cdfe82211a.png)

Abbiamo, inoltre, implementato anche lo "Stato materiale per magazzino" che non guarda alla disponibilità bensì alla sola giacenza, nel caso in cui lo reputaste interessante.
