### ISSUE TITLE
ECS: filtro spedizioni (CWS)

### ISSUE THREAD

**Issue by Dario-Zaniboni-EOS** [EOS-Solutions/IDEAS#174]
In un ambiente BC che prevede l'utilizzo delle spedizioni CWS, il report "Fatt. Cumulative Estese (ECS)" propone comunque tra i filtri in request page quello per "Nr.", relativo alle testate spedizioni standard.
Per aiutare i clienti a non fare confusione, andrebbe esposto tra i ReqFilterFields il campo "Nr. spedizione CWS" e nascosto il "Nr.".

![image](https://user-images.githubusercontent.com/106167410/212963296-364d635f-fdd5-4cd7-8909-d50aab67490b.png)

**Comment by AndreaDiCeglie** [comment]
Removing Nr. Is not possible

Adding CWS Nr. probably requires a new bridge app

Since it's already possible to filter using this fields the benefit/expense ratio is not valuable for this implementation
