### ISSUE TITLE
CWS: classe documento nei criterio raggruppamento (WI 11331)

### ISSUE THREAD

**Issue by Dario-Zaniboni-EOS** [EOS-Solutions/IDEAS#175]
Spesso i clienti richiedono di poter spezzare le spedizioni CWS per classe documento di vendita (CDL).

Sarebbe utile trovare di default il campo **Codice classe documento** all'interno della lista "Selezione campi criterio raggruppamento" (EOS CWS Comb. Criteria Editor (70491957, Worksheet)).

**Comment by f0ffee** [comment]
Deployed: CWS 21.0.23
