### ISSUE TITLE
CWS: gestione trasferimenti diretti registrati (WI 11258)

### ISSUE THREAD

**Issue by Dario-Zaniboni-EOS** [EOS-Solutions/IDEAS#176]
Al momento l’app CWS non prevede la gestione dei documenti **Trasferimento diretto registrato**.

Dunque, se all’interno del setup magazzino un cliente attiva l’opzione _Registrazione trasferimento diretto = Trasferimento diretto_, non vedrà comparire alcuna spedizioni CWS al momento della registrazione di un ordine di trasferimento diretto.

![image](https://user-images.githubusercontent.com/106167410/213483630-506cb7d7-ce06-4fcd-8811-206b69dc0511.png)

Se volete fare delle prove, trovate il setup compilato in ambiente INTEGRATION - DEL VE TEAM1: fate un nuovo ordine di trasferimento, con opzione “diretto”, da MAG1 a MAG2 per l’articolo 1000 (1 PZ).

Resto a disposizione per qualsiasi necessità.

**Comment by Giuliano-Velludo-EOS** [comment]
Dopo aver analizzato il codice della nuova funzionalità sviluppata da Microsoft abbiamo deciso almeno per il momento di non supportarla. Se pur comoda è al momento a ns. avviso ancora in sviluppo. Abbiamo anche aperto un ticket a Microsoft per la sistemazione di un bug standard nella gestione. Al momento abbiamo aggiunto un messaggio di errore nel caso in cui in presenza della cws venga attivata la gestione. Nei prossimi giorni verifichiamo l'eventuale compatibilità con il le HUM.

**Comment by f0ffee** [comment]
Microsoft ha dichiarato che i fix necessari arriveranno con BC23 (2023 wave 2) e non è ancora chiaro se saranno backportati alle versioni supportate precedenti (BC22 e BC21).
