### ISSUE TITLE
App CFG : Gestire data inizio e fine validità su caratteristiche per regola e valori caratteristiche per regola 

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#177]
Le date di inizio e fine validità sono da aggiungere alla tabella delle caratteristiche per regola e valori caratteristiche per regola 
Per la configurazione da documento la data di riferimento è la data documento per la configurazione da articolo sarà la workdate 
In fase di configurazione le caratteristiche o i valori caratteristica non devono essere visibili alla data. 
Il caso d'uso principale è la messa in opera di aggiornamenti di prodotto. (come per esempio una diba)

**Comment by AndreaDiCeglie** [comment]
under technical evaluation, this should change the user experience on lookup pages, and this is a unwanted behaviour.

**Comment by Giuliano-Velludo-EOS** [comment]
Da fare come custom (passate le indicazioni a Massimiliano Pergher)
