### ISSUE TITLE
ECS Extended combined shipment - Group by Order No. (WI 11377)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#178]
Hi,

a customer would like to group the invoices by order which could be a criteria to integrate into standard.
According to the documentation on help the field is used to group by DDT and not for orders.

![image](https://user-images.githubusercontent.com/107125213/217749572-cc044ba2-860f-45a5-a296-d34f22803b95.png)

Thank you

**Comment by Luca-Maritano-EOS** [comment]
Modifica rilasciata sulle seguenti versioni:
BC23 23.0.36.0
BC24 24.0.27.0
BC25 25.0.22.0
