### ISSUE TITLE
ETC - Costo trasporto fisso in listino (WI 11374)

### ISSUE THREAD

**Issue by nudoor** [EOS-Solutions/IDEAS#179]
Per un cliente è nata la necessità di gestire un costo fisso per riga di listino nei costi di trasporto.
Sarebbe utile poter avere un campo aggiuntivo per gestire un costo fisso invece del solo prezzo unitario.
In questo caso abbiamo implementato una custom per gestire il comportamento, ma potrebbe essere utile se venisse gestito dall'app standard.

![2023-02-09_14h10_18](https://user-images.githubusercontent.com/12609800/217833852-d8733020-ac68-4e58-9f89-1ea8e3b71627.png)

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao la funzionalità richiesta è già coperta dallo standard dell'App. Inserendo le righe degli scaglioni con il solo importo minimo ottieni il funzionamento richiesto.
