### ISSUE TITLE
Aggiungere campo Albo Autotrasportatori sull'anagrafica Shipping Agent (WI 11371)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#180]
Ciao,

siccome tutti gli spedizionieri devono essere iscritti nel albo autotrasporto vi chiedo di prevedere il campo sulla tabella shipping agent.

Saluti e grazie

**Comment by AndreaDiCeglie** [comment]
un text 50 è ok ?

**Comment by jellemundeos** [comment]
Sì

**Comment by Giuliano-Velludo-EOS** [comment]
rilasciate le seguenti versioni della EX066 CDL 21.0.1220.0.81
