### ISSUE TITLE
ETO: Numerazione Struttura Commessa (WI 15814)

### ISSUE THREAD

**Issue by fbruno72** [EOS-Solutions/IDEAS#185]
Utilizzando Engineering, quasi mai i clienti accettano che le strutture commesse vengano create usando un numeratore da Nr. Serie come fa lo standard.
Sarebbe utile, attivabile tramite setup, riportare a standard lo sviluppo fatto in Sarong dove le strutture commesse vengono create come "Nr. Commessa"-01, "Nr. Commessa"-02, etc...
Altre implementazioni poi saranno custom per i singoli progetti.

**Comment by MatCive** [comment]
Nel https://github.com/EOS-Solutions/IDEAS/issues/274 abbiamo inserito anche la gestione del numero di serie così come riportato in questa Issue.

**Comment by Roberto-Lucarelli-EOS** [comment]
Sviluppo rilasciato con la issue #274 

Le modifiche sono contenute nelle seguenti versioni :
EX090 MODUS M365 Job Structure 23.0.23.0
EX090 MODUS M365 Job Structure 24.0.23.0
EX090.04 Engineering to order 23.0.29.0
EX090.04 Engineering to order 24.0.22.0
