### ISSUE TITLE
CMS - Prospetto di liquidazione

### ISSUE THREAD

**Issue by IlariaEos** [EOS-Solutions/IDEAS#186]
Ciao,
nella stampa dei prospetti di liquidazione, molti clienti chiedono l'aggiunta del campo % incassata.
Sarebbe utile se si potesse aggiungere allo standard CMS, grazie.

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao Ilaria, ho condiviso la richiesta con il CC. 
Non appena avremo novità ti aggiornerò.
Ciao Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao Ilaria,
come da indicazioni del CC purtroppo per limiti di spazio non è possibile aggiungere la colonna richiesta, le info e le colonne attualmente presenti nel report sono tutti fondamentali e di importanza maggiore rispetto all’informazione della % di incassato.
