### ISSUE TITLE
CWS- metodo di fatturazione cliente in criteri raggruppamento fatturazione 

### ISSUE THREAD

**Issue by barbaracigarini** [EOS-Solutions/IDEAS#187]
Aggiungere tra i i criteri di raggruppamento fatturazione CWS una caratteristica della scheda cliente che consente di impostare il criterio per gruppi di appartenenza, senza dovere inserire una riga per ciascun cliente.
Serve, ad esempio, nel caso di fattura accompagnatoria per tutti i clienti esteri. 
il campo di raggruppamento potrebbe essere il codice metodo di fatturazione impostato in scheda cliente

**Comment by AndreaDiCeglie** [comment]
After internal analisys we defined to not go on with this change
