### ISSUE TITLE
PCK e HUM: assegnazione articoli per riga ODV

### ISSUE THREAD

**Issue by stefanocastellani** [EOS-Solutions/IDEAS#189]
Se una spedizione warehouse contiene due righe dello stesso articolo, ma di ordini di vendita diversi, la compilazione manuale della packing list non considera l'ordine come discriminante.
Esempio:
- ODV 1, riga 1, articolo A: qtà ordine 100 pz
- ODV 2, riga 1, articolo A: qtà ordine 100 pz
Creo spedizione warehouse con queste 2 righe.
Creo il primo pallet e aggiungo all'interno 10 pz del primo ordine.
Creo il secondo pallet e aggiungo all'interno 10 pz del secondo ordine.
L'app assegna erroneamente 20 pz nella quantità da spedire della prima riga del primo ordine, lasciando a 0 l'altra.
Addirittura se volessi mettere entrambe le quantità nello stesso pallet, non si visualizzerebbe neanche la discriminazione dell'ordine.

Modificando manualmente le qtà da spedire nella spedizione warehouse, mettendo 10 pz su ciascuna riga, alla registrazione viene restituito errore perchè si aspetta di spedire 20 pz nella prima riga.
![image](https://user-images.githubusercontent.com/109364589/221530599-f5b4e03d-419b-48d5-ab89-4a83761c63de.png)

È possibile introdurre una gestione per riga documento nella compilazione della Packing list/HUM?

**Comment by AndreaDiCeglie** [comment]
Please refer to https://github.com/EOS-Solutions/IDEAS/issues/196

**Comment by Giuliano-Velludo-EOS** [comment]
Modifica rilasciata
