### ISSUE TITLE
Job queue entry errors warning email

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#19]
When a job queue entry is stuck due to an error, users are not immediately aware of that.
This is due to the lack of an email that warns when something didn't work.

I'd like a simple task that sends emails to specific users in some cases, e.g. when a queue is in error or is still running after some time. This could even be used to send a message in case of positive result.
This could be done by adding:
- An option "Warning cause" field in the "Job Queue Entry (472)" table to select one or more types of warning you want (Error, Running Time, Success, ...)
- A "Max Running Time" field
- A dedicated table that relates both the job queues and the User Setup (or Contacts) and that is linked to the Job Queue card
- A Codeunit that has to be called when the status of the Job Queue changes

**Comment by AndreaDiCeglie** [comment]
Matteo, vote here: 
https://experience.dynamics.com/ideas/idea/?ideaid=ca4830a7-af1a-ea11-b265-0003ff68f605

**Comment by AndreaDiCeglie** [comment]
"Anzi" is already planned with 144 Votes. This issue will closed with no implementation

https://experience.dynamics.com/ideas/idea/?ideaid=90b987bb-0920-ea11-b265-0003ff68bbbc
