### ISSUE TITLE
ADR: gestione allegati

### ISSUE THREAD

**Issue by Gian01111** [EOS-Solutions/IDEAS#191]
Buongiorno,

vorrei chiedere delle implementazioni riguardanti l'invio dell'e-mail usando l'applicazione ADR, questa implementazione permetterebbe di inserire nuovi allegati all'e-mail, una possibile integrazione potrebbe considerare la possibilità di inserire i seguenti documenti:

•	I documenti allegati nella Factbox;
•	Un documento da inserire a setup che venga proposto ad ogni e-mail;
•	Allegati collegati con docsolution.

Saluti

**Comment by AndreaDiCeglie** [comment]
Buongiorno, la issue è già aperta e approvata su IDEAS 

https://github.com/EOS-Solutions/IDEAS/issues/2 

per eventuali integrazioni potete scrivere in quella
