### ISSUE TITLE
ECS - Cod. Spedizioniere (WI 12617)

### ISSUE THREAD

**Issue by MarkusMoserEOS** [EOS-Solutions/IDEAS#193]
Ciao, 
sarebbe utile che si potesse mettere il campo Cod. Spedizioniere nel Setup / campi metodo fatturazione in modo che si possa accorpare le fatture in base al cod. spedizioniere (Sales Header Shipping Agent Code (105))
 
 
![image](https://user-images.githubusercontent.com/101793608/224715864-68cab548-eda2-4ee8-83eb-1b115df4e5a4.png)

![image](https://user-images.githubusercontent.com/101793608/224715849-fe736f39-6e6e-4b6f-a2cc-58a9e5f63a69.png)

Ciao
Markus

**Comment by Nyryus** [comment]
Released in versions:
23.0.22.0
22.0.10.0
21.0.8.0
