### ISSUE TITLE
CMS: Filtro su cliente + articolo con un filtro BLOB (WI 12612)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#195]
Ciao,

per filtrare su nr. articoli ci sono solo 50 caratteri. 

![image](https://user-images.githubusercontent.com/107125213/226309958-94723c08-eb9e-4ed4-8216-7cf06ac34e5f.png)

Sarebbe comodo avere un filtro come è stato fatto nel SPB dove si può anche su altri campi: 

![image](https://user-images.githubusercontent.com/107125213/226309874-f40b41ff-e98b-44a3-8aa5-773b3ea90572.png)

Saluti

**Comment by AndreaDiCeglie** [comment]
Item filter field will be enlarged. 
Dynamic filter on fields will not be implemented
