### ISSUE TITLE
HUM: Considerare la quantità assegnata nella packing list come assegnazione

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#196]
Ciao,

quando si crea una nuova HUM per una spedizione warehouse con più righe dello stesso articolo e l'utente decide si assegnare le quantità alla chiusura dell'assegnazione non viene considerato quello inserito manualmente.

![image](https://user-images.githubusercontent.com/107125213/226568609-5835528d-b408-4437-b4e3-41017cb261f5.png)

Invece nella tabella dove viene assegnato il contenunto al documento di origine viene creato un singolo record contenendo tutti il contenuto. In più l'intera quantità è assegnato ad una riga sola.

![image](https://user-images.githubusercontent.com/107125213/226569133-a1a0f7d7-aee2-4b07-9324-59c77d829099.png)

Alla registrazione della spedizione arriva di seguito un errore, perchè la quantitá che si vuole spedire non corrisponde a quella assegnata per riga.

![image](https://user-images.githubusercontent.com/107125213/226570334-8d406e94-1cc9-4c72-a098-4ed5bf319177.png)

**Comment by AndreaDiCeglie** [comment]
It's a long term implementation and will be evaluated within competence circle and with the original designers of the app
