### ISSUE TITLE
FTE - Non esportare righe con quantità = 0 in XML fatture vendita (WI 12130)

### ISSUE THREAD

**Issue by AgnoEOS** [EOS-Solutions/IDEAS#197]
Un cliente ha chiesto se sia possibile non estrarre le righe con tipo <>'' e Quantità = 0 nell' XML della fattura vendita.

La richiesta nasce da alcune contestazioni clienti sul disallineamento tra la fattura di cortesia (che non esporta le righe tipo <>'' e  quantità = 0 ) che potrebbe inficiare le documentazioni a corredo di bandi di finanziamento pubblici.

**Comment by AndreaDiCeglie** [comment]
A new checkbox on setup will enable skipping zero quantity export in FTE.
- On New installation (if Outbound setup record not exists) this check is set to TRUE
- On Existing installation/upgrades  (if Outbound setup record exists) this check is not modified

**Comment by f0ffee** [comment]
Will be released in FTE versions 20.0.187, 21.0.67, 22.0.15

Please remember to enable the new flag "Skip Zero Quantity Lines" in the FTE outbound setup.
