### ISSUE TITLE
CFG - Product Configurator translations

### ISSUE THREAD

**Issue by nmoreggio** [EOS-Solutions/IDEAS#198]
**Is your feature request related to a problem? Please describe.**
Nel rapportarsi con i clienti esteri, è richiesto, alla configurazione di un articolo, che venga generata la descrizione dell'articolo e le sue traduzioni nelle lingue utilizzate verso i clienti, utilizzando quanto già previsto nella composizione della descrizione "standard" dell'articolo.

**Describe the solution you'd like**
Implementare una tabella correlata alle _Regole caratteristica_ denominata "Traduzioni descrizioni articolo", avente in chiave Regola e Cod. lingua e come campi Utilizza descrizione articolo, Descrizione e Descrizione 2.
Quando un articolo viene configurato, la funzione di creazione descrizione deve verificare anche i record presenti nella nuova tabella Traduzioni descrizioni articolo e, per ciascun codice lingua, creare un nuovo record nella tabella Traduzioni dell'articolo creato, compilando Descrizione e Descrizione 2 secondo la funzione già presente, con l'unica differenza che, in caso di _Descrizione valore caratteristica_ (parentesi graffe), comporrà la descrizione con quanto presente nella traduzione del valore caratteristica (tabella EOS028 CFG Charac. Translation).

**Describe alternatives you've considered**
No alternatives.

**Additional context**
Al momento non ho la necessità di gestire le varianti, ma immagino si possa applicare la stessa regola.

**Comment by AndreaDiCeglie** [comment]
we have evaluated the request and it's of of scope from the most common scenarios. Events and function are available for development as a custom extension
