### ISSUE TITLE
Data Security: Evento per suggerire il campo DS Field No.

### ISSUE THREAD

**Issue by LorenLoxly** [EOS-Solutions/IDEAS#201]
Quella che vado a proporre è un'idea relativa alla gestione dei setup per implementazioni del Data Security su entità non gestite nativamente

Quando si attiva il Data Security su una entità che non è stata gestita, alla fine dello sviluppo il funzionale che imposta la tabella deve andare a compilare il campo DS Field No. nella tabella EOS DS Tables Setup. Tale campo è nascosto.

La soluzione che propongo è di integrare nell'app un evento SuggestDsFieldNo con parametro il record corrente e se l'app che si sottoscrive identifica il proprio caso può a livello di codice indicare il campo che è stato implementato come custom.

**Comment by AndreaDiCeglie** [comment]
E' possibile impostare il campo (CHE NON E' OBBLIGATORIO) sottoscrivendosi OnAfterVLD di uno dei campi di EDS table Setup o all OnModify. non è necessario un ulteriore evento.
