### ISSUE TITLE
Crea carico whse. - Crea spedizione warehouse

### ISSUE THREAD

**Issue by stefanocorradinidoit** [EOS-Solutions/IDEAS#202]
In fase di creazione carico whse. su ordini di acquisto e/o ordini di reso vendita ed in fase di creazione spedizione warehouse da ordini di vendita e/o ordini reso acquisto bisognerebbe che venissero compilati i campi Tipo destinazione documento e nr. destinazione documento nei rispettivi documenti Carico warehouse e spedizione warehouse

**Comment by Giuliano-Velludo-EOS** [comment]
rilasciate le seguenti versioni della EX006 CWS:
22.0.11
21.0.34
