### ISSUE TITLE
Integrazione tra LS Central e app Dual Unit of Measure

### ISSUE THREAD

**Issue by Giovanni-Marigonda-EOS** [EOS-Solutions/IDEAS#203]
Ciao,

avrei la necessità di integrare l'app DUM con l'app LS Central. 
Nello specifico, LS Central prevede delle pagine e tabelle aggiuntive rispetto allo standard per la gestione delle ricezioni e delle spedizioni da parte dei negozi. La necessità  che queste tabelle e pagine aggiuntive vengano integrate con la gestione dei campi previsti nelle pagine e tabelle standard dall'app DUM.
![image](https://user-images.githubusercontent.com/130978091/232446409-54a6f6b6-9805-4c1d-aac2-00be91f30fa8.png)

Grazie,

Giovanni

**Comment by AndreaDiCeglie** [comment]
Not necessary a standard implementation
