### ISSUE TITLE
CWS - Utility Carico warehouse (WI 15817, 15820)

### ISSUE THREAD

**Issue by nudoor** [EOS-Solutions/IDEAS#204]
Per un cliente ci siamo trovati a gestire 2 implementazioni relativi ai carichi Warehouse, che potrebbero essere utili e implementate come funzioni standard dell'app CWS.

1. Per facilitare la gestione del carico Warehouse abbiamo aggiunto nel setup CWS un flag che pilota la cancellazione del carico dopo la registrazione parziale dello stesso.
![delete](https://user-images.githubusercontent.com/12609800/232452894-fc24f74b-b68a-465b-9931-e63dc96abe5a.png)

2. Al fine di facilitare la gestione dei carichi warehouse abbiamo introdotto la possibilità di modificare la quantità da ricevere   direttamente dal prendi righe carico, così da non dover modificare le righe una volta inserite nel carico. 
Questo facilità l’utente nel caso in cui abbia molte righe nei DDT fornitori, e peremette di velocizzare le operazioni
La qta da ricevere viene popolata con la qtà inevasa della riga
![QtyToRec](https://user-images.githubusercontent.com/12609800/232453535-1a19fb3c-be7d-462c-809e-e03091ff9865.png)

**Comment by AndreaDiCeglie** [comment]
It's ok for proposal 1 and 2, (the only open question is related to the identity of the author and the way to get the current customization)

**Comment by nudoor** [comment]
What do you need Andrea?

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao Micheal i sorgenti ci servono !

**Comment by nudoor** [comment]
Ciao Giuliano,

gli ho recuperati, te li allego
[CWS - Utility Carico warehouse.txt](https://github.com/EOS-Solutions/IDEAS/files/13380857/CWS.-.Utility.Carico.warehouse.txt)

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX006 Combine Warehouse Shipment:
24.0.31
25.0.16 Saas
