### ISSUE TITLE
EDS Order for Status (WI 12790)

### ISSUE THREAD

**Issue by MarcusFabian** [EOS-Solutions/IDEAS#206]
Table EOS DS Table Status (18122142)
I'd like to see a sort order of the status (aka new "Order" field).
The idea is that the user could simply start a function "Next Status" in order to move to the next higher status rather than manually selecting status change from the factbox.

We achieved that in the current solution by prefixing our status with numerical values. Such as 01-NEW, 02-PROGRES, 05-APPROVED but giving an order to "find the next higher status" would be a plus. 

You might use the following code snipped as a start:

```
local procedure StatusUP()
    var
        EDSStatusTrans: Record "EOS DS Status Transaction";
        EDSMgt: Codeunit "EOS DS Management";
        rRef: RecordRef;
        fRef: FieldRef;

    begin
        rRef.Open(Rec."Table ID");
        if not rRef.GetBySystemId(Rec."Table Rec. SystemId") then
            EDSMgt.GetCurrentRecordRef(Rec, rRef);
        EDSStatusTrans.SetRange("Table ID", Rec."Table ID");
          fRef := rRef.Field(1);
          EDSStatusTrans.SetRange("Table Option Type", fRef.Value);
        EDSStatusTrans.SetRange("From Status", Rec."Status Code");
        EDSStatusTrans.SetFilter("To Status", '>%1', Rec."Status Code");  // replace here with new order-value
        if EDSStatusTrans.FindFirst() then begin
            if EDSStatusTrans."To Status" <> Rec."Status Code" then begin
                EDSMgt.ChangeDirectStatus(rRef, Rec."Status Code", EDSStatusTrans."To Status", '');
            end;
        end;
    end;

````

**Comment by AndreaDiCeglie** [comment]
We are evaluating a different implementation

![image](https://user-images.githubusercontent.com/33353905/234587135-f05e0839-42d2-4dbd-a56f-ab4b4c67b357.png)
![image](https://user-images.githubusercontent.com/33353905/234587203-4964ebde-1d29-462f-8ba4-6d5c66c365e6.png)
