### ISSUE TITLE
Generazione autofatt. omaggi (SFG) (WI 12231)

### ISSUE THREAD

**Issue by IlariaEos** [EOS-Solutions/IDEAS#207]
Ciao,

in merito alla creazione della autofattura con il report dell'APP SFG, propongo di gestire i filtri non solo per le date di registrazione (già presente) ma anche per le date di esecuzione operazione dei documenti.

Grazie, ciao

**Comment by Edoardo-Rossi-EOS** [comment]
E' stata aggiunta la possibilita' di filtrare per la data di esecuzione operazione dei documenti, disponibile da BC24 in poi
