### ISSUE TITLE
EX036 - Certificazione Unica Agenzia delle Entrate - Integrazione campi “Tipo di reddito non imponibile” su Fatture e Pagamenti

### ISSUE THREAD

**Issue by ragusale** [EOS-Solutions/IDEAS#21]
La parte relativa al “Tipo di reddito non imponibile” aggiunta sulle Ritenute sarebbe molto utile averla anche sull’inserimento delle  fatture e successivamente dei pagamenti in modo tale che questa informazione arrivi già popolata nelle ritenute.
 In questo modo l’informazione verrebbe popolata già all’inserimento della fattura, si propagherebbe sul pagamento e di conseguenza sulla ritenuta.

**Comment by BarbaraEOS** [comment]
Nel momento in cui viene creata la fattura, non è detto che l’utente abbia effettivamente l’informazione precisa da inserire. 
Consideriamo che ogni anno l’AdE rivede le informazioni relative al tipo di reddito a gennaio dell’anno successivo, quindi quando le fatture sono già state tutte registrate. 
Questo fa sì che l'utente compili i dati con la normativa del 2020, ma poi a gennaio 2021 dovrebbe rivederle tutte perché la normativa è variata (vedi quest’anno con l’aggiunta del 12 e 13).
