### ISSUE TITLE
Gestione Conto Lavoro attivo

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#210]
Gestione più standardizzata del conto lavoro attivo (versione trasferimenti e versione compravendita)

Al momento non esiste (che io sappia) una gestione vera per il conto lavoro attivo, c'è chi fà utilizzare:
- il giro dell'acquisto (con ordini acquisti a 0 in caso di trasferimento)
- il giro della vendita (tramite ordini di reso vendita, ma cosa sto rendendo? fiscalmente non credo sia correttissimo)

La gestione non è molto chiara né "pulita", perchè non si ha comunque modo di capire quale siano gli ordini creati per la gestione del conto lavoro attivo e quali no.

L idea sarebbe di creare questo documento che sta prima di tutti da cui poi fai partire (se compravendita fa oda e odv portandosi dietro i riferimenti, altrimenti se trasferimento fa odt?)

**Comment by AndreaDiCeglie** [comment]
Ciao, 
Si tratta in sostanza della proposta di realizzare una nuova app. Consiglio di portare la questione al competence circle poichè si tratta di un implementazione consistente.
P.S. Verificate  su appsource l'eventuale esistenza di soluzioni di mercato
