### ISSUE TITLE
Ereditare campo commessa in IPL da ordine di vendita 

### ISSUE THREAD

**Issue by MauroEOS** [EOS-Solutions/IDEAS#211]
Attualmente il campo commessa presente in testata e righe degli ordini di vendita non viene ereditato in testata e righe del piano di fatturazione generato con l'app IPL.
Potrebbe essere utile implementare un' integrazione.

**Comment by AndreaDiCeglie** [comment]
Inizialmente il campo era trasferito. Circa 3 anni fa l'assegnazione è stata esplicitamente rimossa
        // IPLInvoicePlanHeader.Validate("Job No.", SalesHeaderR."Job No.");

un evento è disponibile per implementarlo come custom

        IPLEventsPublisher.OnCopyFieldsFromSalesHeaderToInvoicePlan(SalesHeader, IPLInvoicePlanHeader);

Per la RE-implementazione standard chiediamo una valutazione del competence circle
