### ISSUE TITLE
Advanced Document Reporting: save more document in one single PDF file

### ISSUE THREAD

**Issue by Daniele-Corona-EOS** [EOS-Solutions/IDEAS#212]
Expand and integrate a new feature for "Save" action:
save more documents in a single PDF document.
Option to turn the feature on and off
Feature valid for both On Premise and Saas environments

**Comment by AndreaDiCeglie** [comment]
This feature is available for OnPremise installation, for Saas a consuming-paid resource is needed. 
EOS will not release this as standard Feature for Saas.
