### ISSUE TITLE
Gestione allegati PDF PowerApp Nota Spse

### ISSUE THREAD

**Issue by Lbaratin** [EOS-Solutions/IDEAS#215]
Ciao,
vi richiedo se possibile di poter gestire nella PowerApp degli "scontrini" anche gli allegati PDF.
Questo per poter venire incontro alla nuova gestione dell'allegato del Telepass, che posso creare come allegato PDF dalla relativa app Telepass ma che poi non riesco ad inserire tramite PowerApp.

Grazie

**Comment by AndreaDiCeglie** [comment]
This site is for App enhancement not for logging internal request. Internal request must be forwarded to the team responsible person
