### ISSUE TITLE
Compilazione automatica del template "ratei e risconti" nei documenti (WI 12749)

### ISSUE THREAD

**Issue by AG1GA** [EOS-Solutions/IDEAS#217]
Nelle fatture, nelle note di credito e nelle registrazioni di prima nota implementare il suggerimento automatico del template "ratei e risconti". Per esempio, nella testata della pagina ci potrebbe essere un pulsante che aprirebbe un batch che permetterebbe selezionare il template "ratei e risconti", la data iniziale e la data finale di competenza, il tipo di riga (nelle fatture e nelle note di credito) e cliccando su "ok" sarebbe inserito in tutte le righe filtrate con il tipo riga, per esempio, "articolo", "conto c/g", "risorsa". Aiuterebbe tanto ai clienti che creano le fatture con tante righe con le competenze dei ratei e risconti.

**Comment by MarkusMoserEOS** [comment]
Ciao, ho anche clienti dove sarebbe molto utile una funzione del genere.

**Comment by AndreaDiCeglie** [comment]
After few analisys this is our outcome:
- Will be implemented in journal as extension of the function that propose value from the line above
- Will not be implemented on Documents (Order, Invoice, etc)
