### ISSUE TITLE
[ADR] E-mail - Change the text before sending the email

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#219]
Today if I want to add a phrase to an email that I will send once, I need to create a new "E-Mail Texts". 

Import to the e-mail that I am writing the template of the "e-mail Texts" (with placeholders solved?), and be able to view the preview of the text, and add changes before sending it.

**Comment by AndreaDiCeglie** [comment]
Need detailed analisys

**Comment by Delpixe** [comment]
I would like to be able to view the preview of the text I am sending and add changes to It (without having the need to create another "e-mail text")

**Comment by AndreaDiCeglie** [comment]
After internal code analisys we decided to decline the request due to high technical complexity and possible side effects
