### ISSUE TITLE
Modula Interface

### ISSUE THREAD

**Issue by S-bruni** [EOS-Solutions/IDEAS#22]
Create a new app to interface Automated Storage by Modula and Business Central.
Main Features required:

- Picking and Put-away (Pick. Orders or Reclass. Journal, based on the setup)
- Physical Inventory
- Inventory Adjustments
- Share Master Data
- Others..

**Comment by AndreaDiCeglie** [comment]
La proposta è stata presentata al comitato che valuta mensilmente i nuovi prodotti. L'output è che è un tipo di soluzione da implementarsi come customizzazione e solo al ripetersi di un alto numero di integrazioni può essere rivalutata per essere implementata come soluzione standard.
