### ISSUE TITLE
Spedizioni vendita/trasferimento registrate - ricezioni acquito/trasferimento registrate - solo righe con quantità

### ISSUE THREAD

**Issue by stefanocorradinidoit** [EOS-Solutions/IDEAS#220]
Per i clienti con ordini molto lunghi i documenti spedizione vendita e ricezioni di acquisto diventano pesanti in quanto riportano sempre tutte le righe ordine ed il processo di posting è rallentato. Bisognerebbe avere un setup che una volta attivato scriva solo le righe che hanno una quantità. Questa opzione dovrebbe funzionare sia con CWS che senza.

**Comment by AndreaDiCeglie** [comment]
In past NAV version this was easy to implement and maintain changing few code lines. 
As of today extending the standard and not changing is limiting this implementation. 
The only way to achieve it is removing the lines at the end of the process but this is going to increase performance degradation.
