### ISSUE TITLE
ECS Extended combined shipment - Group by Your Reference No + External Document No.

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#221]
Hi,

a customer would like to group the invoices by external document no + your reference which could be a criteria to integrate into standard.

Thanks

**Comment by AndreaDiCeglie** [comment]
Adding custom grouping field is already possible as shared below. Adding new fields can be breaking for existing customer that already added fields as custom extension.

https://github.com/EOS-Solutions/Sample/blob/master/EX050.CombineShipment/Codeunit%2050001%20EOS%20ECS%20Event%20Subscriber.al
