### ISSUE TITLE
EDS - Default Status

### ISSUE THREAD

**Issue by enricozandoli** [EOS-Solutions/IDEAS#222]
Stiamo riportando in diversi progetti il seguente custom. Chiedo la possibilità di valutarlo per inserirlo all'interno dell'app EDS.

E' stato aggiunto un campo "Default Status" all'interno dei cambi stato EDS.

![image](https://github.com/EOS-Solutions/IDEAS/assets/87316626/6bacfdf6-5222-4fb8-bdcb-5a31d85d06d3)

Tale setup permette di proporre automaticamente il valore "New Status" in fase di cambio stato. 

![image](https://github.com/EOS-Solutions/IDEAS/assets/87316626/9f55aca9-5e8c-4af4-b3e2-3edc5530a3c7)

L'utente sarà in grado di impostare uno stato diverso o continuare con il default cliccando OK

Abbiamo notato che l'utente apprezza molto questa facilitazione.

**Comment by AndreaDiCeglie** [comment]
Already reported and accepted as https://github.com/EOS-Solutions/IDEAS/issues/206
