### ISSUE TITLE
EDS - Gestione di un nuovo flag "Rilascio documento manuale disabilitato" sugli stati

### ISSUE THREAD

**Issue by Federico-Perucca-EOS** [EOS-Solutions/IDEAS#223]
**Problema di partenza:**
I cambi stato EDS, se c'è il flag "Rilascio documento disabilitato" spuntato sullo stato di partenza del cambio stato, non permettono di associare la funzione standard EOS di rilascio documento con la sequenza **_prima_**. In altre parole, se essa viene associata, quando viene poi effettuato il cambio stato, viene restituito l'errore che non si hanno le autorizzazioni per effettuare tale cambio stato.
Di seguito trovare delle immagini inerenti ad un esempio del problema, riprodotto sull’EDS degli ordini di acquisto nel vostro ambiente integration (società EX003 EDS):
Sullo stato IN APPROV è stato abilitato il flag “Rilascio documento disabilitato”:
![image](https://github.com/EOS-Solutions/IDEAS/assets/105504926/fecc8bc1-72f6-466a-b774-25cbe1f3aace)

Dal cambio stato IN APPROV a RELEASED è stata associata la funzione di rilascio documento standard EOS:
![image](https://github.com/EOS-Solutions/IDEAS/assets/105504926/a0c0bd06-3a2d-4979-bfd3-1fdafe5e1ea1)
![image](https://github.com/EOS-Solutions/IDEAS/assets/105504926/173628a1-3886-4df8-93de-67e07122f8ab)

Andando poi su un ordine d’acquisto qualsiasi a cambiare lo stato EDS da IN APPROV a RELEASED si è ottenuto il seguente errore:
![image](https://github.com/EOS-Solutions/IDEAS/assets/105504926/202c4870-6e0d-44d0-9352-bdabc0916619)

Lo stesso discorso vale comunque, in modo speculare, anche per lo stato di arrivo del cambio stato e la sequenza **_dopo_** della funzione di rilascio standard EOS.

**Soluzione:**
Alla luce di questo, la soluzione a cui si pensava era quella di implementare una gestione diversificata per le due casistiche di rilascio, ossia una gestione per la casistica di rilascio manuale e una gestione per quella tramite funzione EDS/procedura custom.
E per far ciò, si pensava di aggiungere un flag, chiamato per esempio "Rilascio documento manuale disabilitato", nel setup degli stati EDS, il quale, se attivo, restituisce un errore quando si lancia il rilascio manualmente tramite le action standard dalle pagine dei documenti (solo se chiaramente essi sono nello stato EDS che ha il flag abilitato).
In tutto questo il flag "Rilascio documento disabilitato" continuerebbe invece a funzionare come adesso.
In conclusione, con questa nuova logica, sugli stati dei cambi stato in cui si dovrebbe andare ad associare la funzione di rilascio, il vecchio flag verrebbe disabilitato mentre quello nuovo verrebbe abilitato.
Potrebbe magari anche aver senso, per una questione di specularità, proporre la stessa soluzione sulla funzione di riapri documento.

**Comment by AndreaDiCeglie** [comment]
We cannot hide or change the behavior of standard action in the described way. As an ISV that release standard extensions we must respect the basic behaviour  this may represent a breaking change / break automatic tests or  may provoke incompabiltity with other existing extensions.
This can be done only on the last layer that is the customization/personalization layer
