### ISSUE TITLE
EX059: Fields in ObsoleteState Pending are ignored/emptied (Alredy fixed with existing WI 9362)

### ISSUE THREAD

**Issue by HattrickHorst** [EOS-Solutions/IDEAS#226]
Hey EOS,

This is an issue in your MDI App.

In the Synch. Profile Line, fields that are in ObsoleteState Pending are ignored. However, if they are just in Pending, they can still be in use. Since those fields are not visible in the list of fields in the Synch. Profile Line, they are also not part of the synchronization file, and that's why they are emptied in the target company during synchronization. 

Would it be possible to include those fields in the list of fields? As an alternative, you could also do not touch fields that are not part of the synch. file.

**Comment by AndreaDiCeglie** [comment]
This issue was solved in MAY 22, it is possible that you are using a previous version of the app ?

**Comment by HattrickHorst** [comment]
Ciao Andrea,

Thanks for the reply. Currently we use the BC14 onPrem version. How do I download this fix of May 22?
