### ISSUE TITLE
PQA - Ordini di controllo ogni N pezzi registrati

### ISSUE THREAD

**Issue by GuidiGabriele** [EOS-Solutions/IDEAS#227]
Seguo un cliente che fa verifiche di controllo ogni N pezzi che produce, questa funzionalità al momento non mi sembra esistere nell'app PQA.

**Possibile soluzione richiesta**
Sarebbe possibile inserire un valore "soglia scaglione" da utilizzare per staccare ordini di controllo per ogni multiplo della soglia quando si registra una fase di ciclo "In corso" o di "Output" (ma magari anche in ingresso merci sugli acquisti) ?
Inoltre molto spesso c'è comunque un controllo almeno al primo pezzo quindi sarebbe comunque da emettere un ordine anche se non si raggiunge la soglia (In pratica ogni registrazione staccherebbe sempre almeno un ordine di controllo).

**Esempi**
"Soglia scaglione" = 30 PZ
Registro 5 PZ --> Un ordine di controllo (il primo pezzo)
Registro 30 PZ --> Due ordini di controllo (il primo pezzo e il trentesimo)
Registro 89 PZ --> Tre ordini di controllo (il primo pezzo, il trentesimo, il sessantesimo)

Grazie.

**Comment by Giuliano-Velludo-EOS** [comment]
Come discusso nella call teams del 22/09 la funzionalità và sviluppata come custom. Siamo disponibili a offrire supporto per la realizzazione.
