### ISSUE TITLE
CWS - External Logistic Manual No. to overwrite the CWS Shipment No.

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#228]
When a customer handles part of his warehouse externally, the external logistics agency uses a custom number to ship the items (DDT No.).
In Business Central it can be useful to have the exact same number as the CWS Shipment No.

**Comment by Giuliano-Velludo-EOS** [comment]
Hi Mattia,
You can use this event:
https://docs.eos-solutions.it/en/docs/apps-tech/a879d9e1-a8d9-4dc8-87d8-69d278c5e003/codeunit/codeunit18122374.html#onbeforegetheadernofromwhse

If the ShipmentNo is already populated, the CWS app keeps it good
