### ISSUE TITLE
Aggiunta del campo CAUSALE nelle liste SSU e PSU

### ISSUE THREAD

**Issue by DanieleMonti** [EOS-Solutions/IDEAS#23]
Nelle seguenti liste:
Riepilogo carichi reso (SSU)
Note addebito interessi emesse
Riepilogo documento di vendita (SSU)
Riepilogo fattura registrata vendite (SSU)
Riepilogo documenti vendite archiviati (SSU)
Riepilogo spedizione registrata vendite (SSU)
Riepilogo note credito registrate vendite (SSU)
Riepilogo spedizione reso (PSU)
Riepilogo carichi acquisto (PSU)
Riepilogo archivio acquisto (PSU)
Riepilogo fatture di acquisto (PSU)
Riepilogo documenti di acquisto (PSU)
Riepilogo note di credito di acquisto (PSU)

Non è presente il campo Causale (Reason Code) della tabella Header dei documenti.

![Eos_ReasonCode](https://user-images.githubusercontent.com/84074321/117958592-77c7be00-b31b-11eb-8f1f-b625f2918e0c.jpg)

**Comment by AndreaDiCeglie** [comment]
Header fields are not present in pages. 
Adding header fields needs physical implementation of this fields (or flow fields) on sales line table.
This has a big impact on all apps and may provoke poor perfomance
