### ISSUE TITLE
App: Sales and purchase Promotions for WholeSales(SPP) Example to update from Sales Lines

### ISSUE THREAD

**Issue by Diego-Ripamonti-EOS** [EOS-Solutions/IDEAS#231]
Ho fatto uno sviluppo dove aggiorno i prezzi SPP su delle righe di ordine di vendita.
Ho dovuto aggiornare i prezzi dopo che viene inseriti la riga con sconto e prezzi.
Se vi interessa come sviluppo vi fornisco il codice sorgente.
fatemi sapere

**Comment by hemisphera** [comment]
We will take a look at the code (send it by mail, thanks) and then decide whether we implement it.

**Comment by hemisphera** [comment]
No feedback received.
