### ISSUE TITLE
Rendere estensibile Enum "EOS060 Work Request Status"

### ISSUE THREAD

**Issue by ABardazzi** [EOS-Solutions/IDEAS#232]
Dobiammo aggiungere uno sato all'Enum "EOS060 Work Request Status" che però non è estensibile. C'è un motivo? Potete procedere con estendibilità? Grazie

**Comment by AndreaDiCeglie** [comment]
L'enum è reso non editabile volutamente poichè tutta la business logic che ne consegue deve tenere in considerazione questo nuovo valore.

**Comment by AndreaDiCeglie** [comment]
Current status available are (see below), additional status should managed using EOS Data security or additional field "Status reason code"

    value(0; Planned)
    {
        Caption = 'Planned';
    }
    value(1; Released)
    {
        Caption = 'Released';
    }
    value(2; "In Progress")
    {
        Caption = 'In Progress';
    }
    value(3; Finished)
    {
        Caption = 'Finished';
    }
    value(4; "To Approve")
    {
        Caption = 'To Approve';
    }
