### ISSUE TITLE
FTE - filtro dei documenti in entrata

### ISSUE THREAD

**Issue by AG1GA** [EOS-Solutions/IDEAS#234]
Nella pagina "file in entrata" oppure "anteprima documento elettronico in entrata" filtrare i documenti in base alla descrizione inserita nel file xml/sezione "DatiBeniServizi". Questa funzione potrebbe essere utile per trovare i documenti con le descrizioni specifiche come "articolo X", "servizi di...", etc, per esempio, "monitor Dell nr. 123456", "servizi di consulenza", "ugello per irrigazione da 15mm", etc.

**Comment by AndreaDiCeglie** [comment]
DateBeniServizi is a detail line attribute, the request sound like to cross search both in header and lines.

You could give a try setting up the "Company Data search" adding the Inbound document table

![image](https://github.com/EOS-Solutions/IDEAS/assets/33353905/292be111-160c-46d6-9621-a6e34e37d3e3)
