### ISSUE TITLE
ECS: Save value nel report della creazione delle fatture

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#236]
Ciao,

potreste per favore farlo così, che i filtri messi vengono salvati.

![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/24aba67e-d499-4a32-b556-390509bbfb65)

**Comment by AndreaDiCeglie** [comment]
Needs check for unexpected-undesired behaviours
