### ISSUE TITLE
SGL Aggiornamento documenti da fatturare

### ISSUE THREAD

**Issue by stefanocorradinidoit** [EOS-Solutions/IDEAS#237]
In fase di generazione della spedizione viene inserito nella DTI Entry il valore dell'ordine nel momento della registrazione come importo da fatturare ma se viene modificato successivamente il prezzo dell'ordine non c'e' modo di effettuare un aggiornamento e quindi il valore in attesa di fattura è errato (Naturalmente se il documento è già stato fatturato non ci deve più essere modo di fare nessun aggiornamento). Visto che si tratta di operazioni sporadiche credo che si potrebbe integrare il report di AGGIORNA MOV.DOC. DA FATTURARE SGL con una nuova opzione in modo che sia possibile ricalcolare le spedizioni non fatturate.

**Comment by AndreaDiCeglie** [comment]
This is not considered correct from a business process point o view. We suggest to discuss with Finance competence circle about the suggested solution
