### ISSUE TITLE
EAN128 Library in EOS Administration Library (WI 13130)

### ISSUE THREAD

**Issue by hemisphera** [EOS-Solutions/IDEAS#239]
**Describe the solution you'd like**
In EOS Platform C/AL version there was a codeunit "Barcode Management" (or EAN128 Management) that provided the ability to construct a EAN128 string including the various data parts and handling it's fixed and/or variable lengths, including separator and start/stop characters. This string could then be passed along to the barcode encoding library (now EOS FunctionAPI) which would generate a GS1-128 compatible barcode.

This library has never been ported to AL and should be included in EOS Administration Library.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by Thomas-Torggler-EOS** [comment]
Done
