### ISSUE TITLE
Prospetto Componenti App MMM (WI 13133)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#240]
-  	Sul calcolo componenti aggiungere un Filtro su data versione adesso è una data secca che è poco utile 

- 	Sul calcolo componenti Aggiungere filtro per codice versione 

- 	Aggiungere  filtro sulla funzione cambia componenti “Escludi elaborati"

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciato
