### ISSUE TITLE
Expand "Code" in MPL App

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#243]
La App MPL ha, nella tabella di setup "EOS086 Planning Setup (70491929)", il campo "Code" che è lungo 10 caratteri.
Questo è molto limitante soprattutto per i progetti nei quali i setup di pianificazione sono decine.

L'ideale sarebbe espandere il campo a 20 caratteri così da permetterne una classificazione più accurata.

**Comment by AndreaDiCeglie** [comment]
unfortunately extending (key) fields dimensions for apps published on AppSource is a breaking change.
This mean :
- Obsolete all the table
- create a new table
- move data
- remap all table relations
- obsolete all related table
