### ISSUE TITLE
DocSolutions: order visible attribute in FactBox

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#244]
La funzionalità di visualizzazione delle informazioni nella FactBox è molto comoda ma non è possibile impostarne l'ordinamento:

![image](https://github.com/EOS-Solutions/IDEAS/assets/72971467/84e1eaba-d826-439d-8b08-f1116b8508ce)

L'idea è quella di aggiungere una colonna nellla tabella "EOS069 Library Visible Attr. (18121912)" per impostare la sequenza di visualizzazione:

![image](https://github.com/EOS-Solutions/IDEAS/assets/72971467/10e7f9c2-1540-49ba-bdd0-80ba491c0788)

Questo aiuterebbe a mostrare le informazioni con più coerenza.

**Comment by AndreaDiCeglie** [comment]
Ciao Matteo, l'utilità di questa funzionalità non è molto chiara
