### ISSUE TITLE
Collegamento Tabella Handling Unit Content ai movimenti warehouse

### ISSUE THREAD

**Issue by DavidJEOS** [EOS-Solutions/IDEAS#246]
Ciao,

vi scrivo per proporre la seguente idea, collegare la tabella (e quindi i movimenti) EOS055 Handling Unit Content (70491905) con la warehouse entries, oppure riportando sulla 70491905 il nr. documento da cui è stata creata/rettificata/spedita... 
questo perché senza nessun dato di collegamento non esiste nessun campo per riconciliare i movimenti delle HU con le warehouse entries o le item ledger entries.
Questo deriva dal fatto che: se un utente mi fa una rettifica dall'edit del contenuto HU oppure mi fa una rettifica di giornale dimenticandosi di inserire la HU da quel momento in poi abbiamo un disallineamento che difficilmente è riconciliabile.
Giustificare che il disallineamento non è causato da 365BC, ma da un errore utente non è per nulla semplice. 
Il campo per eseguire i controlli nel setup (Inventory check policy) non basta a gestire la situazione. 

(es. per farlo su 149 movimenti di contabilità articolo e 1011 movimenti HU per quell'articolo/lotto abbiamo dovuto utilizzare la data di creazione del movimento estraendo direttamente la tabella Handling Unit Content)

Saluti

David Jean Pansini

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao mettere il riferimento alla warehouse entry o alla item ledger entry non è tecnicamente fattibile. Dal mio punto di vista se hai il check impostato a rigoroso il problema non Si dovrebbe mai verificare. In alternativa non ti basterebbe sapere quali sono i movimenti "inseriti" manualmente ?
