### ISSUE TITLE
EOS Comm : exposing of “Get Entries to Settle” Procedure on Commission Settlement Journal (WI 13583)

### ISSUE THREAD

**Issue by TekSB** [EOS-Solutions/IDEAS#247]
**Is your feature request related to a problem? Please describe.**
- To allow user to settle commission to a sales person within same period multiple times.
- To allow user to settle commission by product wise.

**Describe the solution you'd like**

Commission Settl. Jnl. Line (Page: 18008306; Table: 18008306)

1. Creating a new flag “Create Purch. Inv”.

2. Creating a new routine by calling the “Get Entries to Settle” to allow user to select following filters.  
- Commission Period
- Salesperson
- Item Code
Once the data populates with flag “Create Purch. Inv” in Commission Settl. Jnl. Lines

3. Upon posting we will need to create the Purch Invoice with Settlement line information group by salesperson
- Posting date
- Salesperson (Vendor)
- Settlement GL from Salesperson
- Amount

**Describe alternatives you've considered**
o	The advice was to create/update journal lines by each field as temporary solution. However, we still need the procedure to be exposed to call it from code. Otherwise, the logic can’t follow if there are any changes made by EOS later stages.

**Additional context**

**Comment by AndreaDiCeglie** [comment]
**_1) "To allow user to settle commission to a sales person within same period multiple times."_**

The main issue about this is the primary Key of the journal header that is not designed for multiple or partial posting.

When a "Commission Settl. Jnl." is settled some fields (Invoice no) on header are set and the journal can't be opened.

The main event to handle this is
**EOSCommEventPublisher.OnBeforeProspectReopen(Rec, IsHandled);** 
where try to skip / handle checks that avoid the journal to be reopened.

Re-posting several time will break relation between Journal and related invoice (1:1 from 1:many) . This is breaking the relational model.

**2) _"To allow user to settle commission by product wise"_**
Posting only some records of the journal is not possible.
The Journal must be posted completely (all rows)
The total amount of the purchase invoice line should be equal to the sum of amounts on the Journal

From a technical perspective it's very hard to change this behaviour without changing the primary key of the journal and all the checks and validations there are depending on this.

**Comment by TekSB** [comment]
**1) "To allow user to settle commission to a sales person within same period multiple times."**

The main issue about this is the primary Key of the journal header that is not designed for multiple or partial posting.

_**[26/10]** The request is not to partial posting of settlement journal lines.
It is to "Get Entries" from commission ledger entries by specifying with filters (Product No, Date & Sales person) and posting of jrnl lines will be posted at once.
Example: Sales person X has product A and product B related commission lines in January month.
To get the commission lines, it needs to release in 2 instances._

    First time run with following filters
      Period : Jan
      Salesperson : X
      Product No: A
      and post the commission settlement journal line.
    
    Second time run with following filters
      Period : Jan
      Salesperson : X
      Product No: B
      and post the commission settlement journal line.

When a "Commission Settl. Jnl." is settled some fields (Invoice no) on header are set and the journal can't be opened.
_**[26/10]** Not fully understood, what is it referring to.?_

The main event to handle this is
EOSCommEventPublisher.OnBeforeProspectReopen(Rec, IsHandled);
where try to skip / handle checks that avoid the journal to be reopened.

Re-posting several time will break relation between Journal and related invoice (1:1 from 1:many) . This is breaking the relational model.
_**[26/10]** I think you have misunderstood this. One commission ledger entry process at once. we are not requesting to split lines to process partial. pls review the above example._

**2) "To allow user to settle commission by product wise"**
Posting only some records of the journal is not possible. [26/10] Yes that's ok.
The Journal must be posted completely (all rows) [26/10] Yes, that's ok too.
The total amount of the purchase invoice line should be equal to the sum of amounts on the Journal

From a technical perspective it's very hard to change this behaviour without changing the primary key of the journal and all the checks and validations there are depending on this.

_**[26/10]** Pls review the comments with example and advise._

**Comment by matteomontanari** [comment]
Hi TekSB

The sole purpose of the page 'Commission Settl. Jnl. Lines (CMS)' (Page 18008306) is to create new manual commission entries (not originating from posted invoices or credit notes) and manage specific scenarios such as advances and their reversals. It is not designed for commission settlement and was not created to generate purchase invoices for agent payments.

These two activities should be performed on the 'Commission Prospect' page (Page 18008312), which, however, does not allow for partial line registration. The scenario you requested is not supported, and I don't think it is possible to achieve it through an extension.

Matteo Montanari
