### ISSUE TITLE
HUM - taglia e incolla HUM con selezione multipla (WI 13474)

### ISSUE THREAD

**Issue by chiarapergolini** [EOS-Solutions/IDEAS#248]
Nell'app delle HUM sarebbe utile poter copiare e incollare più di un'unità di movimentazione alla volta. Sarebbe molto utile quando la packing list viene creata manualmente, da zero o tramite un suggerisci righe parziale.

![2023-10-17_14h42_29](https://github.com/EOS-Solutions/IDEAS/assets/148222794/ee1f9deb-8615-4b5a-9fe3-556db7d933b5)

**Comment by Dario-Zaniboni-EOS** [comment]
Concordo con l'idea di Chiara.
Propongo un'ulteriore evolutiva legata al mondo HUM: https://github.com/EOS-Solutions/IDEAS/issues/251#issue-1957410211

**Comment by Mariangela-DeMaio-EOS** [comment]
Released versions 23.0.20 22.0.39 App EX055.01 "Advanced Logistic CDL".
