### ISSUE TITLE
report CONTO C/G - Movimenti SGL

### ISSUE THREAD

**Issue by SaraAmadei** [EOS-Solutions/IDEAS#249]
Per un cliente è sorta la necessità di aggiungere un “intestazione conto su nuova pagina” al report "Conto C/G - Movimenti SGL" in modo che sia presentabile ai revisori (dal momento che la stampa in xls non è fattibile perché tutti i fogli sono da formattare ). 

Collegamento all'immagine del report in questione: 
https://attachments.office.net/owa/sara.amadei%40eos-solutions.it/service.svc/s/GetAttachmentThumbnail?id=AAMkAGI2NWM5ZjY3LWFiOGYtNGFlMS1iZmRhLWMzNTQ1Nzk5OTU5NQBGAAAAAADkSlY0MQ%2FWSIEWcTngNHS9BwDO2b6dWmiyTLzefNAY9NkPAAAAAAEMAADO2b6dWmiyTLzefNAY9NkPAABSyMQeAAABEgAQAAe72zBox8tNjFXVasD0lns%3D&thumbnailType=2&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjczRkI5QkJFRjYzNjc4RDRGN0U4NEI0NDBCQUJCMTJBMzM5RDlGOTgiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJjX3VidnZZMmVOVDM2RXRFQzZ1eEtqT2RuNWcifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiNjZkYjFhY2Q2ZmNhNDVmYTgwZDJiY2JlYWExMzUwNTgiLCJzaWduaW5fc3RhdGUiOiJbXCJpbmtub3dubnR3a1wiLFwia21zaVwiXSIsInZlciI6IkV4Y2hhbmdlLkNhbGxiYWNrLlYxIiwiYXBwY3R4c2VuZGVyIjoiT3dhRG93bmxvYWRAY2RkMmIyZmYtNjlhZi00OWUzLTkxNjEtNjgwZmI1OGEwMTFkIiwiaXNzcmluZyI6IldXIiwiYXBwY3R4Ijoie1wibXNleGNocHJvdFwiOlwib3dhXCIsXCJwdWlkXCI6XCIxMTUzODAxMTI1NDM1OTUyOTc3XCIsXCJzY29wZVwiOlwiT3dhRG93bmxvYWRcIixcIm9pZFwiOlwiYTczNGIzY2ItM2RhZi00YmQwLWJiNGQtYmFjYmJkZDRmYTgxXCIsXCJwcmltYXJ5c2lkXCI6XCJTLTEtNS0yMS0xMDMzNTE2MDY1LTE3NDIyODA5MC01NzQyMjIwMzItNTI4MzQ5MzJcIn0iLCJuYmYiOjE2OTc2MTIwMDUsImV4cCI6MTY5NzYxMjYwNSwiaXNzIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwQGNkZDJiMmZmLTY5YWYtNDllMy05MTYxLTY4MGZiNThhMDExZCIsImF1ZCI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9hdHRhY2htZW50cy5vZmZpY2UubmV0QGNkZDJiMmZmLTY5YWYtNDllMy05MTYxLTY4MGZiNThhMDExZCIsImhhcHAiOiJvd2EifQ.IBkAsE4xi2xYl_iIrrdH3QXrM1CoCNB2v671O5UgZ7kxyUbwK_6BhzjbUNLVGBAYhzZvpyUze_PYr-HXACS3idkp7Ga1msd6W_YdnmNYWFUS9GJW1jXjXL8_iimXwmab7fiGrlK9ejy0EcpFE7FthNaf_kaT3mhYpmuQMKwjB1PQT0zbvaJZc2EC6Sd_pe6Rqa9Hr9HP9DehgM8tmQMbE7OVkGylj8ZiIv7Te9_PaDoWI3dHrE_x5jNH6zruvAW9S-yyjPHnWA2uSnKcKwmcOkTzx56Vo9ZpN_HU0SUdkG56WClVGCYVmlAs73aLktQzr4IIbIFBcByWS5ny7P8pfQ&X-OWA-CANARY=_wtMvq1IX0eXI1VOeHtm5KDv-kSnz9sYhz4g0vxhZA3z-6WiSwKDu_jft7Ik-vmWJgDmeXWLarM.&owa=outlook.office.com&scriptVer=20231006004.17&animation=true&persistenceId=38ddb838-6e45-4dac-b689-95234a7a0bc4

esempio report (lascio il collegamento all'immagine): 
https://attachments.office.net/owa/sara.amadei%40eos-solutions.it/service.svc/s/GetAttachmentThumbnail?id=AAMkAGI2NWM5ZjY3LWFiOGYtNGFlMS1iZmRhLWMzNTQ1Nzk5OTU5NQBGAAAAAADkSlY0MQ%2FWSIEWcTngNHS9BwDO2b6dWmiyTLzefNAY9NkPAAAAAAEMAADO2b6dWmiyTLzefNAY9NkPAABSyMQeAAABEgAQALSQo5HHuaJNjVaGurJBeZQ%3D&thumbnailType=2&token=eyJhbGciOiJSUzI1NiIsImtpZCI6IjczRkI5QkJFRjYzNjc4RDRGN0U4NEI0NDBCQUJCMTJBMzM5RDlGOTgiLCJ0eXAiOiJKV1QiLCJ4NXQiOiJjX3VidnZZMmVOVDM2RXRFQzZ1eEtqT2RuNWcifQ.eyJvcmlnaW4iOiJodHRwczovL291dGxvb2sub2ZmaWNlLmNvbSIsInVjIjoiNjZkYjFhY2Q2ZmNhNDVmYTgwZDJiY2JlYWExMzUwNTgiLCJzaWduaW5fc3RhdGUiOiJbXCJpbmtub3dubnR3a1wiLFwia21zaVwiXSIsInZlciI6IkV4Y2hhbmdlLkNhbGxiYWNrLlYxIiwiYXBwY3R4c2VuZGVyIjoiT3dhRG93bmxvYWRAY2RkMmIyZmYtNjlhZi00OWUzLTkxNjEtNjgwZmI1OGEwMTFkIiwiaXNzcmluZyI6IldXIiwiYXBwY3R4Ijoie1wibXNleGNocHJvdFwiOlwib3dhXCIsXCJwdWlkXCI6XCIxMTUzODAxMTI1NDM1OTUyOTc3XCIsXCJzY29wZVwiOlwiT3dhRG93bmxvYWRcIixcIm9pZFwiOlwiYTczNGIzY2ItM2RhZi00YmQwLWJiNGQtYmFjYmJkZDRmYTgxXCIsXCJwcmltYXJ5c2lkXCI6XCJTLTEtNS0yMS0xMDMzNTE2MDY1LTE3NDIyODA5MC01NzQyMjIwMzItNTI4MzQ5MzJcIn0iLCJuYmYiOjE2OTc2MTIwMDUsImV4cCI6MTY5NzYxMjYwNSwiaXNzIjoiMDAwMDAwMDItMDAwMC0wZmYxLWNlMDAtMDAwMDAwMDAwMDAwQGNkZDJiMmZmLTY5YWYtNDllMy05MTYxLTY4MGZiNThhMDExZCIsImF1ZCI6IjAwMDAwMDAyLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMC9hdHRhY2htZW50cy5vZmZpY2UubmV0QGNkZDJiMmZmLTY5YWYtNDllMy05MTYxLTY4MGZiNThhMDExZCIsImhhcHAiOiJvd2EifQ.IBkAsE4xi2xYl_iIrrdH3QXrM1CoCNB2v671O5UgZ7kxyUbwK_6BhzjbUNLVGBAYhzZvpyUze_PYr-HXACS3idkp7Ga1msd6W_YdnmNYWFUS9GJW1jXjXL8_iimXwmab7fiGrlK9ejy0EcpFE7FthNaf_kaT3mhYpmuQMKwjB1PQT0zbvaJZc2EC6Sd_pe6Rqa9Hr9HP9DehgM8tmQMbE7OVkGylj8ZiIv7Te9_PaDoWI3dHrE_x5jNH6zruvAW9S-yyjPHnWA2uSnKcKwmcOkTzx56Vo9ZpN_HU0SUdkG56WClVGCYVmlAs73aLktQzr4IIbIFBcByWS5ny7P8pfQ&X-OWA-CANARY=_wtMvq1IX0eXI1VOeHtm5KDv-kSnz9sYhz4g0vxhZA3z-6WiSwKDu_jft7Ik-vmWJgDmeXWLarM.&owa=outlook.office.com&scriptVer=20231006004.17&animation=true&persistenceId=38ddb838-6e45-4dac-b689-95234a7a0bc4

**Comment by AndreaDiCeglie** [comment]
Buongiorno,

Purtroppo le immagini non sono visibili, sembra che il link punti ad una posizione interna di outlook. Ad ogni modo esistono diverse possibilità per ottenere il risultato desiderato senza modifiche all'app standard:

- I layout dei report sono customizzabili liberamente tramite funzionalità standard BC "custom report layout" 
- in Execel i dati sono esportabili con o senza layout


![image](https://github.com/EOS-Solutions/IDEAS/assets/33353905/041fa278-2e0f-4bef-9f51-9bd54d240b8f)
![image](https://github.com/EOS-Solutions/IDEAS/assets/33353905/39c27882-2843-4fd8-9ee3-fdaf88d094b0)
