### ISSUE TITLE
Add the County-Table to Customer, Contact, Vendor

### ISSUE THREAD

**Issue by kurtmarschall** [EOS-Solutions/IDEAS#25]
**Is your feature request related to a problem? Please describe.**
a customer that is migrating from Nav to BC SaaS would like to have the table County (18004135) in BC.
![image](https://user-images.githubusercontent.com/78731376/124147762-49e73600-da8f-11eb-8e59-3b32150382e7.png)

**Describe the solution you'd like**
Create the County Table as in the Platform Nav

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by f0ffee** [comment]
Table 18123703 "EOS County" is already included in the Common Data Layer app
