### ISSUE TITLE
Movimenti COGE (ripristino funzionalità) (WI 13480)

### ISSUE THREAD

**Issue by SilviaBecciolini** [EOS-Solutions/IDEAS#250]
Richiesta dettagliata 
Nella visualizzazione dei movimenti contabili se il tipo origine è cliente/fornitore/banca/cespite aggiungere la decodifica: 
 
![image](https://github.com/EOS-Solutions/IDEAS/assets/148539672/274457c3-364c-42c5-b638-13d4e18d3c97)

 
 
Come era gestito in platform: 
 
 
![image](https://github.com/EOS-Solutions/IDEAS/assets/148539672/c8356db4-5f1a-4b30-9941-8f4b95c7876c)

 
BC14 EOS PLATFORM 
 
Questa vecchia funzione non mi sembra presente in BC, si può implementare? 
Grazie

**Comment by AndreaDiCeglie** [comment]
We need to evaluate possible performance impact but this is basically planned to be  implemented in 
"Finance Common Data Layer"

**Comment by SilviaBecciolini** [comment]
Ciao, riesci a darmi un indicazione di quando sarà disponibile per averne una idea tipo gennaio o marzo o ...
Grazie

**Comment by Roberto-Lucarelli-EOS** [comment]
Aggiunta la colonna Nome origine che mostra il nome dell'anagrafica indicata nel campo nr. origine.
La colonna è di default visible = No (come i campi standard Tipo e nr. origine)

![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/9d1f82ac-a758-42b4-9adb-99705e1a70d9)

Le modifiche sono presenti nelle seguenti versioni :
Accruals and Simulated Common Library 22.0.35.0
Accruals and Simulated Common Library 23.0.30.0
Accruals and Simulated Common Library 24.0.3.0
