### ISSUE TITLE
HUM - Assegnazione multipla da Spedizione Warehouse / Packing List (WI 13477)

### ISSUE THREAD

**Issue by Dario-Zaniboni-EOS** [EOS-Solutions/IDEAS#251]
Consentire l'assegnazione multipla delle HUM, sia a partire dalla factbox presente in spedizione warehouse, sia dalla action riportata nella pagina della Packing List.

![image](https://github.com/EOS-Solutions/IDEAS/assets/106167410/4276ecf4-50a4-4a11-b045-00f52fc554c9)

![image](https://github.com/EOS-Solutions/IDEAS/assets/106167410/6e228b7f-0587-47c6-ac98-c9025a7914be)

**Comment by Mariangela-DeMaio-EOS** [comment]
Released versions 23.0.20 22.0.39 App EX055.01 "Advanced Logistic CDL".
