### ISSUE TITLE
PRQ/ADR: modifiche stampa e invio e-mail per gestione multi fornitore di riga, integrazione con setup report ADR

### ISSUE THREAD

**Issue by chiarapergolini** [EOS-Solutions/IDEAS#252]
L'app **PRQ (richieste di acquisto)** è stata recentemente integrata con la funzione dei testi avanzati (ADR) sia di riga che di testata, ma ritengo che questo non sia sufficiente per considerare l’app PRQ completamente integrata con la **gestione multi fornitore**, funzione che rappresenta uno dei principali vantaggi offerti dall'app rispetto all'utilizzo delle offerte di acquisto standard.

Per un cliente con live gennaio 2024 avremmo bisogno di avere un’integrazione aggiuntiva per quanto riguarda la stampa delle richieste di acquisto. Attualmente, se nelle righe della richiesta sono presenti più fornitori, la stampa è univoca e questo impedisce di usarla come documento verso i fornitori.

Faccio richiesta per estendere le funzionalità dell’app in modo tale che:

1. In presenza di più fornitori in riga, vengano generati tanti pdf quanti sono i fornitori. Utilizzando l'opzione "Invia a PDF" sarebbe inoltre utile salvare il PDF con "Nr richiesta - Codice fornitore"

![image](https://github.com/EOS-Solutions/IDEAS/assets/148222794/05110748-6e29-4519-98bc-9af44562a35e)

2. Sempre riguardo la stampa, ho visto su integration che sono state aggiunte le funzioni “Salva” e “Invia”. Faccio richiesta per inserire il "codice report ADR" anche nella request page del report (azione “Stampa”) come funziona per tutti gli altri report, in modo da non dover necessariamente effettuare il download con l’azione “Salva” e anche da poter usare diversi codici report a seconda delle esigenze.

![image](https://github.com/EOS-Solutions/IDEAS/assets/148222794/798e7df9-7576-4ecb-8f8e-f8e4f973fc90)

3. La funzione "Invia" e-mail dovrebbe essere integrata per supportare la gestione multi fornitore in modo tale che vengano inviate tante e-mail quanti sono i fornitori, come se fosse un invio multiplo già gestito dall'app ADR per l'invio massivo. In questo caso dovrebbe esserci la possibilità, nella pagina di invio, di eliminare i gruppi a cui non si vuole mandare l'e-mail.

**Comment by AndreaDiCeglie** [comment]
The entire app is designed for one document - one print only. The suggestion cannot be accepted

**Comment by chiarapergolini** [comment]
@AndreaDiCeglie regarding the second point: have the ADR configuration report code on the print request page? I know that the labs was working on a modification that would allow you to choose the ADR report code with the Save action.

**Comment by AndreaDiCeglie** [comment]
On report 71367880 "EOS009.18 PRQ Document" this is possible, please open a separate issue for this and keep separated the issues for future request
