### ISSUE TITLE
importo proposto su registrazione coge selezionando collegamento a nr movimento 

### ISSUE THREAD

**Issue by ManRiccardo** [EOS-Solutions/IDEAS#253]
Nelle registrazioni coge non propone importo partita selezionandola/collegandola a elenco partite aperte)
Nella page Registrazioni COGE è possibile scegliere i movimenti da collegare:
un movimento alla volta:  tramite il campo "Collega-a movimento" sulla riga (si vedono TUTTI i movimenti, aperti/chiusi)

Una volta scelto il movimento da collegare sarebbe possibile che il sistema proponesse l’importo della partita selezionata sulla riga?

**Comment by AndreaDiCeglie** [comment]
This scenario was already evaluated during app design.
On Journal Page  due to technical limitation the request cannot be realized. Is only available on posted entries
