### ISSUE TITLE
PRQ/ADR: ADR report code on request page print PRQ (WI 13798)

### ISSUE THREAD

**Issue by chiarapergolini** [EOS-Solutions/IDEAS#254]
Nella request page della stampa della richiesta di acquisto si richiede la possibilità di selezionare un codice report ADR (azione “Stampa”) come funziona per tutti gli altri report, in modo da non dover necessariamente effettuare il download con l’azione “Salva” (vista in una preview su integration), da poter usare diversi codici report ed appoggiarsi al "Progetta layout" per estendere la stampa a seconda delle necessità dei clienti.

![image](https://github.com/EOS-Solutions/IDEAS/assets/148222794/5fad966d-f5e2-47e6-b49b-e3f21e4b2a96)

**Comment by Stefano-Primo-EOS** [comment]
È stata rilasciata una nuova app "Advanced Document Reporting for Purchase Request". 
È in corso di pubblicazione su AppSource ma ci vorrà almeno una settimana, per onPrem è già disponibile
