### ISSUE TITLE
Data Security - Disabilitare Pulsante "Prossimo Stato" su EDS Fact Box quando "prossimo stato suggerito non è impostato" (WI 13803)

### ISSUE THREAD

**Issue by patriziabuccioni** [EOS-Solutions/IDEAS#255]
Nell'ultima versione rilasciata di Data Security è stato introdotto il pulsante "Prossimo stato" nella FactBox EDS Status Record.
![img1](https://github.com/EOS-Solutions/IDEAS/assets/152380630/a993aed0-83ab-43ed-8437-1251fc45262b)
Se per lo stato corrente non è impostato a setup il prossimo stato suggerito, esce il messaggio di errore: 
![img2](https://github.com/EOS-Solutions/IDEAS/assets/152380630/1e715f7c-a845-4efd-819f-1c694d3ff24e)

Per evitare fraintendimenti ai clienti, si potrebbe rendere disabilitato il menu "Prossimo Stato", quando non è impostato a setup il prossimo stato suggerito? 
In questo modo l'utente non avrebbe modo di usare il menu "Prossimo Stato" e non riceverebbe segnalazioni di errore.
Grazie
Patrizia Buccioni

**Comment by AndreaDiCeglie** [comment]
Avendo valutato la richiesta si è optato per un implementazione differente.
Se non c'è il "prosimo stato" anzichè dare errore verrà aperta la pagina di selezione stato
