### ISSUE TITLE
CDL: Document classes on production orders

### ISSUE THREAD

**Issue by Ponch18** [EOS-Solutions/IDEAS#258]
We need to use CDL document classes like on sales and purchase, also on production order.

**Comment by AndreaDiCeglie** [comment]
The business need is not clear.
Document classes on Purchase / Sales has a lot of properties that can't be applied to manufacturing.

What the goal of the implementation ? "No of series and description only ?"
On the other any other app that is creatin P.O. should provide a mechanism to set a default Document Class.

![image](https://github.com/EOS-Solutions/IDEAS/assets/33353905/2bc70ec4-027c-4faf-8f36-b4724469905a)

Current is evaluation from Labs is:
- No clear business value
- Need more specification
- High cost of implementation (considering all potential apps that creates P.O)
-  The same way can be provide as standard app it can be done as PTE

**Comment by Ponch18** [comment]
"No of series and description only" can be enough.

In our case we need to have the possibility to define a document class that allow us to categorize production orders and choose a different no series.

"High cost of implementation (considering all potential apps that creates P.O)", I think that is the same problem as in sales and purchase. We can handle PO creation with a default doc. class.

"The same way can be provide as standard app it can be done as PTE" I think is better to have a standard solution to use on different customers instead of create a new custom and copy it on all project that require it.
