### ISSUE TITLE
EOS Product Configurator from Business Central Jobs (WI 14866)

### ISSUE THREAD

**Issue by JTAdmBdl** [EOS-Solutions/IDEAS#259]
Ability to launch the configuration from a Business Central Job Planning Line.

**Comment by AndreaDiCeglie** [comment]
Creating a configured Item from planning line is quite simple and can be done also as custom.

The main issue is related to prices, from a Job Planning line would not be possible to get calculated prices, have you evaluated this part ?

**Comment by MartinSchnurrKUMAVISION** [comment]
Hello,
We also have customers/interested parties who have asked about the Configurator product in the project plan line.

Your competitor has realized this!

However, the issue of prices is a very important aspect here.
The price calculation should be analogous to sales!

**Comment by Giuliano-Velludo-EOS** [comment]
hello @JTAdmBdl and @MartinSchnurrKUMAVISION Can we use the same price matrix for calculating prices that we use for sales?

**Comment by MartinSchnurrKUMAVISION** [comment]
Hello @Giuliano-Velludo-EOS ,
from our point of view, we can use the matrix prices from sales in the proect plan line.

**Comment by Enrico-Marini-EOS** [comment]
Released Product Configurator versions: 23.0.71, 24.0.17
