### ISSUE TITLE
FTE: DatiOrdineAcquisto e DatiDDT (WI 14245)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#260]
Alcuni clienti sopratutto del settore food hanno fatture con un tante righe su una fattura di vendita. Per quello esce il problema che può capitare che va superato i 5MB.

Con un raggruppamento di DatiOrdineAcquisto e DatiDDT è possibile shrinkare il file senza che vanno tolto informazioni. La definizione lo consente di farlo:

![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/725587ef-f45d-43a7-af8c-1fa79ced3857)

Per DDT:
![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/3be381d1-a585-43b0-8b49-71a53850cb5a)

E per DatiOrdineAcquisto:
![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/48479578-f5a1-467b-be31-b476c590d2e0)

**Comment by AndreaDiCeglie** [comment]
Ciao Jakob,

Avete già valutato l'opzione di non esportarli ?

![image](https://github.com/EOS-Solutions/IDEAS/assets/33353905/c2fc8c04-3be4-4534-a99d-5d898db30fd0)

**Comment by jellemundeos** [comment]
Ciao Andrea,

purtroppo il cliente ha bisogno di communicare le righe al cliente.

Saluti
Jakob

**Comment by jellemundeos** [comment]
Buongiorno,

mi potete già dare qualche novità su questo?

Grazie
Jakob

From: Jakob Ellemund ***@***.***>
Sent: Thursday, December 21, 2023 1:30 PM
To: EOS-Solutions/IDEAS ***@***.***>; EOS-Solutions/IDEAS ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [EOS-Solutions/IDEAS] FTE: DatiOrdineAcquisto e DatiDDT (Issue #260)

Ciao Andrea,

purtroppo il cliente ha bisogno di communicare le righe al cliente.

Saluti
Jakob

**Comment by jellemundeos** [comment]
Buongiorno,

mi potete già dare qualche novità su questo?

Grazie
Jakob


Schöne Grüße
Jakob

From: Jakob Ellemund
Sent: Monday, January 15, 2024 10:49 AM
To: EOS-Solutions/IDEAS ***@***.***>; EOS-Solutions/IDEAS ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [EOS-Solutions/IDEAS] FTE: DatiOrdineAcquisto e DatiDDT (Issue #260)

Buongiorno,

mi potete già dare qualche novità su questo?

Grazie
Jakob

From: Jakob Ellemund ***@***.******@***.***>>
Sent: Thursday, December 21, 2023 1:30 PM
To: EOS-Solutions/IDEAS ***@***.******@***.***>>; EOS-Solutions/IDEAS ***@***.******@***.***>>
Cc: Author ***@***.******@***.***>>
Subject: RE: [EOS-Solutions/IDEAS] FTE: DatiOrdineAcquisto e DatiDDT (Issue #260)

Ciao Andrea,

purtroppo il cliente ha bisogno di communicare le righe al cliente.

Saluti
Jakob
