### ISSUE TITLE
SPP  Funzione "Copia prezzo di vendita" specificare data inizio+fine ( WI 14035 )

### ISSUE THREAD

**Issue by MarkusMoserEOS** [EOS-Solutions/IDEAS#261]
Ciao, 
![image](https://github.com/EOS-Solutions/IDEAS/assets/101793608/2cddd0b1-8e8d-4def-bcbb-c7942ea5e465)

nella funzione "copia prezzo di vendita" sarebbe vantaggioso se si potrebbe anche mettere la data inizio e data fine. 
Perchè attualmente mette sempre da 01.01 (dell'anno dell'originale) - 31.12.2050

l'originale:
![image](https://github.com/EOS-Solutions/IDEAS/assets/101793608/c8eb0a81-c0d2-428d-858c-8680ac8ec24b)
la copia:
![image](https://github.com/EOS-Solutions/IDEAS/assets/101793608/7f88327b-0521-4b75-bbd1-5e900a107a0d)

In caso sono disponibile per domande.
L'esempio si trova in ambiente Labs società LABS DEL BZ TEAM2

Grazie
Markus

**Comment by Elio-Cometto-EOS** [comment]
CR Released on versions:
25.0.12
24.0.47
23.0.68
