### ISSUE TITLE
App ADR - Implementazione su ordine conto lavoro

### ISSUE THREAD

**Issue by mattiaoggioni** [EOS-Solutions/IDEAS#263]
Buongiorno,
sarebbe possibile implementare la funzione di invio email tramite App ADR anche per gli ordini di conto lavoro?
Sia partendo dalla lista degli ordini (page 35490) e sia partendo dalla scheda dell'ordine (page 12152)
![2024-01-15 09 56 04](https://github.com/EOS-Solutions/IDEAS/assets/98746220/729532f1-c2b4-4bd6-8a60-a876399ea73b)

**Comment by AndreaDiCeglie** [comment]
il bottone c'è già ad esempio sulla page 12152. avete installato l'app for Italy ?  Eos.EX009.01.AdvancedDocumentReporting.IT

**Comment by mattiaoggioni** [comment]
Ciao Andrea,
grazie. Ho risolto installando l’APP indicata


Mattia Oggioni
BC Consultant
EOS Solutions
Mail + Teams: ***@***.***
P:+390283508100 | Mob: +39 349 7727703
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.

Da: Andrea Di Ceglie ***@***.***>
Inviato: mercoledì 17 gennaio 2024 15:18
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Mattia Oggioni ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] App ADR - Implementazione su ordine conto lavoro (Issue #263)


il bottone c'è già ad esempio sulla page 12152. avete installato l'app for Italy ? Eos.EX009.01.AdvancedDocumentReporting.IT
