### ISSUE TITLE
EOS Data Security - Modifica sulla funzionalità "Prossimo stato"

### ISSUE THREAD

**Issue by Federico-Perucca-EOS** [EOS-Solutions/IDEAS#266]
La richiesta è quella di far vedere a fianco del pulsante **"Prossimo stato"** quale sarà effettivamente il prossimo stato a cui si verrà rimandati:
![image](https://github.com/EOS-Solutions/IDEAS/assets/105504926/d7a814cf-11ca-480b-96fc-67e44a43fd8c)

Chiaramente tale modifica vale solo se il valore del **"Prossimo stato"** esiste e cioè esso è stato specificato nell'apposito campo della tabella “stati tabella EDS” (table 18122142 “EOS DS Table Status”):
![image](https://github.com/EOS-Solutions/IDEAS/assets/105504926/812e30c3-001a-43e2-ab12-77f57c5330f7)

**Comment by AndreaDiCeglie** [comment]
dynamic captions on actions is not a standard pattern in BC

**Comment by Federico-Perucca-EOS** [comment]
Ciao @AndreaDiCeglie 
Curiosità: Quale standard BC non rispetta la caption dinamica?
Effettivamente non ne ho mai fatte o viste fare, però il fatto è che a noi servirebbe comunque averla (o avere qualcosa quantomeno di simile) principalmente per questo motivo:
Per come avete deciso di implementare l'idea numero 255 ([Data Security - Disabilitare Pulsante "Prossimo Stato" su EDS Fact Box quando "prossimo stato suggerito non è impostato" (WI 13803) · Issue #255 · EOS-Solutions/IDEAS (github.com)](https://github.com/EOS-Solutions/IDEAS/issues/255#issuecomment-1842977849)), se non farete anche questa funzionalità della caption dinamica, non si avrà alcun modo per capire se la funzionalità del prossimo stato è attiva o meno fino a quando non si premerà il pulsante di **Prossimo stato** stesso. O sbaglio? 
In ogni caso, se ritenete comunque non attuabile questa idea anche alla luce di questo, dovremo farla noi come custom in qualche modo e quindi avremo bisogno poi solamente di un vostro suggerimento sul come poterla fare.

**Comment by AndreaDiCeglie** [comment]
A) "Quale standard BC non rispetta la caption dinamica?"
Quello che intendevo scrivere è che in BC non ci sono precedenti di caption dinamiche sulle action e non vorremmo introdurre un nuovo pattern.

"Se la funzionalità del prossimo stato è attiva o meno fino a quando non si premerà il pulsante di Prossimo stato stesso. O sbaglio?" Non sbagli la funzionalità "prossimo stato" è semplicemente una nuova scorciatoia disponibile. Se non setuppata il sistema funziona come in precedenza.

**Comment by Federico-Perucca-EOS** [comment]
@AndreaDiCeglie grazie mille per le informazioni.
Allora proviamo a vedere se riusciamo a introdurre questa funzionalità con un custom.
Magari vi apro un ticket per chiedervi eventi/suggerimenti su come farlo.
