### ISSUE TITLE
APP PMM : Visualizzazione del Carico Risorse per Richieste di Lavoro (WI 14266)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#268]
Le richieste di lavoro generano dei movimenti che creano i carichi di lavoro. 
I carichi per ordini di assistenza o commessa sono già visibili 
Bisognerebbe poter visualizzare i carichi di lavoro (disponibilità residua) per richieste di lavoro. 
Sarebbe utile anche avere una visualizzazione dettagliata della pianificazione (pagina dei movimenti capacità per richieste)

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao @SIMONEGRASSI potresti dare qualche dettaglio in più per lo sviluppo o in alternativa ti può contattare il Dev ?

**Comment by Enrico-Marini-EOS** [comment]
Released versions of Plant Maintenance: 
23.0.47
24.0.23
