### ISSUE TITLE
EX066 CDL - Aggiunta dimensioni non globali in liste SSU e PSU (WI 7031)

### ISSUE THREAD

**Issue by enricozandoli** [EOS-Solutions/IDEAS#27]
Riportare nelle liste SSU e PSU, le dimensioni non globali specificate nel General Ledger Setup (dalla 3 alla 8)

In tutte le pagine standard è presente questa logica di visualizzazione dimensioni non globali per cui si potrebbe tranquillamente estendere per le liste delle app in oggetto.

**Comment by AndreaDiCeglie** [comment]
WI 7031
