### ISSUE TITLE
CDW - Preimpostazione filtro nel CDW Journal (WI 14263)

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#271]
Ciao,

il cliente latteria di vipiteno ha notato che questa funzione qua con l’aumento di righe registrato si rallenta.

![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/b7628850-257a-4365-9f36-2fe7b2b1b004)

Come idea pensavo che si può mettere dei filtri su Posting Date, Sell-To Customer e Bill-To Customer (per gli acquisti Buy-From Vendor e Pay-To Vendor) sotto il nome del batch per velocizzare il calcolo.

Grazie

**Comment by Roberto-Lucarelli-EOS** [comment]
é stata aggiunta una pagina per applicare i filtri al lancio delle 4 funzioni "Prendi riga ....". Su questa page è possibile applicare i filtri per cliente/fornitore e data di registrazione.
![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/ad5d9956-feac-493d-82e8-b18d2b957235)

La modifica è presente sulle versioni:
EX041 Close Documents Without Invoicing 22.0.55.0
EX041 Close Documents Without Invoicing 23.0.12.0
