### ISSUE TITLE
Fact Box Caratteristiche articolo/variante per riga ordine di produzione e righe ordini di trasferimento (WI 14874)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#272]
La stessa factbox che è disponibile sulla sub page delle righe documento di vendita è utile che sia disponibile anche su righe ordini di produzione e trasferimento

**Comment by Enrico-Marini-EOS** [comment]
Released Product Configurator version 23.0.73, 24.0.20
