### ISSUE TITLE
Estendere l'analisi della telemetria di Worksheet analisi telemetria (EAL) anche a segnali custom

### ISSUE THREAD

**Issue by mgrimoldieos** [EOS-Solutions/IDEAS#273]
Sarebbe utile, per riuscire ad interrogare segnali di telemetria custom inviati al Saas, poter estendere la tipologia di analisi della telemetria e, sempre tramite degli eventi, inserire la query KQL personalizzata che si desidera. In questo modo potremmo essere autonomi nella lettura della telemetria.

Attualmente sono presenti questi valori:
Report Execution
App Lifecycle
Slow AL Methods
Page Execution
Outbound Webservice Calls
Inbound Webservice Calls
Job Queue Status
Index Lifecycle
Errors
Scheduled Tasks
Messages
Database Locks
Lifecycle Events
Long Running SQL Queries
Top Table Locks

**Comment by AndreaDiCeglie** [comment]
E' già possibile aggiungere query KQL estendendo (custom ) l'app.
La possibilità di estendere queste viste è già stata valutata con il team delle performance ed è stata scartata.
Per query custom è consigliabile usare gli strumenti già disponibile come https://dataexplorer.azure.com/dashboards/
