### ISSUE TITLE
App ETO: Job structure creation additional functionalities (WI 14871)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#274]
Funzionalità avanzate per la creazione delle strutture di commessa partendo dagli ordini di vendita o dalle commesse stesse.
La necessità è quella di avere uno strumento che permetta, da un ordine di vendita su commessa o da una commessa stessa, di creare una o più strutture opportunamente configurate e, se necessario, già popolate tramite template.
Queste strutture devono poter avere un numero di serie e/o una categoria dedicati e deve essere possibile applicare un template specifico ad ogni tipologia di struttura.
Rif. TDE008643

**Comment by Roberto-Lucarelli-EOS** [comment]
Creata la tabella “Creazione assistita progetto” per gestire la creazione dei progetti / strutture progetto

![image](https://github.com/user-attachments/assets/17979618-3029-479e-a6e8-f17af38ca882)

![image](https://github.com/user-attachments/assets/0489b9ab-186b-46d6-882e-d51fd6444cb6)

La tabella “Creazione assistita progetto” è composta dai seguenti campi :
- Codice : indentifica il record della configurazione
- Descrizione
- Nr. Progetto : indica la numerazione da utilizzare per la creazione di un nuovo progetto
- Tipo creazione struttura preventivo : indicata come deve essere creato il il numero della struttura progetto di tipo preventivo (creata da offerta vendita). Questo campo ha i seguenti valori
1. Nr. Serie : per la creazione di una struttura preventivo viene usato il nr. Serie indicato nel campo “Nr. Struttura preventivo”
2. Progressivo preventivo : per la creazione di una struttura preventivo il numero sarà formato da “Nr. Progetto” + ‘ – ‘ + più un progressivo (es. PROG001-V01)
- Nr. Struttura preventivo : nr. serie da utilizzare in caso di “Tipo creazione struttura preventivo” = “Nr. Serie”
- Progressivo progetto : progressivo da aggiungere la nr. progetto in caso di “Tipo creazione struttura preventivo” = “Progressivo progetto”. Il campo è lungo 3 caratteri e può essere alfanumerico, l’importato che l’ultimo carattere sia un numero (es. V00)
- Template struttura preventivo : codice template da applicare alla struttura preventivo generata, se il campo è vuoto non viene applicato nessun template
- Tipo creazione struttura costruzione : indicata come deve essere creato il il numero della struttura progetto di tipo costruzione (creata da ordine di vendita). Questo campo ha i seguenti valori
1. Nr. Serie : per la creazione di una struttura costruzione viene usato il nr. Serie indicato nel campo “Nr. Struttura costruzione”
2. Progressivo costruzione: per la creazione di una struttura costruzione il numero sarà formato da “Nr. Progetto” + ‘ – ‘ + più un progressivo (es. PROG001-C01)
3. Seriale : per la creazione di una struttura costruzione il numero sarà uguale al nr. di serie indicato in riga ordine di vendita
- Nr. Struttura costruzione: nr. serie da utilizzare in caso di “Tipo creazione struttura costruzione” = “Nr. Serie”
- Progressivo costruzione: progressivo da aggiungere la nr. progetto in caso di “Tipo creazione struttura costruzione” = “Progressivo progetto”. Il campo è lungo 3 caratteri e può essere alfanumerico, l’importato che l’ultimo carattere sia un numero (es. V00). Ad esempio, se si utilizza il codice TEST2, se la commessa ha come codice PROG001, la prima struttura di costruzione creata avrà codice PROG001-C01, la seconda PROG001-C02, la terza PROG001-C03 e così via
- Template struttura costruzione: codice template da applicare alla struttura costruzione generata, se il campo è vuoto non viene applicato nessun template

Per il “Tipo creazione struttura costruzione” = Seriale  sono stati applicati i seguenti vincoli :

1. È possibile utilizzare un codice creazione con “Tipo creazione struttura costruzione” = Seriale  solo a setup è impostato il flag “Nuovo struttura per riga vendita”

![image](https://github.com/user-attachments/assets/ef467bf1-e066-48b5-9219-ae9394ac4e84)
![image](https://github.com/user-attachments/assets/2092d3d1-4c5e-4b16-b907-1ac05a769826)

2. Non è possibile utilizzare un codice creazione con “Tipo creazione struttura costruzione” da Progetto ma solo da ordine di vendita

![image](https://github.com/user-attachments/assets/f2cf8153-bd55-4be3-a6cc-0ff61388af6f)

3. Non è possibile utilizzare un codice creazione con “Tipo creazione struttura costruzione” per righe vendita con quantità maggiori di 1, ovvero con più seriali

![image](https://github.com/user-attachments/assets/d8b92ba1-0549-4c38-adfd-a0daefc64b55)

Per attivare la creazione assistita occorre indicare sull’offerta/ordine di vendita o sulla commessa il “Codice creazione assistita progetti” che si vuole utilizzare. 
Se si indica un codice allora il nr. progetto / struttura verrà generato secondo le regole indicate per quel codice. Se il codice non è indicato allora la creazione dei nr. commessa/struttura seguità il flusso standard

![image](https://github.com/user-attachments/assets/9a561272-d8be-44d4-93bd-258756139eec)

Se la struttura progetto viene creato da Offerta vendita allora verrà utilizzata la logica indicata nei campi “Preventivo” della tabella “Creazione assistita progetto”
Se la struttura progetto viene creato da Ordine vendita allora verrà utilizzata la logica indicata nei campi “Costruzione” della tabella “Creazione assistita progetto”
Se la struttura progetto viene creato da Progetto verrà chiesto all’utente se la struttura deve essere di preventivo o costruzione

![image](https://github.com/user-attachments/assets/66eee0c4-037f-45ca-9339-77e8707f659d)

Se viene creata una struttura di tipo Preventivo, l’utilizzo viene impostato su “Vendita”, invece se viene creata una struttura di tipo Costruzione l’utilizzo viene impostato su “Costruzione”

**Comment by Roberto-Lucarelli-EOS** [comment]
Le modifiche sono contenute nelle seguenti versioni
EX090 MODUS M365 Job Structure 23.0.23.0
EX090 MODUS M365 Job Structure 24.0.23.0
EX090.04 Engineering to order 23.0.29.0
EX090.04 Engineering to order 24.0.22.0
