### ISSUE TITLE
App ETO: Job schedule list (WI 14388)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#276]
L'obiettivo è fare in modo che tutti i clienti ETO possano visualizzare le righe della pianificazione di commessa e struttura per avere così una panoramica dello stato delle attività.

Predisporre una pagina di tipo lista che mostri le righe di Job Schedule (M365 Job Schedule Line (5130126)).
Colonne da visualizzare: 
- Commessa, struttura di commessa
- dettagli della riga Job Schedule
- stato commessa standard
- stato struttura standard

Action da includere:
- Apertura della commessa
- Apertura della struttura di commessa
- Apertura della pianificazione collegata alla riga selezionata (di commessa o di struttura a seconda del tipo riga)

La pagina deve essere filtrabile ed esportabile in Excel e deve essere possibile attivare lo strumento Analisi.

Se attivi, data security di commessa e di struttura.

**Comment by Roberto-Lucarelli-EOS** [comment]
Creata page "Righe pianificazione commessa" (Righe pianificazione progetto in BC24)
La page mostra tutti i record della tabella M365 Job Schedule Line (5130126)

Oltre ai record della tabella sono stati aggiunti i campi:
- Stato commessa (Stato progetto in BC24) : mostra il valore del campo Stato della scheda commessa/progetto
- Stato struttura commessa (Stato struttura progetti in BC24) : mostra il valore del campo Stato della struttura commessa/progetto

![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/9bab9491-8c40-45f5-bba3-62399852d34f)

Nella page sono state aggiunte le seguenti action:
- Commessa (Progetto in BC24) : permette di aprire la scheda della commessa/progetto della riga selezionata
- Struttura commessa (Struttura progetto in BC24) : permette di aprire la struttura commessa/progetto della riga selezionata
- Pianificazione commessa (Pianificazione progetto in BC24) : permette di aprire la pianificazione collegata alla commessa/progetto della riga selezionata
- Pianificazione struttura commessa (Pianificazione struttura progetto in BC24) : permette di aprire la pianificazione collegata alla struttura commessa/progetto della riga selezionata

![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/ce12a3c1-f16a-40a4-8ecd-01b988531ad7)

Le actions "Struttura commessa" e "Pianificazione struttura commessa" sono abilitate solo se la riga selezionata è relativa ad una pianificazione di struttura (campo "Nr. struttura commessa" popolato)

![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/c44120b5-5af3-4a61-aa5c-c40aefc187d2)

La pagina è filtrabile ed esportabile in Excel ed è possibile attivare lo strumento Analisi

Su questa page non è presente il Data Security e se sul cliente è attivo le factbox andranno aggiunte come custom. Così come avviene ora per le commesse e strutture commessa 

NOTA: in BC24 la page è comunque ricercabile anche indicando "Righe pianificazione commessa" 

![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/acc1ee23-4286-4798-b078-7d68ed5b23d3)

La page è contenuta nelle seguenti versioni:
EX090.04 Engineering to order 23.0.23.0
EX090.04 Engineering to order 24.0.16.0
