### ISSUE TITLE
EOS Product Configurator (CFG): Web interface

### ISSUE THREAD

**Issue by MartinSchnurrKUMAVISION** [EOS-Solutions/IDEAS#277]
We have customers/prospects who ask us about a web interface.

To the best of our knowledge, such an interface has already been implemented on a project-specific basis.

I plan to integrate such an interface (standard, web neutral) into the product?

**Comment by AndreaDiCeglie** [comment]
Long terms plan are only to expose API, not to deliver an out of the box Web interface. We shall maybe plan this in future but is not a prior goal at this time
P.S.
BC has already a web interface, any other web client interface is a custom scope

**Comment by MartinSchnurrKUMAVISION** [comment]
correct, it's about API availability
