### ISSUE TITLE
EOS Data Security - Creazione di un campo fisico contenente il codice percorso cambi stato Data Security

### ISSUE THREAD

**Issue by Federico-Perucca-EOS** [EOS-Solutions/IDEAS#278]
La richiesta è quella di creare un campo fisico contenente il codice percorso cambi stato Data Security sulle tabelle in cui il Data Security è attivo.
In sostanza, si richiede di fare un qualcosa di molto simile a quanto già fatto, sempre nelle tabelle in cui il Data Security è attivo, con il campo fisico contenente il codice stato Data Security corrente, e cioè associato in quello specifico momento al documento.

Si tratta di una richiesta fatta, oltre che nell'ottica migliorativa generale del modulo EDS, nell'ottica di velocizzare l'eventuale ricerca del percorso EDS da codice AL.
Ad oggi, infatti, l'unico modo che ho trovato per prendere da codice AL il percorso EDS legato ad uno specifico documento è quello di prendere un suo movimento "a caso" nella vecchia tabella di log _18122153 "EOS DS Status Transaction Log"_.
E immagino che si debba comunque fare la stessa cosa nella nuova tabella di log  _18122161 "EOS003 Status Trans. Log"_ e che ha la gestione con il SystemID.

_Note:
Immagino che il percorso EDS, a differenza dello stato EDS, una volta che è stato associato ad un documento, non può poi più cambiare.
Se così effettivamente fosse, questa richiesta potrebbe avere ancora più senso dato che il dato, una volta assegnato, non potrebbe poi più cambiare._

**Comment by AndreaDiCeglie** [comment]
Last status is already available on table 18122158 EDS Record Status instead of looking on EDS Trans log
Adding a physicall field on any table managed by EDS is overkilling considering that the EDS path is not changing like status and is not so usefull for end users.

**Comment by Federico-Perucca-EOS** [comment]
Grazie mille @AndreaDiCeglie.
Non avevo tenuto conto della table _18122158 “EDS Record Status”_ (e di quella vecchia chiamata invece _18122150 “EOS DS Record Status”_).
E lì effettivamente la ricerca del percorso è più pulita e immediata che nelle tabelle di Log.
Ho parlato comunque con Elio Cometto circa la possibilità di riuscire a mettere il percorso EDS come campo di tabella attivabile da setup, di modo che se qualcuno, per qualsiasi esigenza, volesse averlo, potrebbe attivarlo a piacimento.
Ma mi rendo conto che si tratta di dettagli, che valutando i pro e i contro e considerando che la vostra visione deve essere più ampia dato che parliamo di un’app generica che è usata da centinaia di clienti, non ne vale la pena.
