### ISSUE TITLE
Modify ADR acronym

### ISSUE THREAD

**Issue by henryefgit** [EOS-Solutions/IDEAS#28]
ADR is the agreement concerning the international carriage of dangerous goods by road (see [ADR](https://www.mit.gov.it/mit/site.php?p=cm&o=vd&id=3689)), a topic dealt with several customers.
I suggest to modify "Advanced Document Reporting" acronym.

**Comment by AndreaDiCeglie** [comment]
After evaluating impact on existing deliverables and projects the request has been rejected
