### ISSUE TITLE
Stampa di Enasarco trimestrale

### ISSUE THREAD

**Issue by AG1GA** [EOS-Solutions/IDEAS#280]
Abilitare il filtro della data per la stampa di contributi Enasarco: si dovrebbero filtrare i movimenti di Enasarco anche per il trimestre.

**Comment by AndreaDiCeglie** [comment]
“La stampa non può essere modificata per la richiesta in oggetto; valuteremo l’opportunità di produrre un report trimestrale in modo diverso, coinvolgendo il competence circle.”

**Comment by Yuri-Giacchetto-EOS** [comment]
@AG1GA, come discusso in call, ti chiediamo di fare un passaggio con Lorenzo Trepan responsabile del CC per l'APP in questione.
Io l'ho già avvisato, attendiamo l'esito della vs. analisi
Grazie Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Come da indicazioni da parte del CC le best practice suggerite sono le seguenti:
 
- Estrazione Excel della tabella “Movimenti contributi (CMS)” filtrabile per periodo
- Oppure, è possibile utilizzare la funzione “Distinta contributi (CMS)” nella quale possono essere suggeriti i movimenti Enasarco per periodo da tale distinta è poi possibile estrarre il file “grandi ditte” nel caso in cui si superino i 100 agenti altrimenti può essere utilizzata (senza estrazione del file) a solo scopo informativo, come farebbe un’eventuale stampa.
 
![thumbnail_image003](https://github.com/EOS-Solutions/IDEAS/assets/100839302/6446dd64-c027-475f-b437-07d981813eb3)

La ENASARCO Minimal Calculation non viene più utilizzata in quanto con l’app CMS il calcolo delle integrazioni viene effettuato direttamente in fattura di acquisto e non è più necessario che venga utilizzata.

**Comment by AG1GA** [comment]
Ho trovato la soluzione migliore utilizzando la funzione “analizza” nella pagina dei movimenti contributi (CMS).
***@***.***


***@***.***

***@***.***

***@***.***

***@***.***


Agne Galinskaite
BC Consultant
EOS Solutions
Mail + Teams: ***@***.***
P:+390471319650
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
Die Information in dieser e-Mail ist nur für den oder die angegebenen Adressaten bestimmt. Der Inhalt (inklusive sämtlicher Anlagen) ist vertraulich und persönlich. Wenn Sie nicht einer der Adressaten der Nachricht sind, dürfen Sie die enthaltenen Informationen nicht benutzen, veröffentlichen, verbreiten, kopieren oder drucken. Wenn Sie diese Nachricht auf Grund eines Fehlers erhalten haben, bitten wir Sie, den Sender darüber zu informieren und die Nachricht und alle davon erstellten Kopien aus Ihrem System zu löschen.

Da: Yuri Giacchetto ***@***.***>
Inviato: lunedì 15 aprile 2024 14:38
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Agne Galinskaite ***@***.***>; Mention ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] Stampa di Enasarco trimestrale (Issue #280)


Come da indicazioni da parte del CC le best practice suggerite sono le seguenti:

  *   Estrazione Excel della tabella “Movimenti contributi (CMS)” filtrabile per periodo
  *   Oppure, è possibile utilizzare la funzione “Distinta contributi (CMS)” nella quale possono essere suggeriti i movimenti Enasarco per periodo da tale distinta è poi possibile estrarre il file “grandi ditte” nel caso in cui si superino i 100 agenti altrimenti può essere utilizzata (senza estrazione del file) a solo scopo informativo, come farebbe un’eventuale stampa.

thumbnail_image003.png (view on web)<https://github.com/EOS-Solutions/IDEAS/assets/100839302/6446dd64-c027-475f-b437-07d981813eb3>

La ENASARCO Minimal Calculation non viene più utilizzata in quanto con l’app CMS il calcolo delle integrazioni viene effettuato direttamente in fattura di acquisto e non è più necessario che venga utilizzata.
