### ISSUE TITLE
CMS - App Commissioni - Filtro Gruppo Prodotti in Setup Calcolo Commissioni

### ISSUE THREAD

**Issue by BlackNovaItalia** [EOS-Solutions/IDEAS#281]
Sarebbe ottimo  se il campo per filtrare il gruppo prodotti, ora limitato a 20 caratteri, potesse essere esteso in modo da accogliere filtri più complessi.

**Comment by AndreaDiCeglie** [comment]
Il campo "filtro gruppo prodotti" nella tabella in oggetto in realtà non è un campo di tipo "FILTER" ma accetta un solo codice. di conseguenza la sua dimensione deve essere uguale e coerente con il campo "gruppo prodotti" in anagrafica articolo.

Per vincoli di compatibilità con il continuous upgrade imposto dalla piattaforma non ci è comunque possibile  modificare le dimensioni dei campi. Questo richiede l'aggiunta di un nuovo campo mentre si rende obsoleto il vecchio campo.
In questo specifico caso si tratta di un campo della primary key e questo comporta una modifica molto importante e sopratutto di grosso impatto sul parco installato e relative customizzazioni.

**"Product Commission Group Code"** è un campo dedicato ad uso esclusivo delle provvigioni , si intende da usare in caso di raggruppamenti  impostandolo uguale sugli articoli che condividono una certa politica provvigionale non sovrapponendolo 1:1 al **"product group code"** standard
