### ISSUE TITLE
ETC: poter calcolare i Costi di Trasporto per riga documento o sui Gruppi delle Spedizioni Warehouse (WI14397)

### ISSUE THREAD

**Issue by matteodegiovanni** [EOS-Solutions/IDEAS#282]
La richiesta principale è quella di poter calcolare i costi di trasporto a livello di "Righe Ordine".
Spesso i clienti devono calcolare i preventivi di una spedizione (per avere idea dei costi o per capire a che spedizioniere affidarsi) basandosi su quella che dovrebbe essere la spedizione che faranno.
La spedizione può però racchiudere più righe di più ordini diversi (e di un singolo ordine potrebbe riguardare un set di righe, non tutte).

Capendo la difficoltà di calcolare i Costi di Trasporto per Riga, propongo 2 soluzioni.
La prima: permettere di calcolare i Costi per Documento passando una temporanea che su ogni progetto ci possiamo costruire come vogliamo (senza quindi basarsi sulla RecRef e senza quindi essere vincolato da uno specifico documento, ma costruendocela come vogliamo - es. raggruppata per cliente, indirizzo di destinazione, resa, data spedizione, ecc.)

La seconda : poter calcolare i Costi di Trasporto per i gruppi delle Spedizioni Warehouse.
In questo modo sarei sicuro di avere i parametri di partenza/arrivo uguali per gruppo; sui gruppi sono già presenti le informazioni di peso lordo/peso netto/volume/km/orari.
Inoltre potrei, creando correttamente la Spedizione Warehouse, avere un'idea del calcolo dei costi di trasporto per il set di righe di ordini diversi che mi servono.
Questa soluzione potrebbe intersecarsi meglio anche con l'app dei piani giro

Grazie

**Comment by AndreaDiCeglie** [comment]
Valuteremo la seconda ipotesi: poter calcolare i Costi di Trasporto per i gruppi delle Spedizioni Warehouse.
La prima ipotesi risulta incompatibile con l'attuale code base

**Comment by Mariangela-DeMaio-EOS** [comment]
Rilasciate le seguenti versioni delle app
"Transport Costs"
23.0.26
"Combine warehouse shipment"
23.0.46

Sui gruppi CWS della spedizione warehouse è stata aggiunta l'azione "Suggerisci costi di trasporto per gruppo", che consente di calcolare i costi di tutti gli spedizionieri per i gruppi selezionati. L'azione è abilitata se, sul setup dei costi di trasporto, l'origine dei parametri ha come valore "CWS".
