### ISSUE TITLE
Fatturazione Elettronica - Gestione automatica di un codice SDI specifico per Indirizzo di Spedizione

### ISSUE THREAD

**Issue by LorenzoIanna** [EOS-Solutions/IDEAS#283]
Esiste la possibilità che differenti indirizzi di spedizioni per un cliente abbiamo differenti codici sdi a cui inviare la fattura elettronica.

Richiedo la possibilità di inserire automaticamente il codice.

Creando un campo negli indirizzi di spedizione dove inserire il codice sdi, un campo in anagrafica cliente nel tab del documento elettronico per attivare la gestione.
Alla validate dell'indirizzo di spedizione se il campo è valorizzato inserirlo altrimenti vale quello presente in anagrafica cliente

**Comment by AndreaDiCeglie** [comment]
Premesso che:
I Codici SDI per un cliente possono essere diversi (è già possibile farlo ad esempio per le PA e i loro codici ufficio)
Per una fattura può esserci solo un codice SDI
Per una fattura ci possono essere "N" indirizzi di spedizione
concludiamo che

Questa soluzione potrebbe quindi funzionare solo se gli indirizzi di spedizione (merce) sono criteri di raggruppamento per la fattura.

Consiglierei di gestire la cosa come custom perchè non sembra applicabile in molti scenari e potrebbe indurre ad un utilizzo improprio.

**Comment by LorenzoIanna** [comment]
Grazie per il feedback



Saluti

***@***.***


LORENZO IANNACI | OPERATION CONSULTANT
***@***.******@***.***>
M. 388 7707138 | T. 0731 616021

LOGICAL SYSTEM SRL
VIALE DELL’INDUSTRIA, 50 - 60035 JESI (AN)
WWW.LOGICALSYSTEM.IT<http://WWW.LOGICALSYSTEM.IT>



[Immagine che contiene testo  Descrizione generata automaticamente]



AVVISO DI RISERVATEZZA - Questa e-mail è inviata da o per conto di Logical System Srl ed il suo contenuto è rivolto unicamente alle persone o enti in indirizzo. Essa può contenere informazioni la cui riservatezza è tutelata. Sono vietati la riproduzione e qualsiasi uso di questa e-mail e/o delle informazioni in essa contenute in mancanza di autorizzazione del destinatario. Le informazioni trasmesse attraverso la presente e-mail ed i suoi allegati sono dirette esclusivamente al destinatario e devono ritenersi riservate con divieto di diffusione salva espressa autorizzazione. La diffusione e la comunicazione da parte di soggetto diverso dal destinatario è vietata dall'art. 616 e ss. c.p. e dalle vigenti norme in materia di protezione dei dati personali. Se la presente e-mail ed i suoi allegati fossero ricevuti per errore da persona diversa dal destinatario, Logical System Srl richiederebbe di distruggere tutto quanto ricevuto e di informare il mittente con lo stesso mezzo. Tel. 0731 616021 - Fax 0731 605943 - Email: ***@***.******@***.***>
This e-mail (including attachments) is intended only for the recipient(s) named above. It may contain confidential or privileged information and should not be read, copied, or otherwise used by any other person. If you are not the named recipient, please contact us and delete the e-mail from your system.
INFORMATIVA SUL TRATTAMENTO DEI SUOI DATI PERSONALI (art. 13 Reg. UE 679/2016) Il Suo indirizzo di posta elettronica è stato acquisito ed è utilizzato da Logical System Srl esclusivamente per finalità di comunicazione diretta e in genere del rapporto professionale intrattenuto. I dati personali contenuti nei messaggi di posta elettronica in uscita e in entrata possono essere trattati, esclusivamente a fini tecnici, anche da società informatiche terze delle quali Logical System Srl utilizza i servizi. Poiché spesso tali società hanno i loro server in Europa e negli Stati Uniti, i dati personali possono essere trasferiti sia verso Paesi dell’Unione Europea che verso paesi terzi, comunque nel pieno rispetto di quanto prescritto dalle norme in materia di Trasferimento dei Dati all'estero. Nel caso in cui Lei desiderasse che il Suo indirizzo di posta elettronica sia rimosso dal nostro archivio, ovvero per l'esercizio dei diritti di cui all'art. 15 e ss del suddetto Regolamento può scrivere al Titolare del trattamento, Logical System Srl con sede legale in Viale Dell’Industria 50, 60035 JESI (AN). L' Informativa Privacy completa è disponibile a questo link<https://www.logicalsystem.it/it/privacy>





Da: Andrea Di Ceglie ***@***.***>
Inviato: mercoledì 28 febbraio 2024 15:49
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Lorenzo Iannaci ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] Fatturazione Elettronica - Gestione automatica di un codice SDI specifico per Indirizzo di Spedizione (Issue #283)

Questa è la prima volta che ricevi un'email da questo mittente. Assicurati che sia qualcuno di cui ti fidi.

Premesso che:
I Codici SDI per un cliente possono essere diversi (è già possibile farlo ad esempio per le PA e i loro codici ufficio)
Per una fattura può esserci solo un codice SDI
Per una fattura ci possono essere "N" indirizzi di spedizione
concludiamo che

Questa soluzione potrebbe quindi funzionare solo se gli indirizzi di spedizione (merce) sono criteri di raggruppamento per la fattura.

Consiglierei di gestire la cosa come custom perchè non sembra applicabile in molti scenari e potrebbe indurre ad un utilizzo improprio.

—
Reply to this email directly, view it on GitHub<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F283%23issuecomment-1969147741&e=4641458d&h=34ddeea5&f=y&p=n>, or unsubscribe<https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FBGMVYKOYMJMILOCJYUUZ7ELYV47WRAVCNFSM6AAAAABDWZSOJCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSNRZGE2DONZUGE&e=4641458d&h=f918a689&f=y&p=n>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

--
Messaggio analizzato da Libraesva ESG.
Segnala come malevolo/spam.<http://srvesva02.logsys.intra/action/4TlHLL0G1Vz1xng/submit-as-bad>
Mettilo in blocklist.<http://srvesva02.logsys.intra/action/4TlHLL0G1Vz1xng/blocklist>
