### ISSUE TITLE
EX046 Purchase Request extension Attachments not copying to PO

### ISSUE THREAD

**Issue by CSSAlberta2024** [EOS-Solutions/IDEAS#284]
**Is your feature request related to a problem? Please describe.**

See Issue number: EOS:0262000000735
re:  EX046 Purchase Request extension Attachments not copying to PO.

When a Purchase Order is created from a Purchase Request Document Attachments are copied. However the EOS customization is not copying over any Notes and Links attachments.

All Attachments linked to PRQ should also be copied into any POs created.

**Comment by AndreaDiCeglie** [comment]
Hello, 

AFAIK standard BC codes is not copying attachments and link from a document (I.E sales quote or sales order to shipment / invoices) and the purchase request app is following the same pattern.

We also have an attachment solution called DocSolutions for sharepoint that is implementing this pattern for sales and purchase documents (standards) and also for purchase request

**Comment by CSSAlberta2024** [comment]
Thanks for reaching out,

However we do not use sharepoint as our repository (security is too lax) and instead use native BC storage so we can restrict access and privileges to stored documents based on user profiles.

**Comment by AndreaDiCeglie** [comment]
Hi,

"However we do not use sharepoint as our repository (security is too lax) : "
Using DocSolutions you can grant access to user / user groups at table level. No need to grant user to access sharepoint (it's an app to app connection)
