### ISSUE TITLE
(SGL) Add start date, end date , templates on pages Page Sales Lines (516) and Posted Sales Invoice (132, Document) (WI 14610)

### ISSUE THREAD

**Issue by AndreaDiCeglie** [EOS-Solutions/IDEAS#285]
Pages,

Posted Sales Invoice Lines (526, List)
Posted Sales Credit Memo Lines (527, List)

Posted Purchase Invoice Lines (529, List)
Posted Purchase Cr. Memo Lines (530, List)

Cannot be filtered/ordered using fields that are on SGL apps

Evaluate if possible also on EOS App pages due to dependencies limitation
EOS Sales Document Summary (18123706, List)
EOS Purch. Inv. Summary (18123714, List)
EOS Sales Posted Inv Summary (18123708, List)
EOS Purch. Inv. Summary (18123714, List)

**Comment by Roberto-Lucarelli-EOS** [comment]
Added field "EOS Accrual Template", "EOS Accrual Starting Date" and "EOS Accrual Ending Date" on the following list pages:
"Posted Sales Invoice Lines" (526)
"Posted Sales Credit Memo Lines" (527)
"Posted Purchase Invoice Lines" (529)
"Posted Purchase Cr. Memo Lines" (530)

"EOS Sales Document Summary" (18123706)
"EOS Sales Posted Inv Summary" (18123708)
"EOS Sales Posted CM Summary" (18123709)
"EOS Purchase Document Summary" (18123712)
"EOS Purch. Inv. Summary" (18123714)
"EOS Purch. Cr. Memo Summary" (18123715)

![image](https://github.com/EOS-Solutions/IDEAS/assets/160158898/7760cb30-5f05-42ad-ae42-4a5c96740daf)

**Comment by Roberto-Lucarelli-EOS** [comment]
Modifiche presenti nelle seguenti versioni
Accruals and Simulated Common Library 22.0.34.0
Accruals and Simulated Common Library 23.0.29.0
