### ISSUE TITLE
SPP: Gestire lo sconto dettagliato come valore di una regola sconto nella tabella EOS049 Sales Disc. Line - Item (18090665)

### ISSUE THREAD

**Issue by matteodegiovanni** [EOS-Solutions/IDEAS#287]
Attualmente in una regola sconto SPP (tabella EOS049 Sales Disc. Line - Item (18090665)) è possibile inserire solo un valore di sconto decimale.
Se la regola di quella specifica fascia, però, è 30+25, non è possibile farlo (se non inserendo 2 righe con gestione delle esclusività).
La regola 30+25 però non è l'unione di 2 sconti diversi ma è proprio una fascia sconto (una regola) che deve essere messa "secca" 30+25.

La richiesta, quindi, è di poter gestire lo sconto dettagliato (o il vecchio Sconto riga (T)) che poi mi diventa un valore decimale, già nella creazione della specifica regola di sconto

![07-03-2024 18-03-04](https://github.com/EOS-Solutions/IDEAS/assets/158561531/4cb4a459-179e-4c71-be43-d4eeb36ee15b)

**Comment by AndreaDiCeglie** [comment]
Hi Matthew, 

Since the request modification is complex and highly impacting must be discussed before with the responsible CC. Then the CC can directly discuss the CR with the development team.
