### ISSUE TITLE
MDI - Conti C/G Principali (WI 14616)

### ISSUE THREAD

**Issue by ErikaQgs** [EOS-Solutions/IDEAS#288]
La CONTI C/G PRINCIPALE  consente di attivare i conti sulle società slave , di gestire una descrizione differente " ma per il commercialista".

Si richiede che vi sia la possibilità di inserire descrizioni differenti come campo DESCRIPTION ( perchè accade spesso Es. conto Cassa contanti o carte di credito ) in cui il conto è lo stesso ma il nome è differente.

**Comment by Stefano-Primo-EOS** [comment]
Questa funzionalità può essere gestita in modi diversi: 
 - Aggiungere un campo custom e sincronizzare quello (aggiungendolo al profilo di sincronizzazione) 
 - L'MDI permette di cambiare il Nome e Nome ricerca dei conti, usando le traduzioni. 

L'aggiunta però di un campo descrittivo all'interno del piano dei conti è "out-of-scope" per l'app in se.
