### ISSUE TITLE
ADR - Traduzione paesi

### ISSUE THREAD

**Issue by jellemundeos** [EOS-Solutions/IDEAS#290]
Ciao,

non va considerato la lingua nell'indirizzo che va stampato sui report ADR.

![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/b9c8efbe-d804-4954-ae36-0df72e0ecd3b)

![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/75fc3d36-e50e-49ca-b1c8-87b903d9a74c)

Con il debugger si vede che nella codeunit "Format Address" nella funzione FormatAddr si vede che la variabile è vuoto anche se la lingua dell'documento che va stampato è compilato.

![image](https://github.com/EOS-Solutions/IDEAS/assets/107125213/49549fb5-037d-4eff-8ef5-63f6526cac02)

**Comment by AndreaDiCeglie** [comment]
Hi Jackob , this seems a bug and should be logged to support service.
