### ISSUE TITLE
Gestione data di validità Materiale CONAI in Scheda Imballo Conai (WI 15020)

### ISSUE THREAD

**Issue by Tomas-eos** [EOS-Solutions/IDEAS#291]
Al fine per adeguare la gestione del CONAI alla normativa in continua evoluzione, si chiede di gestire, al pari dei listini del contributo, le date di validità dei materiali. 
 
Per fare questo è necessario introdurre, nella SCHEDA IMBALLO CONAI, una data di:
		o Inizio validità
		o Fine validità
Da associare al MATERIALE CONAI.
 
Questo perché, per un determinato IMBALLO, possa andare ad indicare che:
	• NON deve essere utilizzato più un determinato MATERIALE (in base alla data di fine validità) 
	• Deve essere utilizzato un nuovo MATERIALE (in base alla data di inizio validità)
 
Ovviamente deve esserci il controllo di non sovrapposizione delle date per le diverse righe dei materiali CONAI.
Si tratta quindi di una modifica alla classificazione del prodotto con cui è prodotto un imballo, che nel tempo varia, e pertanto deve essere gestibile la composizione del MATERIALE.

![image](https://github.com/EOS-Solutions/IDEAS/assets/166011367/35de7e8b-324b-4cc2-9ebc-ddc699d1310c)

Va bene che sia utilizzato, come nella gestione attuale, la data di registrazione del documento (sia per fatture che per note di credito) per determinare la validità o meno del Materiale CONAI.

Se approvata, si richieste entro quando si prevede il rilascio.

grazie
Antonio Tomaselli

**Comment by AndreaDiCeglie** [comment]
Buongiorn Antonio, puoi per cortesia allegare o linkare i riferimenti alle novità normative citate ?

**Comment by Tomas-eos** [comment]
Buongiorno

Chiedo i riferimenti al cliente, e poi vi aggiorno.

grazie


Antonio Tomaselli
BC Senior Finance Consultant
EOS Solutions
Mail + Teams: ***@***.***
P: | Mob: +393499835171
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.

Da: Andrea Di Ceglie (gm) ***@***.***>
Inviato: mercoledì 10 aprile 2024 14:41
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Antonio Tomaselli ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] Gestione data di validità Materiale CONAI in Scheda Imballo Conai (Issue #291)


Buongiorn Antonio, puoi per cortesia allegare o linkare i riferimenti alle novità normative citate ?

**Comment by Tomas-eos** [comment]
Buongiorno

Vi riporto indicazioni fornite dal cliente direttamente nella mail allegata.

grazie


Antonio Tomaselli
BC Senior Finance Consultant
EOS Solutions
Mail + Teams: ***@***.***
P: | Mob: +393499835171
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.

Da: Antonio Tomaselli ***@***.***>
Inviato: giovedì 11 aprile 2024 08:43
A: EOS-Solutions/IDEAS ***@***.***>; EOS-Solutions/IDEAS ***@***.***>; Andrea Di Ceglie ***@***.***>
Cc: Author ***@***.***>
Oggetto: R: [EOS-Solutions/IDEAS] Gestione data di validità Materiale CONAI in Scheda Imballo Conai (Issue #291)

Buongiorno

Chiedo i riferimenti al cliente, e poi vi aggiorno.

grazie


Antonio Tomaselli
BC Senior Finance Consultant
EOS Solutions
Mail + Teams: ***@***.******@***.***>
P: | Mob: +393499835171
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.

Da: Andrea Di Ceglie (gm) ***@***.******@***.***>>
Inviato: mercoledì 10 aprile 2024 14:41
A: EOS-Solutions/IDEAS ***@***.******@***.***>>
Cc: Antonio Tomaselli ***@***.******@***.***>>; Author ***@***.******@***.***>>
Oggetto: Re: [EOS-Solutions/IDEAS] Gestione data di validità Materiale CONAI in Scheda Imballo Conai (Issue #291)


Buongiorn Antonio, puoi per cortesia allegare o linkare i riferimenti alle novità normative citate ?

**Comment by Enrico-Marini-EOS** [comment]
Rilasciata CONAI versioni: 
22.0.36
23.0.39
24.0.18
