### ISSUE TITLE
Ricalcolo CONAI in note di credito impostando la data di riferimento da considerare per il calcolo CONAI (WI 15017)

### ISSUE THREAD

**Issue by Tomas-eos** [EOS-Solutions/IDEAS#292]
Nel programma "Note credito vendita" nella sezione IMBALLO CONAI, o comunque mediante creazione di apposito campo in testata delle note di credito, prevedere un campo per poter inserire una DATA DI RIFERIMENTO 
(inizialmente valorizzata con la data di registrazione della fattura di riferimento da poter impostare se recuperabile) in alternativa impostata con la data di registrazione che comunque potrà essere modificata (a cura dell'utente). 
	 
	Attenzione che l’impostazione di una nuova data, può avere impatto sia:
			a. sul tipo di Materiale di calcolo CONAI
			b. sulla contribuzione CONAI
 
![image](https://github.com/EOS-Solutions/IDEAS/assets/166011367/e4cec7c3-67fd-4628-b82f-756deee554b1)

	Per il calcolo si tratta di utilizzare sempre la data di registrazione del documento (nota di credito)

Questo perchè, se devo emettere una nota di credito che deve stornare un documento, deve essere applicato e stornato il calcolo del CONAI che avevo inserito nel documento di origine (quello della fattura).

**Comment by Enrico-Marini-EOS** [comment]
Rilasciata CONAI versioni:
22.0.36
23.0.39
24.0.18
