### ISSUE TITLE
CONAI: Note di Credito - Controllo inserimento righe CONAI con importo a Zero

### ISSUE THREAD

**Issue by Tomas-eos** [EOS-Solutions/IDEAS#294]
Richiesta dettagliata
Viene richiesto che in fase di inserimento NOTE di CREDITO, analogamente da quanto viene effettuato in fase di inserimento fattura, quando l'import del CONAI è inferiore a 0,01 euro (1 centesimo) non venga proposta la riga CONAI.

Vedi esempio DETTAGLIO CONAI
![image](https://github.com/EOS-Solutions/IDEAS/assets/166011367/bbd85446-d6d7-48bf-ba20-60f69e610b7a)

Vedi proposizione riga

![image](https://github.com/EOS-Solutions/IDEAS/assets/166011367/97ab6237-4fc8-4203-8382-b7d0868b79a0)

Vedi movimenti libri giornale generale e movimenti C/G con riga a zero.

![image](https://github.com/EOS-Solutions/IDEAS/assets/166011367/4f453e62-16f6-43e6-a2b5-52cb593f3746)
![image](https://github.com/EOS-Solutions/IDEAS/assets/166011367/7c9bbc51-7e14-4bcf-9e66-2441c2cbcad2)

**Comment by AndreaDiCeglie** [comment]
Chiusa per mancanza di evidenze
