### ISSUE TITLE
Electronic Invoice for Italy FTE - Filtri campo "Nr. cod. paese" (WI 15011)

### ISSUE THREAD

**Issue by CristianCorega-Lutech** [EOS-Solutions/IDEAS#295]
Buongiorno,
ci siamo accorti che nel “Setup in uscita (FTE)", nei filtri della table relation che si apre dal campo “Nr. campo cod. paese” manca quello relativo alla tabella.
Risulta poco chiara la scelta del campo corretto e si rischia di indicare il campo di una tabella sbagliata.
Potreste cortesemente aggiungere tale filtro?
La versione dell'app verificata è la 23.0.52.0.
Grazie, Cristian

**Comment by Andrea-Tassinari-EOS** [comment]
Implementazione effettuata e rilasciata
