### ISSUE TITLE
EOS Purchase Request Enhancement - BC Standard Text Codes (WI 15014)

### ISSUE THREAD

**Issue by JTAdmBdl** [EOS-Solutions/IDEAS#296]
A clear and concise description of what the problem is:

Currently on a Purchase Order I can select Type as "Comment" which brings up the Standard Text Codes to choose from (image)
The purchase request app doesn't have the functionality to use the Standard Text Codes in native BC.

**Describe the solution you'd like**

I would like another Type "Comment" added to the Lines section, so the purchase request has the ability to use Standard Text Codes.

**Describe alternatives you've considered**
Entering the lines manually takes too much time. Considered using a Purchase Order since the functionality is there.

**Additional context**
![image](https://github.com/EOS-Solutions/IDEAS/assets/154361271/5980d5a2-7149-4563-98a3-e1a699fe64a8)

![PO_Lines_Comment_STC](https://github.com/EOS-Solutions/IDEAS/assets/154361271/67aa3280-62cf-458a-8899-eedb0c4c3612)

**Comment by JTAdmBdl** [comment]
sorry for the duplicate images

**Comment by Roberto-Lucarelli-EOS** [comment]
Comment type has been added and now you can use standard text codes

![image](https://github.com/user-attachments/assets/e8f60d49-22d7-4ccf-a4d9-f8bc6e085687)

For comment type lines you can select a standard text code

![image](https://github.com/user-attachments/assets/17647588-2edb-4519-bdf1-d6dd1a718f94)

the description of the standard text code is reported on the description of the purchase request line

![image](https://github.com/user-attachments/assets/f6f0d976-6785-4c77-9ce7-8211c8b73022)

This change is contained in the following versions of the app
**EX046 Purchase Request 25.0.17.0
EX046 Purchase Request 24.0.29.0**
