### ISSUE TITLE
Add EOS-Fields to Page "Registered Whse. Act.-Lines" (WI 15119)

### ISSUE THREAD

**Issue by MarcusFabian** [EOS-Solutions/IDEAS#297]
pageextension 50266 RegWhseActLines extends "Registered Whse. Act.-Lines"
{
    layout
    {
        addlast(Control1)
        {
            field("EOS055 Handling Unit No."; Rec."EOS055 Handling Unit No.")
            {
                ApplicationArea = All;
            }
            field("EOS051 Sec. UoM Code"; Rec."EOS051 Sec. UoM Code")
            {
                ApplicationArea = All;
            }
            field("EOS051 Sec. Quantity"; Rec."EOS051 Sec. Quantity")
            {
                ApplicationArea = All;
            }
            field("EOS05501 Assignment Source"; Rec."EOS05501 Assignment Source")
            {
                ApplicationArea = All;
                Visible = false;
            }
        }
    }
}

**Comment by Enrico-Marini-EOS** [comment]
Released EX055.01 Advanced Logistic CDL. Versions: 
23.0.43
24.0.19
