### ISSUE TITLE
EDI - Path archiviazione messaggi (WI 15113)

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#298]
Se metto il "Cancella Dati Letti" sul "Setup Messaggi EDI", il file non lo trovo più da nessuna parte, non viene archiviato in nessuna path, come lo recupero?
sul verticale foodvision era presente una path di archiviazione
![image (4)](https://github.com/EOS-Solutions/IDEAS/assets/38073933/b2e34f6b-a914-49a1-9db3-35b3d7a44d49)

Ad oggi se viene messo il flag di cancella, il file viene cancellato dalla path (nel mio caso su azure file storage), ma sulla tabella EDI File ho il record che punta ad una path in cui non è più presente il file, per cui, se si tenta di utilizzare l'azione "Apri", viene restituito l'errore sotto
![2](https://github.com/EOS-Solutions/IDEAS/assets/38073933/617c7122-40f3-4edf-9698-aebc18c4faf3)
![3](https://github.com/EOS-Solutions/IDEAS/assets/38073933/7bf020d5-0b46-47b9-aed4-d4e4e0acb1c0)

Spesso nei clienti onPrem che hanno EDI nelle vecchie installazioni, senza FoodVision(altrimenti era già previsto), veniva inserito custom il campo "Path di archiviazione" e gestito nel xml port di import o nel report di import.

**Comment by Edoardo-Rossi-EOS** [comment]
E' stata aggiunta la possibilita di impostare un archivio nella pagina Setup Messaggio EDI
