### ISSUE TITLE
EX003 EDS Add the possibility to associate to a document the path to the 'validate' of a Responsibility Center, if not yet assigned (WI 7039)

### ISSUE THREAD

**Issue by PaoloCarimati** [EOS-Solutions/IDEAS#3]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndreaDiCeglie** [comment]
Adding a new table for Mapping Document classes to EDS Path.
If more than path is mapped to one document class user must select the path
If only path is mapped to one document class user cannot select other path
In not path are mapped to one document class all path can be selected

**Comment by AndreaDiCeglie** [comment]
Rejected
