### ISSUE TITLE
App MES : Storno parziale di un movimento dipendenti mes (e relativi movimenti di capacità) già registrato (WI 15262)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#302]
Al momento è possibile stornare completamente un movimento.
Nel caso di errori da parte dell'operatore per fine attività in ritardo , avendo solo lo storno completo non è possibile assegnare il corretto tempo alla lavorazione. 
Servirebbe una azione che permetta lo storno del movimento errato e la creazione del movimento corretto. 
Modo d'uso 
Si seleziona un movimento 
Si apre una pagina dove indicare la durata tramite data ora inizio,  data ora fine.  
La funzione deve stornare il movimento originale, creare un nuovo movimento come se dal mes si fosse iniziate un'operazione alla data ora inizio e finita alla data ora fine. 
Mantenere i collegamenti 

Lo storno e la scrittura come ora devono rispettare i parametri se è stato registrato il movimento capacità deve essere stornato e registrato se previsto da setup .

**Comment by Giuliano-Velludo-EOS** [comment]
Rilasciate versioni 23.0.50 24.0.33
