### ISSUE TITLE
Product Configurator with Jobs

### ISSUE THREAD

**Issue by JTAdmBdl** [EOS-Solutions/IDEAS#303]
1. When configuring from a job I would like to see the configurator write back the Unit Price from the configurator statistics to the item card “Unit Price” field. If the item is configured for a job and later used on a Sales Order, that item would have the unit price captured from when it was configured for the job.

2. It would be nice to see the “Derived From” portion of the configurator window show the job/project details like it does for a Sales Order. Attached are two files that show the "Derived From" on a Job being blank & it being populated when configuring on a Sales Order. Below are some suggestions that I would like to see:

Document Type: Job
Document No: Job No.
Document Line No: Job Planning Line No.
And add a similar field for Job Task No.

![JobConfig_DerivedFrom](https://github.com/EOS-Solutions/IDEAS/assets/154361271/fec267eb-c545-43c9-baef-54df1ad11506)
![SOConfig_DerivedFrom](https://github.com/EOS-Solutions/IDEAS/assets/154361271/85d37891-f45e-4f64-bf6b-7c9c5e863c0a)

**Comment by Giuliano-Velludo-EOS** [comment]
Hi, the first request has been developed.
For the second one  you can add to the page these fields:
![image](https://github.com/user-attachments/assets/b42507f8-fd27-44b5-85ae-7e09f6084133)
