### ISSUE TITLE
EBR: Riconciliazione pagamenti 

### ISSUE THREAD

**Issue by GiusyViola** [EOS-Solutions/IDEAS#304]
Buongiorno,
il cliente xxxx segnala che sulle righe dei movimenti c/g derivanti da collegamenti manuali a più fatture clienti non è presente la ragione sociale del cliente nel campo descrizione, a differenza dei movimenti generati da collegamenti automatici su unica fattura
![Immagine1](https://github.com/EOS-Solutions/IDEAS/assets/170622393/1212b141-d506-4b94-bf92-f770be0933c6)

Ho notato che nella registrazione riconciliazione pagamenti, quando si collega manualmente il pagamento a più documenti del cliente, indica la descrizione ‘Il pagamento è stato collegato a 2 movimenti’. Mentre sulle altre righe inserisce la ragione sociale del cliente:

![Immagine2](https://github.com/EOS-Solutions/IDEAS/assets/170622393/d0e577dd-ac57-4b46-9b7c-9418ebf0e69d)

E’ possibile uniformare il comportamento e compilare sempre la descrizione con la ragione sociale del cliente?
Nel campo contropartita è già presente il codice del cliente.
 
Resto a disposizione per chiarimenti
 
Buona giornata

**Comment by AndreaDiCeglie** [comment]
Both behaviour descripted are managed by Microsoft in Standard BC implementation and not i scope for EOS Extended Bank Reconciliation.
