### ISSUE TITLE
Errore importazione anagrafiche e scadenzari in DocFinance

### ISSUE THREAD

**Issue by GG-CONSEA** [EOS-Solutions/IDEAS#305]
A seguito di attivazione di autenticazione mfa, lato BC l'accesso viene effettuato correttamente. Accedendo a doc finance per l'importazione delle anagrafiche e degli scadenzari si ottiene l'erroreallegato.
![err](https://github.com/EOS-Solutions/IDEAS/assets/171261846/3d933228-50a5-4bc9-8620-00c459b31137)

**Comment by AndreaDiCeglie** [comment]
This is an errore probably due to bad configuration or network erros, is not suitable for Change request or new suggestion
