### ISSUE TITLE
EDI - EDI Values - Già gestiti (WI 15333)

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#306]
Report di out gira sempre tutte le edi values.

Mi vengono in mente 2 possibilità per snellire questa ciclo:
1. flag su gruppo o messaggi EDI, cosicchè dopo aver creato il file, venga eliminata la edi values
2. Aggiungere un campo nella EDI Values ("messaggio creato") cosicchè dopo aver creato il messaggio venga flaggato e il report giri solo per le edi values non flaggate.

**Comment by Edoardo-Rossi-EOS** [comment]
E' stata aggiunta la possibilità di ignorare i documenti che già possiedono un messaggio EDI tramite un nuovo flag nella pagina Setup Messaggio EDI
