### ISSUE TITLE
CDW: Riapertura movimento chiuso

### ISSUE THREAD

**Issue by danielwegleiter** [EOS-Solutions/IDEAS#307]
Implementare una funzione nei movimenti chiusi documento che permetta di riaprire un riga chiusa con CDW in maniera da poterla fatturare.

![image](https://github.com/EOS-Solutions/IDEAS/assets/108135945/59ea3fb7-32cc-438b-be02-d06211c9ad0f)

**Comment by AndreaDiCeglie** [comment]
can't be done
