### ISSUE TITLE
ETO: Integration with Product Configurator (WI 15628)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#310]
Integrare Product Configurator con ETO in modo che:
- gli articoli vengano configurati vengano esplosi nelle strutture di commessa
- dalla struttura di commessa sia possibile aprire il configuratore per creare/configurare e, quindi, riportare in riga
Riprendere le funzionalità già applicate in passato su NAV.

**Comment by Giuliano-Velludo-EOS** [comment]
Queste le considerazioni si Simone Grassi in merito:
I punti sono 2 
•	Esecuzione del configuratore dalla struttura di commessa eto 
•	Funzione di copia della struttura di variante in struttura eto (da verificare) 

Punto 1 
Dalla struttura di commessa bisogna eseguire il configuratore di prodotto. 
Come per una riga di documento,  o per una riga di commessa (standard righe pianificazione) , bisogna eseguire il configuratore, se è un articolo da neutro a configurato al validate dell’articolo, e aggiungere una action
Se la configurazione è per variante verrà valorizzato il campo variante altrimenti solo l’articolo. (come sempre) 
Valutare se aggiungere qualche action di visualizzazione info del configuratore 

Punto 2 
La copia struttura eto legge sicuramente la bom standard.  Matteo verifica se, la copia, tiene conto della gestione delle diba e cicli su sku  per variante.   
In questo caso si può pensare di allineare la gestione della struttura di variante cfg a quella standard e poi eseguire la copia. 
In alternativa bisogna modificare la funzione di copia struttura per leggere, in caso di gestioni a varianti, la struttura variante dell’app cfg 

Visto che l’intervento è circoscritto ed efficace così.  Io lo metterei nello standard.
