### ISSUE TITLE
Implementare la parte passiva dei piani di fatturazione personalizzati

### ISSUE THREAD

**Issue by vanessaEOS** [EOS-Solutions/IDEAS#313]
Ad oggi l’app IPL permette la gestione di un piano di fatturazione dal punto di vista delle vendite, ma sarebbe utile poter creare e gestire un piano di pagamenti personalizzati anche lato acquisti.

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao @vanessaEOS ,
come anticipato via mail al momento non è prevista l'implementazione della parte passiva dell'APP IPL.

A questo link trovi tutta una serie di APP Custom che però possono essere "riutilizzate" dalle altre delivery :
https://eossolutionsspa.sharepoint.com/:x:/s/EOSMI/EYwRz8j-GJFBmoGrwgXNuP4BTntLOMdjqjGIZUs9QJq1-A?email=vanessa.ferraro%40eos-solutions.it&e=5kkI9Z

Qua vedi che per Tamini e Snam è già stata sviluppata una custom per Piani di fatturazione lato acquisti.
Puoi chiedere a Matteo de Giovanni quando sarà disponibile in SCT per poter prendere spunto per il tuo progetto

Grazie e buona giornata,
Yuri

**Comment by vanessaEOS** [comment]
Ciao @Yuri-Giacchetto-EOS,

grazie per le informazioni.

Buona giornata,
Vanessa
