### ISSUE TITLE
FTE - Implementare gestione tipi documento TD su Setup Registrazioni IVA

### ISSUE THREAD

**Issue by THOMAS-CICOLINI-EOS** [EOS-Solutions/IDEAS#314]
Issue:
Il TD della fattura elettronica, in particolare nella parte di integrazione/autofattura acquisti, è dipendente sia dal fornitore da cui acquisto, sia dal tipo di merce/servizio acquistato. Pertanto, sarebbe preferibile spostare la gestione dei TD dalle "Cat. reg. business IVA", dove è presente il campo Tipo documento di default, a un incrocio tra "Cat. reg. business IVA" e "Cat. reg. articolo/servizio IVA"

Soluzioni:
Due possibili soluzioni alternative:
1. Spostare sul Setup registrazione IVA" la gestione dei TD, in modo tale da poter avere TD diversi a parità di fornitore, in caso di acquisto di servizi e/o merce (es.: TD17 e TD18)
2. Predisporre una nuova tabella di setup, dove poter incrociare "Cat. reg. business IVA" e "Cat. reg. articolo/servizio IVA", e per ogni incrocio associare un TD diverso
Con entrambe le soluzioni, andrebbe riportato sulla fattura registrata il TD "prevalente" per importo. 
Ad esempio, se in una fattura alcune righe dell'importo di 1000€ conducessero a un TD17, e altre, di importo 2000€, conducessero al TD18, dovrebbe "vincere" il TD18, in quanto superiore per importo

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao Thomas,
abbiamo deciso di declinare la Ideas dopo un'attenta valutazione sia tecnica che funzionale.
I principali motivi tecnici sono :
- un'impatto pesante che potrebbe avere sul re-factoring dell'APP FTE
- l'alto numero di custom che potrebbero esser state sviluppate in merito a questo argomento

A livello funzionale invece dato che il TD vale per l'intero documento (in testata), spostandolo a livello di Setup registrazioni IVA, si potrebbero potenzialmente avere TD diversi su righe differenti dello stesso documento.

Ti ringraziamo in ogni caso per lo spunto di riflessione
