### ISSUE TITLE
App PMM Factbox Caratteristiche Macchina su Scheda Macchina e Lista Macchina ( WI 15492)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#315]
![image](https://github.com/EOS-Solutions/IDEAS/assets/74410047/2c908013-dd78-471a-bbeb-019c1f6522a7)
Con la factbox è possibile consultare le caratteristiche direttamente dalla pagina scheda o lista

**Comment by Enrico-Marini-EOS** [comment]
Released versions of Plant Maintenance: 
23.0.47
24.0.23
