### ISSUE TITLE
App SBI BC 24

### ISSUE THREAD

**Issue by MauroEOS** [EOS-Solutions/IDEAS#317]
In BC 24 è stata dismessa l'app SBI.
La maggior parte delle aziende non utilizza più l’app SBI perché è stata rimpiazzata dall'invio allo SDI degli xml relativi alle autofatture.
Tuttavia, qualche azienda manda ancora il pdf in conservazione.
Sarebbe possibile avere l'app ripristinata per BC24, oppure integrata all'interno dell'app FTE?
Questo per evitare di proporre soluzioni custom a clienti che stanno ancora usando l'app SBI.

Grazie in anticipo 

Mauro

**Comment by AndreaDiCeglie** [comment]
Buongiorno,
Avremmo un paio di domande:

1) Il PDF non credo che abbia più valore legale, quindi perchè conservarlo a norma ? A norma dovrebbe essere conservato l'XML.
2) Quante sono le aziende interessate ?

**Comment by MauroEOS** [comment]
Buongiorno.

In merito alle domande.

1. Il pdf non ha più valore legale, come giustamente scritto viene conservato a norma il file xml
2. Per il momento lo ha richiesto un'azienda  

Nel caso non fosse possibile ripristinare l'app o integrarla in app FTE, si potrebbe anche pensare di renderla disponibile in SCT.

Grazie

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno Mauro,
dopo attente valutazioni abbiamo deciso di non ripristinare l'APP nè di integrarla in FTE.
Inoltre dato che non sembra possa essere una funzionalità riutilizzabile dubitiamo possa aver senso renderla disponibile in SCT

Grazie a te
