### ISSUE TITLE
Product Configurator: When item is configured on a Job/Project, Item Card Unit Price Update (WI 15495)

### ISSUE THREAD

**Issue by JTAdmBdl** [EOS-Solutions/IDEAS#318]
With the updated EOS version, when an Item is configured from a SO or from an Item Card/Item List, the “Unit Price” is now populated on the Item Card. 

However, the “Unit Price” when configured from a Job doesn't populate the Item Card.

**Comment by Enrico-Marini-EOS** [comment]
Released new versions of Product Configurator: 
23.0.94
24.0.40
