### ISSUE TITLE
DocSolutions for Sharepoint - Aggiunta opzione di cancellazione dei Files

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#32]
Aggiungere la possibilità di rimuovere +/tutte le righe:

- "Remove All"

oppure

- Multiple Selecetion/Select All per poi rimuovere.

![image](https://user-images.githubusercontent.com/88732191/128990106-3d14ac6a-3b0e-4ad8-9102-4f38d5481df4.png)

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
This feature was evaluated at design time and discarded since may produce accidentally bulk deletions.
To massively delete files there are many possibilities:
- Delete files 1 by 1
- Open the storage location (Sharepoin, or FileSystem, or ARXivar) and delete massively from there
