### ISSUE TITLE
APP PQA : Campionatura su matrice controllo per categoria (WI 15622)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#321]
![image](https://github.com/EOS-Solutions/IDEAS/assets/74410047/e8f3371d-b9d5-4f8c-8861-48e8a76c3008)
la campionatura funziona solo nei casi in cui la matrice di controllo è associata a un articolo specifico

E' necessario che funzioni anche per la categoria articolo

**Comment by Enrico-Marini-EOS** [comment]
Released new versions of EX061 Product Quality Assurance: 
23.0.38
24.0.22
