### ISSUE TITLE
IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625)

### ISSUE THREAD

**Issue by StefanoUberti** [EOS-Solutions/IDEAS#323]
La richiesta è motivata da esigenze espresse da molteplici Clienti.
Non è da intendersi come segnalazione di bug (l'app esegue correttamente quanto è stata istruita a fare), 
bensì come proposta di migliore copertura delle esigenze comunemente riscontrate sul mercato.

**Describe the solution you'd like**
Corcostanza: gli anticipi vengono "recuperati" scalandone l'importo dal totale dovuto delle fatture successivamente emesse
Casistica: le fatture successivamente emesse sono molteplici e parziali 
Comportamento attuale: l'anticipo viene scalato pro-quota (proporzionalmente all'importo fatturato) in ogni fattura
Comportamento richiesto: i clienti correbbero potere scegliere fra il comportamento attuale e la seguente variante:
l'anticipo viene scalato (fino a capienza) per intero fin dalla prima fattura.

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno Stefano,
abbiamo proceduto all'implementazione richiesta.
Prima però di renderla disponibile in Integration vorremmo sapere quando potresti provarla, in maniera tale da non avere del codice "in sospeso" che ci bloccherebbe in eventuali bugfix e/o nuovi rilasci dell'APP.
Attendiamo quindi una possibile data.

Grazie Yuri

**Comment by StefanoUberti** [comment]
Ciao Yuri,
forse è l'effetto delle ferie, ma non mi è chiaro di cosa stiamo parlando.
Potresti spiegarmi il contesto?
Grazie,
Ste


Stefano Uberti
Project Manager & Quality Advisor
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P:. | Mob: 3499835100
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: Yuri Giacchetto ***@***.***>
Inviato: martedì 3 settembre 2024 16:30
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Stefano Uberti ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) (Issue #323)


Buongiorno Stefano,
abbiamo proceduto all'implementazione richiesta.
Prima però di renderla disponibile in Integration vorremmo sapere quando potresti provarla, in maniera tale da non avere del codice "in sospeso" che ci bloccherebbe in eventuali bugfix e/o nuovi rilasci dell'APP.
Attendiamo quindi una possibile data.

Grazie Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao Stefano,
si tratta dell'Ideas 323 (https://github.com/EOS-Solutions/IDEAS/issues/323) che hai aperto il 12 Luglio
[https://opengraph.githubassets.com/f6ad3db436abb6a1633df2b8e9af587bab805d9a10a846e57bd009da8ff29dcb/EOS-Solutions/IDEAS/issues/323]<https://github.com/EOS-Solutions/IDEAS/issues/323>
IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) · Issue #323 · EOS-Solutions/IDEAS<https://github.com/EOS-Solutions/IDEAS/issues/323>
La richiesta è motivata da esigenze espresse da molteplici Clienti. Non è da intendersi come segnalazione di bug (l'app esegue correttamente quanto è stata istruita a fare), bensì come proposta di ...
github.com
Fammi sapere quando potresti testarla.

Grazie Yuri


Yuri Giacchetto
Senior Consultant
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P: | Mob: +39 3453615700
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: StefanoUberti ***@***.***>
Inviato: domenica 8 settembre 2024 11:50
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Yuri Giacchetto ***@***.***>; Assign ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) (Issue #323)


Ciao Yuri,
forse è l'effetto delle ferie, ma non mi è chiaro di cosa stiamo parlando.
Potresti spiegarmi il contesto?
Grazie,
Ste


Stefano Uberti
Project Manager & Quality Advisor
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P:. | Mob: 3499835100
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: Yuri Giacchetto ***@***.***>
Inviato: martedì 3 settembre 2024 16:30
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Stefano Uberti ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) (Issue #323)


Buongiorno Stefano,
abbiamo proceduto all'implementazione richiesta.
Prima però di renderla disponibile in Integration vorremmo sapere quando potresti provarla, in maniera tale da non avere del codice "in sospeso" che ci bloccherebbe in eventuali bugfix e/o nuovi rilasci dell'APP.
Attendiamo quindi una possibile data.

Grazie Yuri

**Comment by StefanoUberti** [comment]
Ciao Yuri,
scusa, ora ho capito! 🙂
Io non sono in grado di eseguire il test, ma metto in CC i membri rilevanti del team di Progetto che potrebbero farlo.

@Mario, Agne, Luigi: volete/potete testare la variante all'app di gestione Anticipi che i colleghi hanno evoluto?

Grazie,
Stefano


Stefano Uberti
Project Manager & Quality Advisor
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P:. | Mob: 3499835100
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: Yuri Giacchetto ***@***.***>
Inviato: lunedì 9 settembre 2024 09:19
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Stefano Uberti ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) (Issue #323)


Ciao Stefano,
si tratta dell'Ideas 323 (https://github.com/EOS-Solutions/IDEAS/issues/323) che hai aperto il 12 Luglio
[https://opengraph.githubassets.com/f6ad3db436abb6a1633df2b8e9af587bab805d9a10a846e57bd009da8ff29dcb/EOS-Solutions/IDEAS/issues/323]<https://github.com/EOS-Solutions/IDEAS/issues/323>
IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) · Issue #323 · EOS-Solutions/IDEAS<https://github.com/EOS-Solutions/IDEAS/issues/323>
La richiesta è motivata da esigenze espresse da molteplici Clienti. Non è da intendersi come segnalazione di bug (l'app esegue correttamente quanto è stata istruita a fare), bensì come proposta di ...
github.com
Fammi sapere quando potresti testarla.

Grazie Yuri


Yuri Giacchetto
Senior Consultant
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P: | Mob: +39 3453615700
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: StefanoUberti ***@***.***>
Inviato: domenica 8 settembre 2024 11:50
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Yuri Giacchetto ***@***.***>; Assign ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) (Issue #323)


Ciao Yuri,
forse è l'effetto delle ferie, ma non mi è chiaro di cosa stiamo parlando.
Potresti spiegarmi il contesto?
Grazie,
Ste


Stefano Uberti
Project Manager & Quality Advisor
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P:. | Mob: 3499835100
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: Yuri Giacchetto ***@***.***>
Inviato: martedì 3 settembre 2024 16:30
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Stefano Uberti ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL: Invoicing Plan gestione Anticipi ad Importo (WI 15625) (Issue #323)


Buongiorno Stefano,
abbiamo proceduto all'implementazione richiesta.
Prima però di renderla disponibile in Integration vorremmo sapere quando potresti provarla, in maniera tale da non avere del codice "in sospeso" che ci bloccherebbe in eventuali bugfix e/o nuovi rilasci dell'APP.
Attendiamo quindi una possibile data.

Grazie Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno,
l'Ideas in oggetto è stata rilasciata con le seguenti versioni dell'APP IPL

BC23 : 23.0.37
BC24 : 24.0.42

Buona giornata,
Yuri
