### ISSUE TITLE
Manual Mode - iFileSystem

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#324]
@Stefano-Primo-EOS sa già
Possibilità di aggiungere una EnumExt per gestire la modalità Manuale sul "EOS004 IFileSystem"

esempio:
- test per i consulenti in SaaS del EDI senza aver installato un servizio a pagamento

**Comment by Thomas-Torggler-EOS** [comment]
Una gestione manuale non è fattibile in quanto richiederebbe (per download e upload almeno) di avere un interazione con l'utente che architetturalmente non sta in piedi.

Per OnPrem hai già la possibilità di usare o la EOS FucntionAPI oppure installare [Azurite](https://learn.microsoft.com/it-it/azure/storage/common/storage-use-azurite?tabs=visual-studio%2Cblob-storage) per avere un simulatore di BLOB storage in locale e usare Azure Storage.

Per SaaS hai la possibilità di usare la InMemory-Storage. Però considera che questo è uno storage volatile per-sessione e non tiene i file dopo un logout o cambio utente.
