### ISSUE TITLE
Power MES Campi lista dinamica : Aumentare il numero dei campi disponibili (WI 15701)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#326]
E' una richiesta che hanno fatto diversi clienti 
Vorrebbero avere più campo selezionabili 

Si potrebbe pensare a 10 campi per averne un numero sufficiente comunque almeno 8

**Comment by matteoparlato** [comment]
@AndreaDiCeglie  non possiamo al momento realizzare questa modifica. Le gallery di PowerApps non possono scorrere sia verticalmente che orizzontalmente, pertanto l'aggiunta di nuovi campi, oltre a quelli definiti, non è al momento possibile.
