### ISSUE TITLE
Inserimento funzionalità gestione allegati in spedizioni cws registrate (WI 15713)

### ISSUE THREAD

**Issue by MarcoPontanari** [EOS-Solutions/IDEAS#332]
Nelle spedizione cws registrate nella lista sono visibili le note, nella card si vedono sia note che l'icona allegati.
Inserendo delle note si incrementa il numero sia delle note che delle nel contatore degli allegati. Vedere allegato.
[doc2.docx](https://github.com/user-attachments/files/16392650/doc2.docx)

La richiesta è inserire l'opportunità di utilizzare gli allegati standard nella card e possibilmente anche nella list.

**Comment by Enrico-Marini-EOS** [comment]
Released new versions of EX006 Combine Warehouse Shipment:
23.0.65
24.0.23
