### ISSUE TITLE
Gestione notifiche su instant messaging service

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#333]
**Richiesta**
Quando una coda processi và in errore, vorrei inviare una notifica su teams (o telegram?) ad un utente designato per ricevere le notifiche o in un broadcast a cui gli utenti interessati si possono sottoscrivere.

**In alternativa avevo considerato**
- Invio email, ma le email sono più scomode da controllare (così mi ha riferito il cliente).
- pila su BC delle code in errore (così però deve accedere per forza a BC per controllare).

**Comment by AndreaDiCeglie** [comment]
https://learn.microsoft.com/en-us/dynamics365/release-plan/2024wave2/smb/dynamics365-business-central/get-notified-about-issues-job-queue-background-processing
