### ISSUE TITLE
PRQ: Add "Drop Shipment" features to the purchase requests

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#334]
Aggiungere le informazioni del Drop Shipment nelle tabelle e nelle procedure PRQ.
Gestire il calcolo del Drop Shipment standard così che le richieste di approvvigionamento includano le PRQ nel calcolo delle righe di vendita soddisfatte.

**Comment by AndreaDiCeglie** [comment]
dopo lunga e faticosa disamina della richiesta siamo giunti alla conclusione che lo scenario descritto non debba / possa essere soddisfatto dall'app PRQ che nasce con presupposti e obiettivi diversi. Quanto richiesto sembra una forzatura del disegno originale che vista la differenza cardinalità con cui le PRQ generano e si collegano a righe offerte e righe ordine non si confa pienamente a quanto richiesto dai giri del drop shipment
