### ISSUE TITLE
SGL Storno singolo

### ISSUE THREAD

**Issue by MarkusMoserEOS** [EOS-Solutions/IDEAS#335]
Ciao, 

 stornare nei movimenti SGL non solo per registro (funzione "Storna registro"), ma anche per singoli movimenti:

Perchè un cliente registra manualmente in un Batch più movimenti SGL con Nr. documenti diversi e comunque purtroppo non può stornare i mov SGL del singolo movimenti. Deve stornare tutti quei documenti che ha registrato nel batch insieme al documento che vorrebbe stornare. 
I Test ho fatto sull'integration LABS DEL BZ Team 2: 
![image](https://github.com/user-attachments/assets/5cad50af-6dce-48e9-ba2e-ece0016fdde5)
![image](https://github.com/user-attachments/assets/277d0cf5-acca-47ab-8968-294f06da1d75)
![image](https://github.com/user-attachments/assets/3fae1104-357e-4c5c-a272-0a96f6f0d114)

Grazie
Markus

**Comment by AndreaDiCeglie** [comment]
Buongiorno, sebbene la richiesta abbia senso funzionalmente lo storno delle SGL è implementato basandosi sullo storno standard di BC che supporta solo registri o transaction no e non il singolo movimento

**Comment by MarkusMoserEOS** [comment]
Ciao Andrea, 

grazie per la risposta. 
Infatti, però se faccio gli stessi steps in contabilità generale con la funzione standard allora non mi storna tutta la transazione, ma solo per documento:
Sempre in DEL BZ2 ho salvato come registrazione standard TESTMMO la registrazione: 
![image](https://github.com/user-attachments/assets/49c6d96e-c657-454b-9cfc-7c3257064ee9)
![image](https://github.com/user-attachments/assets/ce8b9d98-1779-48b6-9e00-7143717957a8)
![image](https://github.com/user-attachments/assets/4bf48b8b-dc8f-49dc-8d48-27036d843fda)


Forse dovrei fare una altro step quando storno con SGL in modo che mi prende solo i movimenti collegato al documento?

Grazie
Markus

**Comment by AndreaDiCeglie** [comment]
Sebbene si  possa avere la sensazione che lo storno sia avvenuto solo per documento, in realtà è stato fatto per transazione.
Bisogna esaminare nell'esempio fornito la cardinalità e la composizione di nr documento e nr transazione.
Nel tuo esempio c'è il nr di transazione che va di pari passo col nr documento. Vedi screenshot il titolo è "storna movimenti transazioni"

**Comment by MarkusMoserEOS** [comment]
grazie per la risposta. 
allora dico al cliente che deve fare una custom perchè la funzione "Storno registro" della App SGL va sul Nr. documento perchè la transaction no. non esiste nella tabella del SGL (e non c'è intenzione di cambiarla)
![image](https://github.com/user-attachments/assets/23c6d770-5288-4973-a348-741ed4955501)

Invece la funzione Standard BC va sul transaction no. 
![image](https://github.com/user-attachments/assets/076de88f-9da4-4196-b5ce-fb65d81766d7)

Grazie
