### ISSUE TITLE
PMM : Utilizzare i fogli presenze per inserire i tempi delle risorse su richieste di lavoro PMM (WI 15874)

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#337]
Al momento dal foglio presenze è possibile inserire i tempi delle risorse per commessa, ordine di assistenza,  risorsa senza documento, assenza, assemblaggio  (tutte le consuntivazioni relative alle risorse) 
Non è possibile inserire ore Risorsa su Richieste di lavoro PMM 
![image](https://github.com/user-attachments/assets/a2dcedea-96c1-4faf-9d5e-077d02fff294)

**Comment by AndreaDiCeglie** [comment]
L'estensione di enum standard per quanto sia in sè un operazione fattibile e semplice può dare facilmente origine a comportamenti inattesi poichè il codice standard che tratta le condizioni logiche legate ai valori presenti non considerano affatto eventuali nuovi valori custom. E' pertanto necessario un approfondimento tecnico con numerosi test nei diversi scenari

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX060 Plant Maintenance:
23.0.57
24.0.35 Saas
25.0.10
