### ISSUE TITLE
EX074 EDI - migliorie da apportare per espandere le potenzialità dell'app

### ISSUE THREAD

**Issue by FleshC0ffin** [EOS-Solutions/IDEAS#338]
Ciao,

vi scrivo un paio di considerazioni che potrebbero tornare utili per l'app EX074 EDI, dopo aver lavorato un anno abbondante su un'integrazione EDI esterna su un cliente di Padova.

Attualmente, da quanto ho capito, vengono gestite:
1. Ricezioni d'ordine (protocollo 850)
2. Conferma di ricezione d'ordine al mittente (protocollo 855)
3. Invio fattura/nota credito (protocolli 810/812)

Altri protocolli da implementare, a parer mio, che potrebbero tornare utili a livello "generico" sono:

1. Modifiche dell'ordine (protocollo 860), ovvero, dato un Ordine ABC già ricevuto e presente in Business Central, modificarlo, aggiungendo nuove righe o modificando dettagli di righe già presenti
2. Invio spedizione (protocollo 856), è un protocollo che va di pari passo con l'810. Implementabile sia con le CWS che Spedizioni di Vendita standard.
3. Conferma generica (protocollo 997), penso sia già implementato tramite i messaggi di notifica quando vengono gestite le fatture/note credito (es. "messaggio inviato con successo" o "messaggio errato, visualizzare log"). Può essere sostitutivo del protocollo 855, in quanto serve più come un "ehi, ho ricevuto quello che hai inviato in generale", piuttosto che specificare N protocolli per tipo documento.

Altro dubbio che mi viene: noi in che modo gestiamo i codici GLN/DUNS e dipartimenti EDI? Il primo sarebbe il codice univoco associato al partner commerciale (Esempio: partner EOS Solutions, codificato globalmente come EOS, con DUNS 0011002233), che però può variare ed essere associato a degli identificativi univoci relativi alle vendite, fatture e spedizioni (es. EOS per gli ordini ha DUNS 0011002233, per le fatture 1100220033, per le spedizioni 0033001122). Il secondo, invece, è un codice che definisce qual è il reparto del cliente che gestisce internamente lo smistamento della merce arrivata. Solitamente è univoco, come identificativo, d'altronde capita che un partner commerciale gestisca diversi tipi di documento con dipartimenti diversi (es. dipartimento XYZ gestisce la merce comprata, dipartimento ABC gestisce la merce dopo la riparazione), oppure, che i documenti in uscita vengono gestiti con un dipartimento e i documenti in entrata con un altro.

Al momento non mi viene in mente altro sui protocolli... non penso nemmeno serva (quanto emerso l'ho scritto in base a quanto ho visto sulla società americana del cliente, che per l'80% vive di EDI), in quanto si tratterebbe di estendere quanto già è presente nell'app (ovvio, non so com'è fatta, quindi non so quanto impattante sarebbero le modifiche), però potrebbe tornarci utile per implementazioni su clienti futuri o, qualora dovessero persistere attuali blocchi sul cliente, dovuti all'ente terzo che gestisce l'EDI, per includere l'app in progetti già esistenti, adattando quanto già è stato fatto alla platform.

Resto a disposizione per eventuale confronto e presentazione sui dati del cliente di quanto scritto sopra.

Grazie!

**Comment by AndreaDiCeglie** [comment]
I protocolli citati negli esempi sono specifici per X12 usato sopratutto per USA e CANADA. 
L'app EOS EDI è strutturata come framework di base estendibile che supporta out of the box un numero limitato di messaggi e standard.
Quanto descritto fa riferimento ad una sola delle possibili decine di implementazioni che i flussi EDI possono richiedere.

Se si tratta di funzionalità già sviluppate è possibile richiedere che vegano accreditate come soluzioni SCT (Rif Implementation) o aggiunte a Sample. Nei piani di crescita dell'APP EDI non è previsto il supporto completo di specifici standard e/o settori

**Comment by FleshC0ffin** [comment]
Ciao Andrea,

Mea culpa sul non essermi informato a dovere sulla differenza tra protocolli USA-Canada/EU, scusa.

Presumo quindi che, qualora dovesse presentarsi una richiesta del cliente per, ad esempio, aggiungere la notifica di spedizione, sarebbe da estendere l'app Plaftorm con una custom, corretto?

**Comment by AndreaDiCeglie** [comment]
si
