### ISSUE TITLE
CIG e CUP sulla scheda del cliente 

### ISSUE THREAD

**Issue by MarkusMoserEOS** [EOS-Solutions/IDEAS#343]
Ciao, 

ho visto adesso un paio di clienti che ci avevano chiesto una modifica per mettere il CIG e CUP sul cliente perchè non cambia per ca. un anno. Questi due campi sul cliente dovrebbero poi essere inseriti in un nuovo record nella tabella EOS Outb. EDoc. Related Docs. (18123045), Eos Document Type = DatiordineAcquisto --> EOS CodiceCUP (250, Code[15]) und EOS CodiceCIG (260, Code[15]).
Altrimenti avrebbero dovuto sempre inserire a mano nei documenti correlati il CIG e CUP. 

![image](https://github.com/user-attachments/assets/d794268a-ccb6-4a62-b73e-16ca90a07c91)

Ciao
Markus

**Comment by AndreaDiCeglie** [comment]
Ciao Markus, 
Per alcuni clienti la gara e progetto possono effettivamente durare molto ma metterli sulla scheda cliente non sembra indicato come implementazione standard.
Un ipotesi più elastica potrebbe essere avere una tabella con Cod Cliente, Cig, Cup, Data inizio e data fine.
Tuttavia anche questa sembra adatta solo a chi gestisce un appalto alla volta, potrebbe essere normale avere in contemporanea più gare e più progetti.
Secondo noi restano implementazioni da fare custom

**Comment by MarkusMoserEOS** [comment]
Ciao Andrea, 

ok grazie per la risposta!

Ciao
Markus
