### ISSUE TITLE
App PQA: blocco creazione prelievo per gli articoli che hanno un ordine di controllo aperto

### ISSUE THREAD

**Issue by Simone-Tartarini** [EOS-Solutions/IDEAS#344]
Riporto di seguito l'email con l'Idea che ho inviato al Labs:

Se ho degli articoli presenti in una collocazione di controllo qualità, spostati nella collocazione tramite un ordine di controllo aperto, il sistema non me lo farà notare finché non creo la CWS e, in questo caso (soprattutto per alcuni clienti che me l'hanno segnalato), è pericoloso perché il programma ti dà la possibilità di effettuare il prelievo di merce che in realtà non è disponibile (perché si trova in controllo qualità).

Sarebbe bello se si potesse bloccare la creazione del prelievo (che sia fatto da Power App, o da spedizioni warehouse, o dal prospetto prelievi) per tutti quegli articoli che hanno la quantità da prelevare bloccata da un ordine di controllo aperto. 
L'eccezione si verificherebbe nel momento in cui ho una riga spedizione per 1.000 pezzi dell'articolo X e nell'ordine di controllo ho 500 pezzi, mentre in magazzino ne ho 2.000 stoccate. In questo caso il prelievo può essere fatto.

Spero di essermi espresso correttamente. In caso contrario sentiamoci.

Grazie,

Simone Tartarini
BC Operations Consultant

**Comment by AndreaDiCeglie** [comment]
non  è possibile suggeriamo di confrontarsi con il competence circle manufacturing (Rif. Grassi)
