### ISSUE TITLE
DUM - Implementare logica che permette l'utilizzo della funzione Create Purchase Order dai Sale Order (WI 15928)

### ISSUE THREAD

**Issue by alepillon** [EOS-Solutions/IDEAS#345]
Buiongiorno,

Vorremmo sottoporvi la possibilita' di utilizzare la funzione Create Purchase Order dai Sale Order.
Attualmente questa funzione crea un Purchase Order scorretto perche' durante la creazione dell'ordine il sistema non e' in grado di recuperare i corretti Purchase Prices se espressi attraverso la secondary unit of measure.
Per nostra conoscenza la funzione Create Purchase Order si appoggia alla Requistion Worksheet che attualmente ha lo stesso problema quando si gestiscono i Drop Shipment da li (i Purchase Order anche in quel caso non sono creati correttamente)

Cordiali saluti.

**Comment by Mariangela-DeMaio-EOS** [comment]
Released version 24.4.37 of EX051 "Dual Unit of Measure" .
