### ISSUE TITLE
Predisporre una funzione per aggiornare in modo massivo il materiale nella "SCHEDA IMBALLO CONAI"

### ISSUE THREAD

**Issue by ErcolinoG** [EOS-Solutions/IDEAS#347]
Buongiorno,
chiedo di sviluppare una funzione che aggiorni in modo massivo i materiali Conai all'interno della scheda imballo conai.
La funzione dovrebbe essere sviluppata interamente da zero e dovrebbe, almeno idealmente portare ad una creazione di un cruscotto posso essere riempito in base a tre diversi filtri:
1) articolo
2) fornitore (dato presente in anagrafica articoli)
3) materiale conai

Nel tentativo di offrire un esemplificazione di quanto richiesto allego l'immagine di un cruscotto che è stato sviluppato per aggiornare in modo massimo i prezzi di vendita.

![image](https://github.com/user-attachments/assets/a00bed48-b255-4679-8d9a-c339b9ad7fa8)

Una volta inserito uno dei tre filtri, il giornale del cruscotto dovrebbe mostrare i seguenti dati:

1) materiale
2) peso netto presente nell'agrafica articolo
3) date di validità di inizio e fine

A questo punto dovrebbe esser possibile esportare i dati in excel e poter aggiornare/cambiare le stringhe. 
Ė essenziale aggiornare il peso netto dell'anagrafica articoli perché è in base a quel valore che viene poi inserito il peso primario dell'imballaggio conai all'interno della scheda imballo. 

Al fine di evitare possibili complicazioni è fondamentale che se viene inserito un nuovo record su un articolo, che presumibilmente riporta come data di inizio validità quella del giorno in cui si compie l'operazione, automaticamente venga impostata, sul record precedente, una data di fine validità che sia pari alla data del giorno dell'operazione -1, o comunque alla data di inizio validità del nuovo record -1.

**Comment by AndreaDiCeglie** [comment]
Stiamo valutando la cosa, la soluzione descritta appare eccessivamente complessa , sarebbe probabilmente sufficiente avere una lista flat delle righe utilizzabile con la funzione standard "edit in excel".
Vista la bassa priorità che abbiamo assegnato alla proposta ci ripromettiamo di rivalutarla
