### ISSUE TITLE
PTS | collegamento scheda tecnica e articolo (WI 16307)

### ISSUE THREAD

**Issue by mgeremia** [EOS-Solutions/IDEAS#348]
Dalla scheda articolo, quando si passa all'elenco delle specifiche tecniche per vedere quali specifiche tecniche di prodotto sono collegate a un articolo, non c'è modo di aprire la specifica tecnica dall'elenco.

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX091 Product Technical Specifications: 
23.0.34
24.0.24 Saas
25.0.11
