### ISSUE TITLE
Gestione fatturazione per gli ordini speciali

### ISSUE THREAD

**Issue by apezzano** [EOS-Solutions/IDEAS#350]
Buongiorno,

chiedo la possibilità di integrare la logica standard della generazione delle fatture nel caso di ordini speciali: da standard Microsoft nel caso di ordini speciali non è possibile generare fatture di acquisto, se prima non sono state create e registrate le fatture di vendita correlate allo stesso ordine. Si può togliere questo vincolo? Per clienti italiani capita spesso di dover registrare prima la fattura di acquisto e, solo dopo, quella di vendita. 

Grazie

**Comment by AndreaDiCeglie** [comment]
non abbiamo verificato se sia tecnicamente possibile, se lo fosse può e deve essere realizzato come custom. Non c'è un app standard EOS che abbia queste finalità e in caso di effetti collaterali imprevisti non spetta alle app certificate rimuovere controlli standard così come non possiamo nascondere campi, azioni, page...
