### ISSUE TITLE
MMM - aggiunta task su cicli alternativi e automatismo per sostituzione fase (WI 16319)

### ISSUE THREAD

**Issue by chiarapergolini** [EOS-Solutions/IDEAS#351]
Come estensione all'app **Manufacturing masterdata management (MMM)** si richiedono queste modifiche per la gestione delle risorse alternative sui cicli:

- Nella tabella Righe cicli produzione alternative (EOS085 Rout. Alternative Line (18004194)), inserire il campo Task standard. Effettuare la stessa modifica sulle Righe cicli ord. prod. Altern (EOS085 Prod Ord. Rtng. L. Alt. (18004195)).

- Alla creazione e all'aggiornamento dell'ordine di produzione, popolare il dato leggendo dal ciclo. Assicurarsi di effettuare la compilazione anche al passaggio fra i vari stati dell'ordine (es. da confermato a rilasciato).

- Nella pagina Righe cicli ord. prod. altern. (EOS085 Prod Ord. Rtng. L. Alt. (18004195, List)) creare una funzione per permettere la sostituzione della fase ciclo con la riga di ciclo alternativa selezionata.

- Nella pagina Cicli ordini produzione (Prod. Order Routing (99000817, List)) sarebbe utile avere un campo calcolato "Esiste alternativa" con valori Sì/No. Cliccando sul campo sarebbe utile aprire la pagina EOS085 Prod Ord. Rtng. L. Alt. (18004195, List).

**Comment by AndreaDiCeglie** [comment]
Ciao,

Le richieste indicate sopra fanno riferimento ad una sola app ma a due implementazioni differenti e distinte.
Consideriamo approvata la prima a cui verrà assegnato un WorkItem e quindi una data di rilascio.
Per la seconda ti chiediamo di insierie una nuova issue in IDEAS

**Comment by chiarapergolini** [comment]
Ciao, vi informo che ho aggiunto questa issue per la seconda richiesta https://github.com/EOS-Solutions/IDEAS/issues/370.
Grazie

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX085 Manufacturing Masterdata Management (per i primi due punti della IDEA):
23.0.30
23.1.37
24.0.27
24.1.24
25.0.13
