### ISSUE TITLE
ADR: Extended the Advanced Texts to missing service and transfer pages (WI 16325)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#354]
Riscontriamo che i Testi Avanzati sono mancanti solo nelle seguenti pagine:
- Transfer Order
- Transfer Shipment
- Service Credit Memo
- Service Posted Cr.Memo
- Service Contract Quote
- Service Contract
Per completezza sarebbe opportuno averli presenti su anche questi oggetti così da riprendere completamente le vecchie funzionalità di Engineering che avevamo su NAV.

**Comment by AndreaDiCeglie** [comment]
La parte Trasferimenti è da valutare ma comunque faremo il possibile

**Comment by Stefano-Primo-EOS** [comment]
E' ora disponibile OnPrem 24.0.25 e 25.0.15
In massimo 24h sarà disponibile anche su SaaS
