### ISSUE TITLE
MMM: Copy the location code when adding a component in a production order (WI 16328)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#356]
Gestire l'ubicazione sulle nuove righe inserite quando si usa il Prospetto Componenti per aggiungere un articolo in un ordine di produzione.
Tutti i dati originali della riga a cui ci si lega, infatti, andrebbero copiati così da non dover intervenire sulle nuove righe appena create per modificarle manualmente. Nello specifico, dovrebbe copiare:
- Routing link code
- Location code

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX085 Manufacturing Masterdata Management: 
23.0.30
23.1.37
24.0.27
24.1.24
25.0.13
