### ISSUE TITLE
HUM: add setup to allow inheriting a HUM from the transfer shipment to the transfer receipt (WI 16337)

### ISSUE THREAD

**Issue by f0ffee** [EOS-Solutions/IDEAS#359]
Right now, when assigning a HUM to a warehouse shipment born from a transfer order, the user has to manually re-assign the same HUM on the related warehouse receipt. If the user forgets to do so, the material is still posted and transferred to the new location, but the HUM stays behind and it's complicated to adjust it.

It would be helpful to have a setup (in order to maintain current behaviour as it is) that would allow the HUM to be automatically inherited from the warehouse receipt.

**Comment by Mariangela-DeMaio-EOS** [comment]
Released in version 24.0.48 "Advanced Logistic Common Library"
