### ISSUE TITLE
DocSolutions for Sharepoint - EOS069 Library Permission - Aggiunta controllo "Consenti/permetti eliminazione"

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#36]
Aggiungere l'opzione "Consenti/permetti eliminazione" per ridurre le attività di gestione cestini e restore dei dati da SharePoint ed i relativi rischi di perdita dei medesimi.

![Cattura](https://user-images.githubusercontent.com/88732191/129209683-4ef84494-5658-4484-b524-f68044b2e1a1.PNG)

p.s. vedasi anche Issue #39

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
Since Uploading a file ,ay imply substituting an existing file, deletion is a subordinated permission of write.
DocSolutions Permission sets are designed accordingly with file system permissions
Won't change
