### ISSUE TITLE
App VMI - Stampa libro giornale senza movimenti stornati

### ISSUE THREAD

**Issue by MauroEOS** [EOS-Solutions/IDEAS#360]
La stampa del libro giornale con l'app VMI include anche i movimenti della G/L Entry (17) con flag "Stornato" = true (campo Reversed (73, Boolean) della G/L entries).
Un cliente mi ha chiesto la possibilità di escludere questi movimenti dalla stampa.
Sarebbe utile avere un flag includi/escludi movimenti stornati nella page di lancio del report.

Grazie

**Comment by AndreaDiCeglie** [comment]
non c'è il rischio di creare buchi nella stampa ?
