### ISSUE TITLE
PMM : Gestione dei ticket 

### ISSUE THREAD

**Issue by SIMONEGRASSI** [EOS-Solutions/IDEAS#364]
La gestione dei ticket è utile per aprire delle richieste di intervento per manutenzione a macchinari o infrastrutture. 
Il ticket può diventare o meno una richiesta di lavoro . 
I campi proposti potrebbero essere : 
	○ Codice
	○ Descrizione
	○ Foto (Potere importare più foto, creare info-box.
	○ Stato segnalazione (options)
	○ Nr. richiesta lavoro
	○ Dalla segnalazione si deve potere creare un intervento.

Il ticket può essere aperto da bc o da power app
Dovrà esserci una sezione per aprire i ticket e per verificarli

**Comment by AndreaDiCeglie** [comment]
developing a ticketing system in BC seems not to be a good idea, I'm available for further discussion about this
