### ISSUE TITLE
IPL: Manage service orders in Invoice Plan (WI 16371)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#367]
Implementazione del piano di fatturazione negli ordini di assistenza.

**Comment by Yuri-Giacchetto-EOS** [comment]
Versione beta dell'APP IPL aggiornata con la gestione degli ordini di assistenza presente in Integration Finance (http://br-labsdev3.eos.it:8083/integration_fin/)

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao,
lunedì andremo in pubblicazione con l'aggiornamento dell'APP che gestirà anche gli ordini di assistenza.
Le funzionalità presenti saranno pressoché identiche a quelle degli Ordini di vendita, comprensiva di "gestione CIG e CUP" e "NC non collegata a fattura" appena rilasciate per gli OdV.

Lo sviluppo sarà rilasciato per BC24 e BC25

Non appena pubblicate vi faremo avere le versioni aggiornate.

Grazie Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno,
la soluzione verrà rilasciata per le seguenti versioni :

BC24 : 24.0.50
BC25 : 25.0.19

Ciao Yuri
