### ISSUE TITLE
App VMI - Richiesta inserimento eventi Report "EOS Calc. and Post VAT Settl." (WI 16349)

### ISSUE THREAD

**Issue by cosimomelechiagic** [EOS-Solutions/IDEAS#368]
Si richiede la possibilità di inserire alcuni eventi all'interno del Report 18008259 "EOS Calc. and Post VAT Settl.". In allegato troverete il file Word con gli eventi da creare e l'ultimo report standard 20 (l'estensione è stata modificata in .txt poiché non era possibile caricarlo con l'estensione originale; basterà rinominarlo in .al), con indicazioni su dove inserirli.

[Eventi.docx](https://github.com/user-attachments/files/17310085/Eventi.docx)
[CalcandPostVATSettlement.Report.txt](https://github.com/user-attachments/files/17309966/CalcandPostVATSettlement.Report.txt)

Grazie per l'attenzione.

Cosimo Melechì - cosimo.melechi@agictech.com

**Comment by cosimomelechiagic** [comment]
Buon pomeriggio,

vi chiedo se sono presenti aggiornamenti relativi alla richiesta effettuata e, se possibile, sapere le tempistiche di rilascio.

Vi ringrazio,

Saluti.

**Comment by Ricardo-Quintero-EOS** [comment]
Ciao,

La modifica è stata effettuata e pubblicata nei feed onprem per  BC24 e BC25 nelle versioni  24.0.37 , 25.0.20

Gli eventi aggiunti sono 

- OnBeforeVATPostingSetupCalculationType
- OnAfterCopyAmounts
- OnBeforePostRoundingAmountPostSettlementAccount
- OnBeforePostSettlementAccountRoundAmount 
- OnBeforePostSettlementAccountVATAmount 

nei punti richiesti nel vostro file word

Saluti,
Ricardo
