### ISSUE TITLE
Common Data Layer: add Service document summary (WI 16456)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#369]
Le funzionalità del riepilogo documenti coprono i flussi acquisto e vendite ma non quelli del modulo assistenza.
Sarebbe comodo avere un riepilogo dei documenti, delle fatture e delle note di credito.

**Comment by AndreaDiCeglie** [comment]
Le page fatte da noi nel cdl sono poi state rifatte da MS nello standard. Al momento di fatto sono doppioni che non abbiamo voluto rimuovere poichè non comportano particolari costi o rischi. L'analisi delle righe di assistenza dovrebbe quindi già esserci nello standard

**Comment by MatCive** [comment]
In realtà nello standard non sono presenti:

![image](https://github.com/user-attachments/assets/c6fed928-6066-4833-8fd5-b14028b7ed4f)

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX066 Common Data Layer:
24.0.26 Saas
25.0.13
