### ISSUE TITLE
Foreign Currency of the invoices (customer and vendors) compensation

### ISSUE THREAD

**Issue by ja1mes1** [EOS-Solutions/IDEAS#37]
Is there a way to see the Foreign Currency of the invoices (customer and vendors)? We can only see the LCY amounts. We tried to look if they were available in Personalization but they were not there.

we need to see the balance and amount of invoices in Euros to do the compensation.

**Comment by AndreaDiCeglie** [comment]
This would be a nice feature but currently is low priority and high budget. Will be considered in future.

**Comment by AndreaDiCeglie** [comment]
Customer Vendor compensation is announced as new standard Feature for BC20. 
Waiting to see what Microsoft is releasing.
https://docs.microsoft.com/en-us/dynamics365-release-plan/2022wave1/smb/dynamics365-business-central/consolidate-customer-vendor-balances
