### ISSUE TITLE
MMM - automatismo per sostituzione fase alternativa in cicli ordine di produzione (WI 16427, WI 16430)

### ISSUE THREAD

**Issue by chiarapergolini** [EOS-Solutions/IDEAS#370]
Come estensione all'app Manufacturing masterdata management (MMM) si richiedono queste modifiche per la gestione delle risorse alternative sui cicli:

- Nella pagina Righe cicli ord. prod. altern. (EOS085 Prod Ord. Rtng. L. Alt. (18004195, List)) creare una funzione per permettere la sostituzione della fase ciclo con la riga di ciclo alternativa selezionata.

- Nella pagina Cicli ordini produzione (Prod. Order Routing (99000817, List)) sarebbe utile avere un campo calcolato "Esiste alternativa" con valori Sì/No. Cliccando sul campo sarebbe utile aprire la pagina EOS085 Prod Ord. Rtng. L. Alt. (18004195, List).

**Comment by Enrico-Marini-EOS** [comment]
Rilasciate le seguenti versioni della EX085 Manufacturing Masterdata Management:
23.0.33
23.1.40
24.0.30
24.1.27 Saas
25.0.16
