### ISSUE TITLE
EOS031 CONAI - action “Imballo CONAI” 

### ISSUE THREAD

**Issue by LoreLBA** [EOS-Solutions/IDEAS#371]
Nella pagina della fattura di vendita, cliccando il pulsante “Imballo CONAI” si apre la Pagina  “Modifica – Dettaglio CONAI”. Se al suo interno ci sono delle righe, cliccando il tasto CHIUDI, aggiunge, se non presenti, le righe addebito(articolo) CONAI per ogni riga articolo corrispondente, (se già presenti, le aggiorna).
La richiesta sarebbe di aggiungere il tasto “IMBALLO CONAI” con la stessa funzionalità, sull’ordine di vendita e sull’offerta di vendita.

![2024-10-11_11h37_46](https://github.com/user-attachments/assets/3f30532b-208d-4f29-b58e-36dbfbcb502b)
![2024-10-11_11h40_49](https://github.com/user-attachments/assets/d9675426-c98c-422c-ae56-222ef0fb3575)

**Comment by AndreaDiCeglie** [comment]
developed as custom
