### ISSUE TITLE
Getting notified for arriving calibration date

### ISSUE THREAD

**Issue by EmadKeyvani86** [EOS-Solutions/IDEAS#372]
Hi,
I have a question about the Inspection Device List (PQA) in Business Central. We store all the data related to the devices, including the calibration date and period. I'm wondering if it's possible to receive an email from BC (or any notification) when the calibration date is approaching. 
![Capture](https://github.com/user-attachments/assets/b0028c3c-6700-4404-91c8-62db2110d937)

**Comment by AndreaDiCeglie** [comment]
Hi, we have no plans to implement a specific notification system for this date.
What is basically needed is a notification system that can manage recipients, channel and a Jobqueue the monitors the expiration date.

We have an app that can maybe satisfy this with a small customization to insert the record as "manual expiration"

https://appsource.microsoft.com/en-us/product/dynamics-365-business-central/PUBID.eos_solutions%7CAID.ex033_expirationmonitorforazuresecrets%7CPAPPID.d80a15a1-e722-421a-a765-fd52a1eaf70a?tab=Overview
