### ISSUE TITLE
VMI - Registri fiscali IVA Raggruppati annuali non espone importo pagato con F24

### ISSUE THREAD

**Issue by GiusyViola** [EOS-Solutions/IDEAS#375]
Buongiorno,
piu' di un cliente mi segnala il seguente problema.

 Nella stampa dei registri iva raggruppati non viene esposto l’importo pagato con F24, anche se viene compilato nell’Importo pagato nel periodo nella lista dichiarazioni IVA.

Ho eseguito un test sul nostro ambiente sull’azienda CB MI-CN.
Ho liquidato 2 mesi: maggio e giugno 2027.
Vi allego le stampe.
Maggio a debito 2.650,89
Giugno a credito di 2.200,00

Se stampo i registri fiscali raggruppati dei 2 mesi indica un debito di 450,89, perché non viene esposto l’importo pagato anche se compilato nel periodo 05/2027.

Allego stampe.

Saluti
Giusy Viola

![liq](https://github.com/user-attachments/assets/009bd916-cea7-49e7-8b86-b40eefd11d11)

 
[Calcola e registra liquidazione IVA (VMI) 062027.pdf](https://github.com/user-attachments/files/17407711/Calcola.e.registra.liquidazione.IVA.VMI.062027.pdf)
[Calcola e registra liquidazione IVA 052027.pdf](https://github.com/user-attachments/files/17407712/Calcola.e.registra.liquidazione.IVA.052027.pdf)
[Registri fiscali IVA Raggruppati (VMI).pdf](https://github.com/user-attachments/files/17407713/Registri.fiscali.IVA.Raggruppati.VMI.pdf)

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao Giuseppina,
mi sono confrontato con il CC (Petrera/Giordani) e abbiamo deciso di non procedere all'implementazione.
Queste le motivazioni principali :
- Calc. e reg. liq. IVA: la liquidazione viene eseguita prima di pagare l’IVA, e di conseguenza sarebbe visibile solamente in seguito ad una ristampa, operazione inusuale
- Registri IVA raggruppati: è una stampa che solitamente viene utilizzata come recap di più periodi IVA (a supporto della dichiarazione annuale). Necessiterebbe di un livello di dettaglio dell’importo pagato per banca/mese e non di un semplice totale. Esporre il solo importo pagato nei mesi considerati non darebbe valore aggiunto.
Suggeriamo quindi un eventuale custom per il cliente.

Buona giornata,
Yuri
