### ISSUE TITLE
Gestione Iva fatturazione OSS

### ISSUE THREAD

**Issue by ErcolinoG** [EOS-Solutions/IDEAS#377]
Attualemnte in BC non c'è la possibilità di gestire in maniera chiara la fatturazione in regime OSS, ossia la gestione delle vendite a privati esteri.
In particolare  sia nel caso l'azienda desideri utilizzare platfond iva (indicando l'operazione con codice N3.2) sia che non lo faccia (indicando quindi l'operazione con codice N7) nella fattura elettronica non è possibile dare evidenza nè dell'aliquota iva (che sarà quella del paese estero di riferitmento) nè del relativo importo. 
A tal proposito questi dati potrebbero essere indicati nella sezione"Altri dati gestionali" della fatturazione elettronica:

Tipo dato: IVA
Valore testo: (aliquota paese di riferimento es. 17%)
Valore numerico: importo iva

Oltre ad una maggior chiarezza dell'operazione svolta, la possibilità di inserire l'aliquota iva del paese di riferimento in fattura, sebbene l'operazione sia non imponibile, permetterebbe di facilitare la tenuta dei registri iva esteri.

**Comment by Yuri-Giacchetto-EOS** [comment]
Attualmente, in accordo con il CC Finance, non è prevista la gestione del regime OSS nel tracciato FTE in quanto non obbligatoria. E' quindi necessario eventualmente procedere con una custom.

Per quanto riguarda la gestione della liquidazione IVA per le fatture OSS ricordiamo che è presente su VIVA la documentazione per il corretto setup : https://eossolutionsspa.sharepoint.com/:w:/r/sites/Viva_Delivery/Documenti%20condivisi/Competence%20Circles/Finance/operaz-regimeOSS-IOSS.docx?d=wa44d108c8b794d4d9ab43df2e63b917c&csf=1&web=1&e=aWfEQb

Per ogni altra informazione sul tema si rimanda al CC Finance.
