### ISSUE TITLE
Bundle Assistant: Tool di gestione per Vendita

### ISSUE THREAD

**Issue by Andrea-Tassinari-EOS** [EOS-Solutions/IDEAS#379]
Bundle assistant

Con questa ideas si intende voler proporre un tool di assistenza per la gestione lato cliente dei Bundle
Per chi non avesse dimenstichezza con l'argomento riporto il link a widipedia che spiega concettualmente il tema:
https://en.wikipedia.org/wiki/Product_bundling

Il legame logico sulla quale vorrei mappare la proposta è la gestione attraverso distinte di assemblaggio ed articoli del prodotto Bundle.
Nel caso si voglia non dipendere dalla distinta di assemblaggio poichè la sua gestione nativa di BC non offre sufficienti informazioni o sia troppo limitante si potrebbe anche ricreare una struttura analoga alla distinta di assemblagio e che gestisca con testata e righe, anche le versioni, lo stato, data di valità e data di prima approvazione (così da gestire nelle logiche anche l'utilizzo delle distinte per concetti di validazione).

In Offerta ed Ordine vorrei suggerire di creare delle action che propongano di:
- "Ottimizza in Bundle"
- "Proponi Bundle per sfusi parziali"

Nella Lista delle Distinte di Assemblaggio si vorrebbe poter integrare le seguenti funzionalità:
- "Suggerisci Assemblaggio Bundle"
- "Suggestisci nuova Distinta Bundle"

Di seguito vado a spiegare i concetti delle fnzionalità:
"Ottimizza in Bundle":
Partendo dalle righe di un ordine, il tool deve produrre un'elaborazione di accorpamento di tutte le righe possibilmente gestibili come bundle e se si conferma il suggerimento si aggiornanlo le righe documento (Ordine o Offerta) con la proposta prodotta.
Lo strumento deve ragionare andando a valutare se prima di tutto con le quantità ancora da gestire (mantenendo attraverso opzione anche la condizione di magazzino di partenza) è possibile produrre dei bundle di accorpamento, e poi valutare secondo la logica selezionata, gli accorpamenti.
Le logiche ipotizzabili sarebbero: Miglior prezzo cliente, Miglior utilizzo magazzino.
Nella logica del Miglior Prezzo cliente il calcolo dovrebbe ponderare sul produrre bundle cercando di massimizzare il risparmio sul prezzo di vendita a cliente.
Nella logica del Miglior utilizzo Magazzino, il calcolo dovrebbe cercare di dare priorità al consumo delle giacenze già disponibili a magazzino.
Nella fase di utilizzo si dovrebbe poter indicare se si vuole inserire le nuove righe basate su articoli Bundle

"Proponi Bundle per sfusi parziali"
Come per la funzione "Ottimizza in Bundle" si vorrebbe produrre uno strumento a due fasi: una di elaborazione in cui vengono proposte delle righe ed una seconda fase, post approvazione da parte dell'utente, in cui vengono modificate le righe ordine.
Questo strumento, che in parte si basa sui concetti del primo, in quanto se lanciato dovrebbe fare come prima attività l'ottimizzazione, dovrebbe ragionare sulle righe articolo residue che sono rimaste non gestite a bundle, ed in base alle distinte base di assemblaggio utilizzabili, proponga delle righe gestite a bundle ma per i quali utilizzi sia necessario anche aggiungere ulteriori articoli.
Si potrebbe voler usare questa funzionalità senza la prima, in questo caso le DB da considerare sarebbero quelle per cui manca almeno un componente della DB. Questa volontà di utilizzo sarebbe utile a chi vorrebbe produrre offerte per far conoscere i suoi nuovi prodotti, innestandoli ad ordini basati su prodotti già più conosciuti.
In questo caso i parametri di lancio dovrebbero poter gestire le seguenti capacità:
- Considera solo prezzo finale conveniente (Quindi la logica utilizza solo le Distinte che produrranno, all'aggiunta di articoli un prezzo finale al cliente pari o inferiore a quello attuabile)
- Considera solo prezzo finale al massimo di una percentuale di markup (Quindi la logica non si basa solo sui prezzi convenienti, ma prenderà in considerazione anche prezzi maggiori fino al limite calcolato come percentuale inserita)
Un'ulteriore logica integrabile sarebbe anche quella del "Privilegia consumo giacenze" il cui scopo è successivo alle logiche introdotte prima, ma nel caso ci siano più Distinte utili, darà priorità a quelle i cui articoli aggiunti, o i bundle stessi, abbiano più giacenze a magazzino.

"Suggerisci Assemblaggio Bundle"
Questa funzionalità serirebbe per avviare ordini di assemblaggio basandosi sulle richieste da ordini di vendita e giacenze di magazzino. Logica simile ad un MRP.

Spiegati i concetti tecnici della proposta posso finalmente spiegare a chi rivolgerei questo prodotto:
Per tutte le realtà il cui tema del costo di magazzino è importante e non si possono permettere il lusso di stoccare in eterno
Per tutte le realtà che vogliono avere già lato marketing uno strumento utile a suggerire l'utilizzo di nuovi articoli o articoli poco richiesti.
Per tutte le realtà che già lavorano su articoli di assemblaggio ma gradirebbero una migliore gestione sia di pianificazione che di aggiornamento descrittivo.

Anche in questo caso, un'analisi di fattibilità ed una stima del costo di implementazione andrebbe fatta e potrebbe non tornare utile nel rapporto costo benefici, ma spero che l'incipit sia stato apprezzato.

**Comment by Matteo-Montanari-EOS** [comment]
Abbiamo valutato l'impatto sulle altre app ed è troppo importante, sia per una parziale copertura offerta dalla SPP sia da tutte le altre app che lavorano sulle righe vendita (omaggi, HUM, provvigioni e produzione) che andrebbero integrate con app ponte.
