### ISSUE TITLE
During initial testing, the Document Type “Payment” was used. Is it possible to change that to Credit Memo or something to that effect?

### ISSUE THREAD

**Issue by ja1mes1** [EOS-Solutions/IDEAS#38]
Can the program give us the default document type as a Credit memo and the program give us a  recurrent a default number for the CR?

**Comment by AndreaDiCeglie** [comment]
We suggest to use payments. Cr Memo (but this may vary for countries regulation) should be only used with VAT relevant entries. Cr Memo also should need a document number that you don’t have when compensating.
In any other case Cr-Memo as default can be implemented with a small customization

**Comment by ja1mes1** [comment]
Yes, we don’t use VAT entries. Then its ok a CR-Memo
 <http://www.bts.io/>	 	
Jaime Sanz
Financial department 

Click here for my Business Card <https://www.know.ee/9a6hxUOHbjT>
www.bts.io <http://www.bts.io/> 
 <https://www.linkedin.com/company/business-telecommunications-services/>   <https://twitter.com/BTSio>   <https://www.youtube.com/user/BTSTelecommunication>
Este mensaje es para uso exclusivo de sus destinatarios y puede contener secretos profesionales u otra información confidencial o privilegiada. Cualquier uso desautorizado, copia, publicación o distribución del mimo está prohibida. Si usted no es el destinatario, por favor infórmenos inmediatamente respondiendo a este mensaje y borre este mensaje, incluyendo cualquier adjunto o copias en su sistema.  De conformidad con el RGPD (UE) 2016/679 y la LOPDyGDD 3/2018, le informamos de que esta dirección de correo electrónico y/o cualesquiera otros datos personales que Ud. nos haya facilitado serán tratados por BTS con absoluta confidencialidad y con la única finalidad de prestarle los servicios solicitados, por su condición de cliente, proveedor o porque nos ha solicitado información en algún momento. Dichos datos solo se conservarán durante el tiempo que sea necesario para el cumplimiento de las obligaciones legales. Puede ejercitar sus derechos en cualquier momento mediante correo electrónico a: ***@***.***

This e-mail is for the exclusive use of its recipients and may contain business secrets or other confidential or privileged information. Any unauthorized use, copying, publication or distribution of this e-mail is strictly prohibited. If you are not the intended recipient, please inform us immediately by replying to this e-mail and delete it, including any attachments or copies on your system. In accordance with the RGPD (EU) 2016/679 and the LOPDyGDD 3/2018, we inform you that this e-mail address and/or any other personal data you have provided us with will be treated by BTS with absolute confidentiality and with the only purpose of providing you with the requested services, due to your condition as a client, supplier or because you have requested information from us at any time. These data will only be kept for as long as required to comply with legal obligations. You can exercise your rights at any time by sending an e-mail to: ***@***.***
