### ISSUE TITLE
Power WMS - Migliorare l'esperienza utente delle azioni attività custom

### ISSUE THREAD

**Issue by Gabriele-Colombo-EOS** [EOS-Solutions/IDEAS#381]
La richiesta è quella di rendere più usabile l'esperienza utente relativa alle azioni attività custom che vengono create da BC.
Tradotto si richiede di rendere più velcoce l'input dei vari dati.
La richiesta deriva da un caso reale che ci ha richiesto un cliente: ho creato un’azione che, data in input un’UdC, crea una riga nell’ordine di trasferimento abbinandola in automatico.  

![image](https://github.com/user-attachments/assets/def97dad-7b6d-4911-9f6a-8d52d636c2c7)

![image](https://github.com/user-attachments/assets/ab7af767-691a-47df-8489-69a271e0a53d)

Il problema è che per eseguire l’operazione l’utente deve:
- Cliccare l’azione
- Cliccare edit sul campo
- Cliccare la textbox (non è focussata in automatico)
- Dare in input l’UdC o scansionare
- Cliccare OK per il campo
- Cliccare ancora OK per l’azione

Capite che è molto laborioso, sono 5 click in totale da Power App (e ho un solo campo, pensate con 3/4 o più), quando basterebbe cliccare l’azione, aprire già un campo di input focussato ed editabile e alla scansione, con TAB o Enter dare già conferma e se ad esempio è l’ultimo campo e tutti gli obbligatori sono compilati dare anche l’OK dell’azione.

Tradotto nel mio caso specifico dove ho solo un input obbligatorio, l’operatività diventerebbe:
- Cliccare l’azione
- Scansionare l’UdC
E fine, essendo il campo già focussato, scansionano subito, essendo l’unico campo alla prima scansione si da già in automatico l’OK per far scattare l’azione.

Io eliminerei proprio la parte di edit, fare diventare il modale che si apre una finestra con già lì i vari campi da scansionare, tanto avere vecchio valore e nuovo valore serve a poco secondo me.
Quindi se anche avessi 5 campi in input tutti obbligatori, farli vedere tutti subito in elenco in base alla priorità impostata, già tutti editabili e andare con il focus in ordine, parto col primo, sparo, passa al secondo in automatico e arrivato all'ultimo se tutti compilati dare l'ok. L'utente non deve cliccare niente ma solo eventualmente scansionare. Se poi vuole inserire i dati a mano clicca il campo e fa manualmente. 

Se la spiegazione non è chiara sono a disposizione per farvi vedere meglio cosa intendo.

Grazie mille

**Comment by Matteo-Parlato-EOS** [comment]
Ciao @Gabriele-Colombo-EOS ,
la tua richiesta è lecita ma non possiamo esaudirla del tutto.
 
Il motivo per cui le azioni custom sono suddivise su più schermate (o finestre di dialogo) è dovuto al fatto che abbiamo un limite di ~300 componenti per schermata in PowerApps e tramite i componenti possiamo scriverne di generici e riutilizzarli al fine di riutilizzarli in quanti più scenari possibili e quindi star lontani da quel limite. Creare una seconda pagina di input generica in formato lista andrebbe ad appesantire ulteriormente le schermate (e alcune già sforano il limite di componenti) oltre a non permettermi di eseguire validazione sui dati.
 
Spostarti automaticamente sul parametro successivo non è possibile poichè la funzione SetFocus di PowerApps non permette di interagire con i controlli che fanno parte dei record di una gallery, pertanto questa richiesta non è possibile per motivi tecnici.
 
[SetFocus Limitations](https://learn.microsoft.com/en-us/power-platform/power-fx/reference/function-setfocus#limitations)
 
Possiamo venirti incontro sul focus della casella di testo automatico quando vai in modifica di un certo parametro.
 
La tua richiesta originale può esser risolta interamente andando a realizzare una finestra di dialogo ad hoc con tutti e i soli parametri richiesti dalla funzione che andresti ad eseguire in BC (appesantendo ulteriormente la schermata già satura - e se esegui più funzioni hai diverse schermate di dialogo da sviluppare custom?).

**Comment by Gabriele-Colombo-EOS** [comment]
Ciao @Matteo-Parlato-EOS,
premetto di aver capito poco della spiegazione non conoscendo come si sviluppa lato power app, però ho inteso che in pratica si può fare poco e nulla. 

Riguardo questo punto: _Possiamo venirti incontro sul focus della casella di testo automatico quando vai in modifica di un certo parametro_. tradotto nella pratica come si comporterebbe? Che quando clicco l'edit del parametro in automatico ho il focus sulla casella?

Invece sul fatto di creare finestre di dialogo ad hoc ti direi di no, anche perchè da quel poco che ho capito se iniziamo a creare maschere custom nella power app poi non possiamo più aggiornarla in quanto quando viene fatto il deploy degli aggiornamenti di fatto sovrascrive tutto quello esistente, è corretto?
Se così direi che non ne vale la pena.
