### ISSUE TITLE
FTE - Gestione nuovo flag in anagrafica cliente "Disabilitato addebito bollo" (WI 16620)

### ISSUE THREAD

**Issue by BARBERISLBA** [EOS-Solutions/IDEAS#385]
E' necessario che tutte le fatture emesse verso **clienti PA** non abbiano il riaddebito del bollo, pur avendo la sezione “dati bollo” debitamente compilata.
Dall’altra parte, le fatture a clienti privati e non PA devono riportare l’addebito del bollo, come da prassi nella gran parte delle aziende italiane. 

Vi chiediamo pertanto, se possibile, di aggiornare l’app di modo da permettere di decidere, in base ai setup IVA, non solo se applicare il bollo, ma anche se addebitarlo o meno al cliente (in alternativa,  si puo' prendere a riferimento l’anagrafica del cliente: ove il formato doc. elettronico sia “fattura PA” vi chiediamo di escludere il riaddebito del bollo di default, così da rispettare le vigenti norme fiscali.) 
Per quanto riguarda il bollo a clienti PA, nell’xml deve necessariamente essere compilato il blocco “Dati bollo” in quanto l’articolo IVA Esente 10 richiede l’applicazione dello stesso.
Tuttavia, il bollo NON deve essere riaddebitato al cliente PA (come da normativa vigente sotto riportata).
![SETUP BOLLO 3](https://github.com/user-attachments/assets/b6ccb24d-4215-43b3-9506-b0b26aa6e40b)

Per i clienti non PA deve rimanere quantomeno la possibilità di scegliere se addebitare o meno il bollo in modo automatico (così come è attualmente a sistema).

Se il riaddebito o meno del bollo fosse impostabile in base ai setup IVA (dove ora si indica se un dato incrocio IVA è soggetto a bollo o meno) si darebbe al cliente la possibilità di setuppare il riaddebito del bollo in autonomia, senza costringerlo a interventi manuali nei casi particolari (come quello della NC). 
Oltretutto, faccio presente che se per i clienti non PA il cliente volesse eliminare la riga di riaddebito bollo, il cliente dovrebbe rilasciare la fattura, riaprirla, cancellare la riga di addebito bollo e rilasciare nuovamente la fattura per la registrazione, ma con il rilascio il sistema inserirebbe una nuova riga di riaddebito, generando un circolo vizioso di difficile gestione.

![image
![SETUP BOLLO2](https://github.com/user-attachments/assets/9e77e2e8-5878-4c69-be70-ae5982fdcae6)
](https://github.com/user-attachments/assets/9dfa2d86-1bb8-4ad4-b68e-48b99b9162d0)

**Comment by BARBERISLBA** [comment]
![SETUP BOLLO](https://github.com/user-attachments/assets/91b2cef2-2b72-41c0-b762-8b3b0039b6af)

**Comment by Yuri-Giacchetto-EOS** [comment]
Creazione nuovo flag in anagrafica cliente : "Disabilitato addebito bollo"

- se flag Disabilitato = True in Setup Bollo (FTE)
   --> non cambia nulla, non crea mai la riga nè la espone nell'XML

- se flag Disabilitato = False in Setup Bollo (FTE)
        se flag "Disabilitato addebito bollo" in Anagrafica cliente = TRUE 
        --> non creo la riga ma deve esserci evidenza del bollo nel file XML (Situazione PA)
        se flag "Disabilitato addebito bollo" in Anagrafica cliente = FALSE 
        --> creo la riga nel documento e deve esserci evidenza del bollo nel file XML (situazione attuale)

**Comment by BARBERISLBA** [comment]
Buongiorno Yuri,
grazie degli aggiornamenti la modifica è stata rilasciata ufficialmente posso già scaricarla per fare un test?
Marta

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno @BARBERISLBA.
Quella riportata è l'analisi effettuata e condivisa con il CC.
In questi giorni procederemo con gli sviluppi.
Sarà mia premura avvisarla non appena sarà possibile scaricare l'APP aggiornata.
Saluti, Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Aggiornamento : la modifica è stata ultimata ed è in fase di test.
Il rilascio avverrà quindi a breve.

Buona giornata,
Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Buonasera,
la soluzione verrà rilasciata per le seguenti versioni :

BC14 : 14.0.610
BC23 : 23.0.125
BC24 : 24.0.85
BC25 : 25.0.37

Ciao Yuri
