### ISSUE TITLE
HUM in ordine di trasferimento

### ISSUE THREAD

**Issue by DavidJEOS** [EOS-Solutions/IDEAS#386]
Ciao,

sono in un ambiente di DEMO, sto facendo dei test per ordini di trasferimento con magazzino di partenza che ha le HUM e quello di destinazione che invece non le ha (ubicazione senza collocazioni).
Ho spedito la HUM e ho eseguito il ricevimento, questa è la situazione.
![Mov cont articoloHUM](https://github.com/user-attachments/assets/c90f7c7f-04f4-4e67-b253-db19e84ae624)
L'articolo nei movimenti contabili risulta nel magazzino a cui è stata trasferita la merce.
Mentre l'unità di carico risulta ancora nel magazzino di TRANSITO.
![Unità di carico in TRANSITO](https://github.com/user-attachments/assets/40c34535-d824-4ee6-ba97-004b1ba42a45)
Non si potrebbe risolvere questa situazione che adesso abbiamo da qualche anno?
Se non ho capito male su Gimoka questo bug è già stato risolto.

Fatemi sapere

Saluti

David Jean Pansini

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao non è un bug a mio avviso. Tu devi assegnare le HU alla ricezione all'interno dell'ordine di trasferimento. Hai la packing list ?
In ogni caso come hai visto stiamo introducendo una modifica che dovrebbe coprire questa casistica.

**Comment by Giuliano-Velludo-EOS** [comment]
![image](https://github.com/user-attachments/assets/35ef797c-93db-4f8c-a9dd-3e0450e8a85b)
