### ISSUE TITLE
IPL - Invoicing Plan - Riporto codici CUP e CIG in piano di fatturazione e successivi documenti generati (WI 16623)

### ISSUE THREAD

**Issue by SusannaCamerotto** [EOS-Solutions/IDEAS#389]
Il suggerimento costituisce l'aggiunta di un requisito fondamentale per la fatturazione su gare/progetti cioè i codici CUP (Codice unico progetto) e CIG (Codice identificativo gara) inseriti nell'ordine di vendita. Il cliente chiede obbligatoriamente l'indicazione di questi due codici (comunicati da lui stesso al fornitore) nel caso in cui si stia gestendo una vendita relativa ad una gara o ad un progetto.
Se presenti nell'ordine, la fattura viene rigettata dal cliente se mancante di queste informazioni e, di conseguenza, non verrà mai saldata.

La generazione del piano di fatturazione da ordine di vendita, deve portarsi anche i due codici in oggetto per poi trasferirli alle fatture (di tutte le tipologie) generate con il piano.

I due campi sono standard nella tabella della testata ordine , nella testata delle fatture di vendita e note credito (sia provvisorie che registrate) e sono:
Fattura Project Code (12182, Code[15])
Fattura Tender Code (12183, Code[15])

**Comment by Yuri-Giacchetto-EOS** [comment]
Buonasera Susanna,
lo sviluppo è in corso e a breve procederemo con la pubblicazione dell'APP aggiornata in versione 23,24 e 25

Saluti

**Comment by SusannaCamerotto** [comment]
Buonasera,
grazie mille, avevo intuito dal Webinar sulle novità 😊
Buona serata

Susanna Camerotto
Finance consultant

[Horsa Logo]

Horsa Way srl

Da: Yuri Giacchetto ***@***.***>
Inviato: mercoledì 11 dicembre 2024 17:20
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Susanna Camerotto ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL - Invoicing Plan - Riporto codici CUP e CIG in piano di fatturazione e successivi documenti generati (WI 16623) (Issue #389)


Buonasera Susanna,
lo sviluppo è in corso e a breve procederemo con la pubblicazione dell'APP aggiornata in versione 23,24 e 25

Saluti

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno,
la soluzione verrà rilasciata per le seguenti versioni dell'APP IPL:

BC23 : 23.0.42
BC24 : 24.0.48
BC25 : 25.0.18

Saluti,
Yuri Giacchetto

**Comment by SusannaCamerotto** [comment]
Grazie.
Buone feste 😊

Susanna Camerotto
Finance consultant

[Horsa Logo]

Horsa Way srl

Da: Yuri Giacchetto ***@***.***>
Inviato: mercoledì 18 dicembre 2024 11:38
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Susanna Camerotto ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] IPL - Invoicing Plan - Riporto codici CUP e CIG in piano di fatturazione e successivi documenti generati (WI 16623) (Issue #389)


Buongiorno,
la soluzione verrà rilasciata per le seguenti versioni dell'APP IPL:

BC23 : 23.0.42
BC24 : 24.0.48
BC25 : 25.0.18

Saluti,
Yuri Giacchetto
