### ISSUE TITLE
DCF - DocFinance Connector - possibilità di saltare le scadenze verso DocFinance delle scadenze in sospeso / filtrabili

### ISSUE THREAD

**Issue by ManRiccardo** [EOS-Solutions/IDEAS#394]
Buongiorno,

proponiamo come ideas la possibilità di saltare le scadenze verso DocFinance delle scadenze in sospeso / filtrabili

Grazie,

**Comment by Giuliano-Velludo-EOS** [comment]
Ciao esiste già l'evento OnBeforeExportVendLedgerEntry(VendLedgerEntry, BatchID, Handled); a cui puoi agganciarti per fare il filtro che hai richiesto.
