### ISSUE TITLE
FTE - Possibilità di allegare documenti da DocSolutions sull'Xml delle autofatture di acquisto

### ISSUE THREAD

**Issue by Barbara-Coldani-EOS** [EOS-Solutions/IDEAS#395]
Sembra che la normativa preveda la possibilità di non tenere il cartaceo delle fatture di acquisto estere, se sull'Xml delle autofatture di acquisto viene riportata la scansione del documento cartaceo. 
Si richiede quindi di poter inserire in automatico sull'Xml delle autofatture di acquisto, magari tramite un flag, i files contenuti nel DocSolutions di quella specifica fattura registrata.

**Comment by Giuliano-Velludo-EOS** [comment]
L'app ponte con DocSolutions non esiste potrebbe essere possibile passando per un CDL.
Da valutare un eventuale custom
Ne discutiamo con @Andrea-Di-Ceglie-EOS

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao Barbara, attualmente vediamo due possibili soluzioni :
1. modifica APP EOS, con l'aggiunta di un flag in testata documento (TAB documento elettronico) e l'utilizzo degli allegati documento (no docsolution perchè ci vorrebbe APP Ponte). Verrebbero riportati tutti gli allegati presenti.

2. custom utilizzando l'evento OnWriteAllegati_2_5 della CDU 18123005 EOS063 Outb. Purch. EDoc. Wrt. (https://docs.eos-solutions.it/en/docs/apps-tech/b3b8e132-0ba8-4429-9e94-851829ceb7a3/codeunit/codeunit18123005.html#onwriteallegati_2_5). In questo caso con l'aggiunta della dipendenza all'APP di DocSolutions la gestione sarebbe sempre più semplice.

La terza, che sarebbe l'APP ponte attualmente vorremmo evitarla.

Per favore fai un check con Luca e facci sapere.
Grazie Yuri

**Comment by Barbara-Coldani-EOS** [comment]
Ciao,
Ho parlato con Polenghi, per loro la soluzione migliore è fare un custom.
Mi diceva che ha già scritto a Veronese chiedendo di aprire una nuova CR.

Potete chiudere la mia idea.

Grazie,

Barbara Coldani
Senior Consultant
EOS Solutions
Mail + Teams: ***@***.*** ***@***.***>
P:. | Mob: 3453988173
<https://www.eos-solutions.it>
Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.


________________________________
Da: Yuri Giacchetto ***@***.***>
Inviato: lunedì 25 novembre 2024 14:29
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Barbara Coldani ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] FTE - Possibilità di allegare documenti da DocSolutions sull'Xml delle autofatture di acquisto (Issue #395)


Ciao Barbara, attualmente vediamo due possibili soluzioni :

  1.  modifica APP EOS, con l'aggiunta di un flag in testata documento (TAB documento elettronico) e l'utilizzo degli allegati documento (no docsolution perchè ci vorrebbe APP Ponte). Verrebbero riportati tutti gli allegati presenti.

  2.  custom utilizzando l'evento OnWriteAllegati_2_5 della CDU 18123005 EOS063 Outb. Purch. EDoc. Wrt. (https://docs.eos-solutions.it/en/docs/apps-tech/b3b8e132-0ba8-4429-9e94-851829ceb7a3/codeunit/codeunit18123005.html#onwriteallegati_2_5). In questo caso con l'aggiunta della dipendenza all'APP di DocSolutions la gestione sarebbe sempre più semplice.

La terza, che sarebbe l'APP ponte attualmente vorremmo evitarla.

Per favore fai un check con Luca e facci sapere.
Grazie Yuri

**Comment by Yuri-Giacchetto-EOS** [comment]
Grazie a te del feedback. 
Buona giornata
