### ISSUE TITLE
[FEATURE] Electronic Invoice for San Marino - Support for 'Tipo Merce' and Supplemental XML Submission for San Marino

### ISSUE THREAD

**Issue by Delpixe** [EOS-Solutions/IDEAS#397]
**Is your feature request related to a problem? Please describe.**  
The FTE application currently does not support the management of the "tipo merce" field, which is critical for the passive side of electronic invoicing with San Marino. Additionally, the process requires generating and submitting an additional XML file after registering a purchase invoice or credit note.

**Describe the solution you'd like**  
I would like FTE to be enhanced with the following functionalities:  
1. **Management of the "tipo merce" field:** Add a dedicated field to capture "tipo merce" during the registration of purchase invoices or credit notes.  
2. **Generation and submission of the supplemental XML file:** Enable FTE to automatically generate and send the additional XML file required for compliance with San Marino regulations.  
**_Please note that line 1 received must be the line 1 (line 2 = line 2, line N = line N etc.) into the supplemental XML File_**

4. **Logging and tracking:** Implement a comprehensive logging system to track submission attempts, statuses, and any errors encountered during the process.  
5. **Validation and compliance checks:** Introduce automated controls to ensure the "tipo merce" field and other required data in the supplemental XML file adhere to San Marino’s technical specifications. 
6. **Readable stylesheet:** Include a user-friendly stylesheet to allow users to view the supplemental XML file in a readable format for verification and auditing purposes.  

**Describe alternatives you've considered**  
An alternative would be to develop a fully custom solution for the client to handle these requirements outside of FTE. 
However, this approach would require significant development effort and create inefficiencies in managing separate systems for standard and San Marino-specific invoicing processes.

**Additional context**  
The "tipo merce" field and the supplemental XML file are mandatory for compliance with San Marino’s passive-side invoicing regulations. Failure to address these requirements can result in non-compliance and administrative penalties. 

I am attaching examples of the supplemental XML format, regulatory guidelines, and the desired stylesheet for reference. 

https://www.finanze.sm/pub2/FinanzeSM/Aree-Tematiche/Fatturazione-Elettronica/Documentazione-normativa-e-tecnica.html

i.e. (with the sensitive fields emptied)
![image](https://github.com/user-attachments/assets/f5fa76a8-c281-4322-9c6c-a9fb533f39ba)

**Comment by Yuri-Giacchetto-EOS** [comment]
Rifiutata dopo analisi approfondita e verifiche con CC. 
Suggerita custom + SCT
