### ISSUE TITLE
DocSolutions for Sharepoint - Estendere la gestione DCS alle tabelle di Lines

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#40]
Estendere la funzione alle tabelle di riga. La richiesta è legata alla possibilità di poter collegare allegati alle righe dei documenti ( a.e. Righe di Fatture di acquisto ) e non solo alla testata e alla necessità di popolare alcuni metadati da valori provenienti da campi di riga.

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
DocSolutions factbox can be linked to any table , there is no technical "difference" between headers or "lines".
By default documents Files are attached to Documents header tables, with customization can be linked to any table
