### ISSUE TITLE
App HUM: traduzioni articoli sul prendi righe documenti origine

### ISSUE THREAD

**Issue by AntonioEos** [EOS-Solutions/IDEAS#401]
Ciao a tutti,

è possibile modificare la funzione del "Prendi righe documento origine" dell'assegnazione dell'unità di carico in documenti warehouse per fare in modo che consideri le traduzioni in lingua degli item che si selezionano dalla tabella Item Translation (82)?
Verificando, nella pagina EOS055 Avail. Source Items (18126886, Worksheet) la descrizione non è modificabile, mentre è modificabile a mano nella EOS055.01 HU Content Journal (18126885, Worksheet).
Sarebbe dispendioso per i clienti aggiornare a mano sempre queste descrizioni tradotte in lingua prima della registrazione delle unità di carico per spedizioni warehouse con molte righe.

Antonio

![2024-11-28 11_45_26-Spedizione warehouse - SH000235 (DCN)](https://github.com/user-attachments/assets/8f130b2e-3df5-4c95-8296-1741c651632d)

**Comment by AndreaDiCeglie** [comment]
Ciao,
L'idea di tradurre i dati in tabella non è corretta by design. i dati sul DB rimangono in una sola lingua, le traduzioni sono finalizzate alle stampe.
