### ISSUE TITLE
HUM: informazione quantità da spedire in packing list (WI 16726)

### ISSUE THREAD

**Issue by chiarapergolini** [EOS-Solutions/IDEAS#404]
Nel momento in cui si compila la packing list assegnano le quantità degli gli articoli all'unità di carico creata, non si fa riferimento all'effettiva quantità da inscatolare, ma solo alla quantità totale della riga. Sarebbe opportuno avere una colonna "Quantità da spedire" che faccia riferimento a quella presente sulla riga della spedizione warehouse. 

![image](https://github.com/user-attachments/assets/a90465ba-6552-4cad-b865-ca381d9dbdbe)

Sono da valutare gli impatti di questa modifica con tutti gli scenari di impostazione della packing list. Eventualmente, si potrebbe creare un setup che controlli che la quantità da gestire superi la quantità da spedire. Sarebbe ovviamente da attivare solo nei casi in cui la packing list venga creata dopo il prelievo per la spedizione.

**Comment by AndreaDiCeglie** [comment]
Valutiamo positivamente la possibilità di esporre la Qta da spedire , abbiamo diversi dubbi sull'opportunità di introdurre i controlli suggeriti poichè in diversi scenari potrebbero fallire

**Comment by chiarapergolini** [comment]
Grazie Andrea per la valutazione. Principalmente volevo sottoporvi la mancanza di un'informazione completa, lasciando a voi stabilire che tipo di processi agganciarvi.

**Comment by Mariangela-DeMaio-EOS** [comment]
Released version 24.0.52  "Advanced Logistic Common Library".
