### ISSUE TITLE
Aggiunta eventi calcolo Importo usato (VL) - Dichiarazioni d'intento (VMI)

### ISSUE THREAD

**Issue by CristianCorega-Lutech** [EOS-Solutions/IDEAS#405]
Ciao a tutti,

vi chiedo cortesemente, se possibile, l'aggiunta dei classici eventi OnBefore e OnAfter nella funzione CalcUsedAmount della tabella 18008255 EOS VAT Exemption oppure in altre funzioni più consone. La necessità è quella di poter calcolare in autonomia il valore dei campi "Importo usato (VL)" e "Importo residuo (VL)" della tabella "Dichiarazioni d'intento (VMI)".

Stiamo sviluppando un custom per un cliente in fase di migrazione a BC24 OnPrem e, nella precedente gestione non EOS, il controllo sull'utilizzo delle lettere di intento prendeva in considerazione anche i documenti temporanei (ordini, resi, fatture, note credito, etc..) e i documenti registrati quali carichi e spedizioni. L'obiettivo è di bloccare l'utilizzo della dichiarazione al raggiungimento dell'importo massimo, considerando però anche le tipologie di documenti indicate in precedenza.

Per noi la richiesta è prioritaria in quanto abbiamo riportato tutta la gestione del conteggio ma non riusciamo ad integrarla con gli attuali controlli; potremmo anche procedere con dei controlli indipendenti ma non riusciremmo a coprire tutte le casistiche: il controllo std potrebbe infatti essere più stringente rispetto a quello custom e non abbiamo trovato un modo per aggirarlo.

Se non fosse possibile avere gli eventi in tempi relativamente brevi, vi chiediamo se ci sono altri modi per raggiungere il risultato desiderato sfruttando funzioni/eventi che magari ci sono sfuggiti.
 
Rimango a disposizione per ulteriori informazioni.
Grazie, Cristian

**Comment by AndreaDiCeglie** [comment]
Ciao Cristian, per richieste di nuovi eventi e comunque quando è richiesta una data di scadenza precisa vi chiediamo di aprire un ticket al supporto. Lo scopo di IDEAS è avere solo change request di migliorie e / o nuove funzionalità che possano essere pianificate e gestite con la dovuta calma e prospettiva.
I punti nuovi su IDEAS vengono valutati ogni 2-3 settimane
Chiudo l'IDEA che comunque è valutata positivamente. Apri un ticket e lo evaderemo.
