### ISSUE TITLE
DocSolutions for FileSystem - Apertura File da "Open Location"

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#41]
Consentire l'apertura del file nella Directory direttamente dall' add.-in:

![image](https://user-images.githubusercontent.com/88732191/130195000-510fff6e-4b92-40f9-a856-1d592ae741ad.png)

Attualmente viene solo indicato il percorso in cui si trova il file:

![image](https://user-images.githubusercontent.com/88732191/130194896-edff920f-a3d5-4441-80da-41611787b80e.png)

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
Storage folder are network UNC accessible (for sure) by BC service user from BC application server.
End users may use DocSolutions over the Internet, Mobiles etc without any access to local area network resources.
