### ISSUE TITLE
DocSolutions for Sharepoint - Prevenire l'errore nel caricamento di file con path con spazi finali

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#43]
Prevenire l'errore nel caricamento di file riferiti a path con spazi finali:

![Cattura](https://user-images.githubusercontent.com/88732191/130663714-3083b3dd-0aba-4592-bc06-871268ed064b.PNG)

![Cattura](https://user-images.githubusercontent.com/88732191/130664190-e10a3290-3cde-4b56-a26a-628c2daee030.PNG)

Grazie
Massimo

**Comment by AndreaDiCeglie** [comment]
This is logged as bug, and will be solved through support service
