### ISSUE TITLE
IPL Invoice Plan App - New features (WI 8235)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#44]
Here are new features to improve the IPL App.

- Rename "Impostazione del piano fatture" to "Setup piano fatturazione"
- Remove the "Tipo fattura chiusura" field in the setup page
- Add the IPL posting setup in the 148 page and rename the label
- In the IPL header add the "Importo totale a chiusura" as the total of all the IPL lines, included the closing amount
- From the IP header remove the "Importo da registrare" and move it to the lines by converting it into a FlowField
- From the IP header remove the "Importo da fatturare" and move it to the lines by converting it into a FlowField
- Rename "Importo residuo" to "Importo totale fatturato"
- Remove "Completamente fatturato"
- Remove "Fattura chiusura rettificata"
- Remove "Importo da registrare"
- Remove the "Create single invoice" boolean in the report
- Remove, if not needed, the "Aggiorna allocazione posizione"
- Add the link to the "EOS IPL Invoice Plan List" page
- Remove the linke "Lista righe pianificazione fatturazione"

These are the needed fields in the "EOS IPL Invoice Plan Line List (18091206, List)" page:

- Tipo fattura
- Nr. commessa
- Nr. Piano fatturazione
- Nr documento origine
- Nr Origine
- Nome
- Cod valuta
- Nr. riga
- Data di registrazione
- Quota in %
- Importo
- Cat. reg. articolo/servizio
- Fattura registrata
- Esegui azione
- Documento da Registrare
- Descrizione
- Testo esiste

[Piano di fatturazione.pdf](https://github.com/EOS-Solutions/IDEAS/files/7103658/Piano.di.fatturazione.pdf)

**Comment by alessandrovecchio** [comment]
Ciao, la richiesta è si è poi evoluta in una serie di migliorie e refactoring seguiti da Francesco Petrera e Lorenzo Trepan. Chiudo la issue perchè il WI allegato sarebbe fuorviante.
