### ISSUE TITLE
DocSolutions for FileSystem - Percorso errato messaggio informativo.

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#46]
Il valore di directory name viene indicato con una slash in più.
 
![Cattura](https://user-images.githubusercontent.com/88732191/134381343-b43b2555-a9a5-41e7-bbcb-0d03e1d58316.PNG)

**Comment by AndreaDiCeglie** [comment]
L'errore non si riscontra, il doppio slash è probabilmente dato da un errore del  setup che contiene il pattern per la creazione della cartella

![image](https://user-images.githubusercontent.com/33353905/149293446-01c810a4-a3b4-4a79-b56f-197d08186632.png)
