### ISSUE TITLE
Plant Maintenance direct posting of "Machine Journal Line" without insert of record

### ISSUE THREAD

**Issue by lucaeos** [EOS-Solutions/IDEAS#47]
Create new function/codeunit to allow posting of Machine Journal Line without inserting record.

In practise like we do with codeunit "Item Jnl.-Post Line" filling "Item Journal Line" and calling RunWithCheck
with record passed in memory.

**Comment by f0ffee** [comment]
Starting from version 20.0.21 (BC20 and up) it is possible to call the Codeunit.Run method for both posting codeunits (which is to say, both machine journal lines and work journal lines are supported). The passed record does not need to be inserted in the database. Thank you for your suggestion.
