### ISSUE TITLE
EX009 ADR Add text in the lower body in Sales Invoices and Shipments

### ISSUE THREAD

**Issue by PaoloCarimati** [EOS-Solutions/IDEAS#5]
We ask for the possibility of automatically adding texts in each ADR report. Texts in the document language and with start and end date of validity.
The text will be added after all lines on the last page.
For example, this can be used to communicate company closing dates.

**Comment by AndreaDiCeglie** [comment]
Delivered with advanced text feature http://helpbc.eos-solutions.it/main.aspx?lang=en&content=ENU_AdvDocReporting-AdvText.html
