### ISSUE TITLE
Block location ledger entries based on setup

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#50]
Many customers ask me to inhibit item transactions on specific locations in order to keep track of existing locations but not allow users to post.

I'd like a tool to activate/deactivate the item transactions according to the setup applied to each location, e.g. a boolean field "Blocked". This field could be then be controlled by an EDS function (according to customs applied to the clients).
The blocked value should then be checked before the Item Ledger Entry posting procedure.

An additional feature could be the one of having a dedicated table in which list which locations can't be used in specific documents, such as sales orders, purchase order and so on. This way, the block could then be applied to the tables before the posting, e.g. while inserting new lines.

**Comment by Giuliano-Velludo-EOS** [comment]
Al momento non esistono le condizioni per la creazione di una nuova app con questa singola funzionalità.
