### ISSUE TITLE
Controllo Plafond VMI

### ISSUE THREAD

**Issue by ErikaC82** [EOS-Solutions/IDEAS#51]
Sarebbe utile aggiungere una colonna simile a " Verifica plafond su carichi"  per poter verificare il plafond sugli Ordini 
Verifica plafond su Ordini  -> può valorizzare "Importo plafond non fatturato (VL)" o un campo "Importo plafond ordini (VL)"

**Comment by alessandrovecchio** [comment]
Buongiorno, dopo un confronto interno abbiamo deciso di non implementare il suggerimento nel funzionamento della nostra app standard.
Se decideste di procedere in qualche modo con un custom restiamo a disposizione per il supporto relativo.

Saluti
