### ISSUE TITLE
Add item EDS "Sales Blocked" and "Purchasing Blocked" functions (WI 9094)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#52]
In every new BC project I develop two EDS functions in order to activate/deactivate the "Sales Blocked" and "Purchasing Blocked" item field.
These two new fields are useful in order to block the End Of Life items and the related features are requested by the customers during the workflow design.

My idea is to add to the standard EDS setup the four functions:

- Activate Purchasing Blocked
- Deactivate Purchasing Blocked
- Activate Sales Blocked
- Deactivate Sales Blocked

**Comment by ElioCometto** [comment]
Change done. 
App version with update: 19.0.40
