### ISSUE TITLE
PRQ: Add fixed asset lines to EOS Purchase Requests

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#54]
Some customers are asking to manage the Fixed Assets in the PRQ lines.

The request is to add this type of line to the PRQ lines in order to manage the same process as Items and G/L Accounts.

**Comment by AndreaDiCeglie** [comment]
Add Fixed Asset and Resources too

**Comment by Chuucommie** [comment]
Implemented Fixed Assets and Resources
