### ISSUE TITLE
APP EX003 Data Security - Percorsi di stato con filtro su tabella origine

### ISSUE THREAD

**Issue by LMONTEOS** [EOS-Solutions/IDEAS#57]
L'idea è quella di poter attivare un filtro (sulla tabella Origine) nei percorsi Cambio stato EDS affinchè si possano avere workflow differenti a seconda di condizioni legate alla tipologia di dati legati.

Esempio: Workflow approvazione articoli.
ES1: In base alla Categoria Articolo, avere differenti Workflow approvativi
ES2: In base al Sistema di rifornimento e Metodo di Riordino attivare controlli diffenti

Esempio: Workflow ODV
ES1: in base alla Classe Documento attivare certi tipi di controlli (classe ricambi piuttosto che prodotti finiti)

![image](https://user-images.githubusercontent.com/94471141/142022559-cb43a13b-a30b-4918-ba75-144843ec2ac4.png)

**Comment by AndreaDiCeglie** [comment]
Al cambio dei valori di uno di questi campi (Cat Articolo o Classe di Documento) cosa fare se è già assegnato uno stato di EDS e il workflow è in corso ?.
Il risultato può essere quello di avere stati inconsistenti

**Comment by LMONTEOS** [comment]
Corretta la domanda: se ho impostato un campo con un valore e ne ho vincolato un percorso, al cambiamento di tale valore, il percorso risulta essere "non corretto".
La soluzione è dare errore al cambio di valore del campo presente "nelle regole" che decidono il percorso stesso.

__________________________________________________________________________________
Luca Montanari
Senior Consultant



EOS Solutions
mail: ***@***.******@***.***>

legal mail: ***@***.******@***.***>

Via 2 Giugno 1946, n. 8 (40033) Casalecchio di Reno (BO)

Mob:+39 348 7685684

www.eos-solutions.it<http://www.eos-solutions.it/>

__________________________________________________________________________________

Da: Andrea Di Ceglie ***@***.***>
Inviato: mercoledì 9 marzo 2022 12:22
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Luca Montanari ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] APP EX003 Data Security - Percorsi di stato con filtro su tabella origine (Issue #57)


Al cambio dei valori di uno di questi campi (Cat Articolo o Classe di Documento) cosa fare se è già assegnato uno stato di EDS e il workflow è in corso ?.
Il risultato può essere quello di avere stati inconsistenti

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F57%23issuecomment-1062819427&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C9ce52fa43bf64d7ec20408da01bf0ecf%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637824217350597066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tGAxUqgD3SHTsrzST6F9dUbYY1fMexCeUxhq%2B%2F4RyGo%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWQYHZMMILPEZBCPTMGB67TU7CCWDANCNFSM5IEVHAHQ&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C9ce52fa43bf64d7ec20408da01bf0ecf%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637824217350597066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NGO3VkTTPPSZsNE9rMIJDy9xpEaay3hYHg9hTcigSFE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C9ce52fa43bf64d7ec20408da01bf0ecf%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637824217350753319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WlOp1e%2Foa90w%2FU9Ua4ueMob9000in7r1k8GjVpavIeE%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C9ce52fa43bf64d7ec20408da01bf0ecf%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637824217350753319%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=vLSRElzwS7bz%2FLPbKNzggESi2B4U4mY59vJy%2Fm56nas%3D&reserved=0>.

**Comment by AndreaDiCeglie** [comment]
Sarebbe bello, tecnicamente però richiederebbe che EDS si sottoscrivesse al VLD di ogni campo di BC. E' lo stesso motivo per cui fin ora non abbiamo implementato in EDS la "field level security".
Ci sono partner che hanno implementato soluzioni del genere. Di fatto hanno un motore che genera una grossa codeunit custom che si sottoscrive alle tabelle/campi messi a setup. 
Alla fine è un generatore di custom che si appoggiano ad un core standard.
Non impossibile da realizzare ma comunque impegnativo e non Plug & Play.

Visto il relativamente poco vantaggio per questa feature di EDS probabilmente risulta più vantaggioso svilupparla interamente come custom.

**Comment by LMONTEOS** [comment]
Sottoscrivo questa affermazione --> Alla fine è un generatore di custom che si appoggiano ad un core standard.
Ad ogni modo per un cliente, abbiamo stimato di farla: magari una volta completata ci possiamo risentire.
__________________________________________________________________________________
Luca Montanari
Senior Consultant



EOS Solutions
mail: ***@***.******@***.***>

legal mail: ***@***.******@***.***>

Via 2 Giugno 1946, n. 8 (40033) Casalecchio di Reno (BO)

Mob:+39 348 7685684

www.eos-solutions.it<http://www.eos-solutions.it/>

__________________________________________________________________________________

Da: Andrea Di Ceglie ***@***.***>
Inviato: giovedì 10 marzo 2022 14:53
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Luca Montanari ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] APP EX003 Data Security - Percorsi di stato con filtro su tabella origine (Issue #57)


Sarebbe bello, tecnicamente però richiederebbe che EDS si sottoscrivesse al VLD di ogni campo di BC. E' lo stesso motivo per cui fin ora non abbiamo implementato in EDS la "field level security".
Ci sono partner che hanno implementato soluzioni del genere. Di fatto hanno un motore che genera una grossa codeunit custom che si sottoscrive alle tabelle/campi messi a setup.
Alla fine è un generatore di custom che si appoggiano ad un core standard.
Non impossibile da realizzare ma comunque impegnativo e non Plug & Play.

Visto il relativamente poco vantaggio per questa feature di EDS probabilmente risulta più vantaggioso svilupparla interamente come custom.

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F57%23issuecomment-1064086937&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C813d620f140647647cd908da029d6756%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637825172314918692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ECfSSLMYDOZYneN36Y6ax0YxGawxaTqBH1dh3OEGT3E%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAWQYHZJBAXGACIYNF2L4DATU7H5ELANCNFSM5IEVHAHQ&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C813d620f140647647cd908da029d6756%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637825172314918692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=hFhaXw708zh44ChjdRTF3UmgLkixGWBqaOIxoViJgws%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C813d620f140647647cd908da029d6756%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637825172314918692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Z63plKVPfXRVYjlJsW4EhURJaL2Q33IIKmUV1ecjeEg%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cluca.montanari%40eos-solutions.it%7C813d620f140647647cd908da029d6756%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637825172314918692%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=yUWF%2BQEbcsM3D6I8SICDYw4VqBYhvQC%2BbFarZN4O6BA%3D&reserved=0>.
