### ISSUE TITLE
generazione automatica autofatture da Fattura acquisto extraUE

### ISSUE THREAD

**Issue by ElenaStaffolani** [EOS-Solutions/IDEAS#58]
Desidereremmo un automatismo che generi l’autofattura a fronte della registrazione in Fuori campo iva relativa al fornitore per i seguenti casi: TD17 e TD19 
evitando all’utente la doppia registrazione per un unico documento.

**Comment by AndreaDiCeglie** [comment]
Buongiorno, abbiamo analizzato la questione e riteniamo che fiscalmente sia corretto gestire 2 documenti distinti, la fattura estera FC IVA e poi l'autofattura. Di conseguenza non implementeremo quanto richiesto
