### ISSUE TITLE
DocSolutions for Sharepoint - Attach on multiple records simultaneously

### ISSUE THREAD

**Issue by massimocisco** [EOS-Solutions/IDEAS#60]
Often there is a need to attach the same documents to multiple filtered or selected records in Businesse Central.
But the attachment is loaded only in the first selected record.

![Cattura](https://user-images.githubusercontent.com/88732191/142734529-8575db05-2e67-4826-9f67-30e839a80b87.PNG)

**Comment by AndreaDiCeglie** [comment]
Dragging multiple files with transfer of metadata and preview i inconsistent from a design point of view.
Multiple values cannot be showed in the preview page grouped in one record.

Example:
Setup Item
Transfer Field Item Category to Sharepoint custom columns
Preview : On
