### ISSUE TITLE
app Packing list e HUM - enhancement

### ISSUE THREAD

**Issue by DavidJEOS** [EOS-Solutions/IDEAS#61]
Se assegno una qtà da ricevere inferiore alla qtà in riga il sistema con il suggerimento imballaggio si disinteressa della qtà da ricevere, crea tante unità di carico quanto sono quelle che soddisfano la qtà in riga. L'utente può procedere solo a cancellare unità di carico per unità di carico procedendo manualmente nell'operazione.
Sarebbe bene che il sistema ragionasse sulla qtà da ricevere inserita dall'utente e non sulla qtà totale sulla riga ordine/carico warehouse

**Comment by AndreaDiCeglie** [comment]
La richiesta è chiara ma per questioni funzionali non può essere realizzata come richiesto poichè ingenera processi contraddittori.
E' in esame una soluzione alternativa a quella proposta che consenta comunque di soddisfare il bisogno iniziale
