### ISSUE TITLE
VMI - implementazione controllo preventivo su fatture in sospeso (WI 7856)

### ISSUE THREAD

**Issue by FedericoEos93** [EOS-Solutions/IDEAS#64]
si propone una miglioria della stampa dei registri iva vmi:

![vmi 1](https://user-images.githubusercontent.com/85099759/143478629-c97f1f46-e249-4ad2-8dd0-7a66eca9d13c.png)

infatti in occasione di questa stampa non viene effettuato il controllo di quelle fatture in bozza che però hanno già occupato un numero di serie iva. controllo che invece avviene al momento di calcolo della liquidazione periodica:

![vmi 2](https://user-images.githubusercontent.com/85099759/143478737-f68c0db2-37aa-41ba-80aa-5bb401813f4e.png)

**Comment by alessandrovecchio** [comment]
Ciao, da un test su ambiente **integration** il controllo segnalato sembra esere già presente per la stampa "Registro fiscale IVA (VMI)" come per la liquidazione IVA. Di default:
- richiede conferma a procedere se la sta,pa non è definitiva
- blocca con un errore se la stampa è definitiva
essite un evento per modificare la severità.

Es. società DELBOTEAM1, "Registro acquisti extra UE", mese dicembre 2021

**Comment by FedericoEos93** [comment]
Buonasera Alessandro,

Sì confermo che è stato risolto.

Grazie
