### ISSUE TITLE
CVS - stampa valuta locale cliente estero (8232)

### ISSUE THREAD

**Issue by FedericoEos93** [EOS-Solutions/IDEAS#65]
si propone di modificare il report CVS estratto conto (18123355) in maniera tale da mostrare il codice valuta utilizzato per il documento invece che quello locale:

![image](https://user-images.githubusercontent.com/85099759/143603730-74dac02f-d3db-4133-a29f-21bbdd2c803c.png)

**Comment by Chuucommie** [comment]
Ciao,

La modifica è stata effettuata e pubblicata per BC19, BC20 e BC21 nelle versioni 19.0.25, 20.0.18 e 21.0.2

Saluti,
Ricardo
