### ISSUE TITLE
Errore in funzione calcolo giacenze Reg. Inv. Fisico

### ISSUE THREAD

**Issue by FedericoEos93** [EOS-Solutions/IDEAS#66]
Effettuando una registrazione di inventario fisico nella società doit degli ambienti labs si è notato il seguente malfunzionamento relativo ai filtri data: in breve sembra non funzionare.

articolo 1850:

 
![image](https://user-images.githubusercontent.com/85099759/146181663-23f37e42-36e7-4496-9894-a747775e273c.png)

Registrazione inventario fisico con filtro al 30/06:

![image](https://user-images.githubusercontent.com/85099759/146182317-39e1e472-0cb1-42bc-9790-0990bd15a5c7.png)

![image](https://user-images.githubusercontent.com/85099759/146182306-6b06d0c6-f7e7-4298-ac43-3b21be4f6923.png)

Giustamente il programma suggerisce una quantità parti a 15.

Registrazione con filtro al 15/06:

 
![image](https://user-images.githubusercontent.com/85099759/146181787-bf5fb3c1-b754-40f7-8ab1-f768895ea49c.png)

![image](https://user-images.githubusercontent.com/85099759/146182433-1f44f6c7-1e04-4347-80ea-e27fa12a15a3.png)

Mi sarei aspettato una quantità pari a 10 mentre propone sempre 15.

**Comment by AndreaDiCeglie** [comment]
Da quanto si evince dalle immagini si tratta di un programma standard e non EOS.
Aggiungo che su IDEAS vanno proposte migliorie, idee change request e non malfunzionamenti / bug.
In questo caso potete aprire un ticket a MS
