### ISSUE TITLE
Abilitazione Variante in maniera ibrida per l'app CFG

### ISSUE THREAD

**Issue by DavidJEOS** [EOS-Solutions/IDEAS#67]
La richiesta è la seguente:

possibilità di gestire la variante 365BC sull'app CFG non a livello di setup generale ma avere una gestione ibrida che interessa l'articolo specifico. La logica dovrebbe essere la seguente:
Aggiunta di un nuovo campo custom sull'anagrafica articolo che segua le stesse logiche del campo setup variante, ma queste eseguirle solo sugli articoli che sono abilitati a questa gestione, in modo che se l'articolo di partenza è quello sarà possibile gestire da quel momento in poi su quell'articolo solo la configurazione di varianti.
Questo secondo l'idea che:
- Si parta da un articolo neutro
- Da questo vengano staccati articoli nuovi configurati
- Su questi ultimi abilitata la gestione della variante.
- Nel momento in cui si parte da questi, gli articoli creati saranno solo varianti, in modo da poter sfruttare anche la gestione di diverse fasi di lavoro, non che DB, per ottenere lo stesso articolo ma come variante che è soggetta ad azioni o tenori di prodotto differente. 
Il flusso dovrebbe essere il seguente: 
a.	A livello di setup rimane la gestione articolo.
b.	Inserimento articolo neutro e creazione del nuovo articolo come da standard.
c.	Attivazione flag creazione varianti sul nuovo articolo creato.
d.	Quando si reinserisce l’articolo appena creato con il flag variante, il sistema dovrebbe creare un altro articolo neutro (con specifico numeratore), creare una variante e ricopiarne i dati del configuratore nella variante e poi cancellare l’articolo neutro creato appositamente per la gestione.

Spero di essere risultato chiaro nella spiegazione

Grazie

David

**Comment by AndreaDiCeglie** [comment]
La richiesta è già stata valutata più volte (con riferimento allo stesso progetto) .
La modifica è estremamente costosa e invasiva e rischia di impattare tutto il parco installato.
Spostare l'opzione crea variante / crea articolo dal setup generale all'articolo neutro è un cambio fondamentale di design dell'app.
Verrà valutato in futuro ma non è prevista alcuna implementazione a breve
