### ISSUE TITLE
APP (CMS) - Creazione movimenti FIRR provvisori in tabella movimenti contributi (WI 8229)

### ISSUE THREAD

**Issue by agtmartino** [EOS-Solutions/IDEAS#68]
Ad oggi se non si imposta l’opzione “Registra” è possibile solo ottenere una stampa PDF o EXCEL e non è possibile visualizzare i movimenti contributi temporanei e magari eseguire piccoli aggiustamenti.

![Report Firr](https://user-images.githubusercontent.com/96775970/147563994-54ffdbb4-5525-4f12-9634-4ac4437942d7.jpg)

Attivando l’opzione registra il sistema procede con la registrazione e non è possibile effettuare modifiche agli importi calcolati senza effettuare rettifiche contabili.

La richiesta è di poter produrre i movimenti contributi (CMS) in modalità provvisoria avendo la possibilità di intervenire sull’Importo contributo (VL) per poi renderli definitivi con le consuete modalità implementate per i movimenti contributi enasarco

![Enasarco](https://user-images.githubusercontent.com/96775970/147563206-df6a825d-6598-4beb-875b-3f08101f5d3e.jpg)

**Comment by AndreaDiCeglie** [comment]
La proposta è stata valutata positivamente ed assegnata una priorità bassa. Per il momento non è pianificata per lo sviluppo, verrà riconsiderata in futuro
