### ISSUE TITLE
EX086 MPL - Permettere l'impostazione dei filtri di default sulla pagina "EOS086 Sequence Planning" (70491931)

### ISSUE THREAD

**Issue by Paolo-Carimati-EOS** [EOS-Solutions/IDEAS#69]
La richiesta servirebbe per consentire di aprire il “Pianificatore Sequenziale” dalla lista delle “Aree Produzione” oppure dalla lista dei “Centri di lavoro” aggiungendo un’azione al menu “Pianificazione”.

![image](https://user-images.githubusercontent.com/72973520/147741277-24ceead2-3d26-41eb-928d-b5e54aaee832.png)

Richiesta da Doriano Ponzo

**Comment by Giuliano-Velludo-EOS** [comment]
E' stato aperto un wi 7576 diversi mesi fà ed è assegnato a Mirko.
