### ISSUE TITLE
OVR spedizioni eccesso difetto articoli gestiti a tracciabilità

### ISSUE THREAD

**Issue by stefanocorradinidoit** [EOS-Solutions/IDEAS#71]
Il setup di under & over delivery non ha nessun effetto se l'articolo è gestito a tracciabilità Nr. lotto specifico in quanto anche se è possibile modificare la quantità sulla spedizione warehouse non si riesce a collegare una quantità superiore su uno o più lotti disponibili.
Per meglio dire nella pagina tracciabilità è possibile selezionare anche una quantità maggiore ma poi in fase di registrazione esce il messaggio "impossibile collegare più di xxxxxxxx unità".

**Comment by Giuliano-Velludo-EOS** [comment]
Far gestire la tracciabilità All'App OVR sarebbe possibile solo in caso di utilizzo di un solo lotto. In situazioni multi lotto a ns. avviso la cosa non si può fare in modo automatico. Non viene prevista l'implementazione dell'App.
