### ISSUE TITLE
No commission after certain date

### ISSUE THREAD

**Issue by hueiyik** [EOS-Solutions/IDEAS#72]
**Is your feature request related to a problem? Please describe.**
Normally we do not want to pay salesperson when the customer is 120 days due. It doesn't make sense to pay salespeople if their customer pays so late (they are not doing their job)

**Describe the solution you'd like**
After x number days invoice posted and payment not received, commission is 0. It's a standard feature that is missing from this great app.

**Describe alternatives you've considered**

**Additional context**

**Comment by alessandrovecchio** [comment]
Hi, we decided to not include this feature in standard app functionality.
As suggestion, you can create and schedule a custom reports that starting from CMS entries checks if payment is overdue and that set to TRUE flag Exclude.
The other option that maybe is more complicated, is to act with a event during settlement process introducing this custom logic.

Regards
