### ISSUE TITLE
App VMI ricerca anche su campi NOME e P.IVA page 18008255

### ISSUE THREAD

**Issue by ErikaC82** [EOS-Solutions/IDEAS#73]
Si richiede la possibilità di effettuare la ricerca anche sui campi NOME e P.IVA ( campi attualmente calcolati dalla Source no)

**Comment by AndreaDiCeglie** [comment]
Page 18008255 "EOS VAT Exemption Card" is a CARD and cannot be implemented a filter.
You are probably referring to the list, we identified this as low priority request
