### ISSUE TITLE
MES check appartenenza area di produzione con riga ciclo

### ISSUE THREAD

**Issue by G14nM4rc0** [EOS-Solutions/IDEAS#75]
**As-Is**
La versione attuale dell'app del MES permette di avviare e chiudere delle fasi con area di produzione diversa rispetto al ciclo dell’ordine di produzione.
**Richiesta:**
poter definire, tramite un setup, se è possibile o meno consuntivare dei movimenti con area di produzione diversa rispetto al ciclo dell'ordine di produzione.
**Soluzione proposta:**
Il Setup può essere fatto a livello di area di produzione aggiungendo un parametro che pilota tale controllo. Se il controllo è attivo l'app del MES, tramite la pagina EOS 070 MES Barcode Output (18122704, ListPlus), non deve permette la registrazione bloccando l'utente in fase di registrazione.

caso di riferimento: CAS-29931-Y2K0C8

**Comment by AndreaDiCeglie** [comment]
Since this is allowed by standard it can be realized as customization (or in standard app).
As new feature for the standard app we assigned a low priority

**Comment by AndreaDiCeglie** [comment]
won't fix
