### ISSUE TITLE
EX047 Over- and Under-Delivery Quantities - aggiungere campi su Sales Order Archive (WI 9062)

### ISSUE THREAD

**Issue by nmoreggio** [EOS-Solutions/IDEAS#78]
Mi è capitato di dover verificare se in una precedente versione di un ordine di vendita una riga fosse stata chiusa oppure no.
Non ho potuto farlo perchè apparentemente manca il campo in tabella.
Sarebbe opportuno che i campi dell'app venissero replicati e salvati anche negli Archivi Ordini vendita.
NB: non ho ancora testato se, ripristinando una precedente versione dell'ordine, una riga chiusa venisse riaperta o viceversa.

**Comment by Mariangela-DeMaio-EOS** [comment]
Released OnPrem the following versions of the app EX047 "Over- and Under-Delivery Quantities":
20.0.6
19.0.38
18.0.48
18.3.14
