### ISSUE TITLE
GetYourBill2BC

### ISSUE THREAD

**Issue by nicola-myo** [EOS-Solutions/IDEAS#8]
Load and manage XML files (ITA Electronic Invoices) from the GetYourBill payment service (https://www.getyourbill.com/) to BC

**Additional context**
Already implemented in NAV 2015

**Comment by mamutand** [comment]
Ho una richiesta cliente, che vorrebbe leggere file XML (sigillati) creati dalle casse RT (registrazione telematica) e mandato all´agenzia delle entrate. Non credo sia possibile leggere i file diretti, ma l´AdE offre interfaccie web per leggere quei dati, ma non ho capito bene, se per usarla si dovrebbe certificare. 
@nicola-myo  getyourbill sarebbe l´intermediario certificato a cui BC si potrebbe aggiancare per recuperare i dati dall´agenzia delle entrate?

**Comment by nicola-myo** [comment]
> 
> 
> Ho una richiesta cliente, che vorrebbe leggere file XML (sigillati) creati dalle casse RT (registrazione telematica) e mandato all´agenzia delle entrate. Non credo sia possibile leggere i file diretti, ma l´AdE offre interfaccie web per leggere quei dati, ma non ho capito bene, se per usarla si dovrebbe certificare.
> @nicola-myo getyourbill sarebbe l´intermediario certificato a cui BC si potrebbe aggiancare per recuperare i dati dall´agenzia delle entrate?

Si dovrebbe chiedere direttamente a GetYourBill. Da quanto so, é GetYourBill a generare l'XML e ad inviarlo sia all'agenzia delle entrate che al cliente (quello che emette la fattura), che poi lo da in pasto a NAV. Scondo me si dovrebbe chiedere al gestore della cassa RT se prevede di esportare il file XML della fattura da qualche parte (alla fine é la cassa che lo genera). La funzione NAV di GetYourBill a quel punto funzionerebbe.

**Comment by AndreaDiCeglie** [comment]
After evaluation from executive board we decided not to implement. re-evaluation in future is appliable
