### ISSUE TITLE
App CDL - Classi documento acquisto: Possibilità di impostare nr serie diverso per le CWS

### ISSUE THREAD

**Issue by mattiaoggioni** [EOS-Solutions/IDEAS#80]
Come avviene già per i nr di serie delle spedizioni, si richiede di aggiungere un campo per poter impostare il nr di serie diverso per le CWS registrate.
Sarebbe utile sia per le classi di acquisto e sia per le classi di vendita

nel caso delle classi di acquisto sarebbe la CWS legata alla spedizione di reso acquisto registrata

![image](https://user-images.githubusercontent.com/98746220/151787777-be494748-f678-4e66-91b3-3d8ef8a17234.png)
![Immagine](https://user-images.githubusercontent.com/98746220/151787823-b12409c1-8d2d-4f0d-8b98-77dfcea7025e.png)

**Comment by AndreaDiCeglie** [comment]
Since its possible to combine different document classess in one CWS is not clear how to manage class selection on CWS

**Comment by mattiaoggioni** [comment]
Ciao Andrea,
nel caso del cliente in questione (Fiocchi) lo userebbero solo per i resi a fornitore e per questi documenti non vengono fatte spedizioni whse, ma solo spedizioni dirette tramite la registrazione del reso

In questo caso quindi mi aspetto che la spedizione vendita registrata e la spedizione CWS siano sempre 1-1

Non si può eventualmente pilotare questa integrazione solo se si usano le spedizioni dirette e/o nella spedizione whse ci sono documenti con la stessa classe?


Saluti,

Mattia Oggioni

Consultant



EOS Solutions

Bologna
Milano

Bolzano
Padova

Innsbruck
Perugia


mail: ***@***.******@***.***>

legal mail: ***@***.******@***.***>

Viale Colleoni 11, I-20864 Agrate Brianza (MB)

T: +39 02 83508100

F: +39 0471 319699

www.eos-solutions.it<http://www.eos-solutions.it/>


[http://www.eos-solutions.it/sig/firma.png]

Le informazioni contenute in questo messaggio sono intese per i soli destinatari indicati. Il contenuto (inclusi tutti gli allegati) è riservato e personale. Qualora Lei non risultasse tra i destinatari indicati non ha il diritto di utilizzare, pubblicare, distribuire, copiare o stampare le informazioni del messaggio. Se il messaggio Le fosse pervenuto per errore, La invitiamo ad eliminarlo dal Suo sistema (compreso eventuali copie), informando il mittente dell'errore.
This e-mail (and attachments, if any) is confidential and access by anyone other than the addressee(s) is unauthorized. If you are not the intended recipient, any disclosure, copying, forwarding, or distribution of this e-mail is prohibited and immediate deletion should be effected.  We would appreciate your notifying the sender immediately should you become aware of any instances of such occurrence.


Da: Andrea Di Ceglie ***@***.***>
Inviato: mercoledì 16 febbraio 2022 16:04
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Mattia Oggioni ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] App CDL - Classi documento acquisto: Possibilità di impostare nr serie diverso per le CWS (Issue #80)


Since its possible to combine different document classess in one CWS is not clear how to manage class selection on CWS

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F80%23issuecomment-1041586535&data=04%7C01%7CMattia.Oggioni%40eos-solutions.it%7C3ce302f4009d42c1067808d9f15da260%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806206746515902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tO0OkwqonW5OpFxxjchpALC84fJTK1CZtrkA7S2eYTI%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXRL63FS3H55OT2WL53VAGDU3O4HHANCNFSM5NGAOMXA&data=04%7C01%7CMattia.Oggioni%40eos-solutions.it%7C3ce302f4009d42c1067808d9f15da260%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806206746515902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SO8aGJ5N%2FqQ2IbSW%2B8FXmwnizZFOTKKG8GIz4fEE%2FgE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMattia.Oggioni%40eos-solutions.it%7C3ce302f4009d42c1067808d9f15da260%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806206746515902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=b1x6WOijKZ1BNElsNgldjZ0OiHXu%2F%2FeOmBgUK28sDqE%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMattia.Oggioni%40eos-solutions.it%7C3ce302f4009d42c1067808d9f15da260%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806206746515902%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=YMWq7heEqgF08Bj%2BxPs093%2BoIzQX0RnM3fHA8LN4DJU%3D&reserved=0>.
