### ISSUE TITLE
Purch. Rcpt. Lines vuote

### ISSUE THREAD

**Issue by nmoreggio** [EOS-Solutions/IDEAS#81]
A fronte di un carico warehouse contenente righe di più ordini di acquisto, BC **a standard** crea _n_ Purch. Rcpt. Header, una per ogni diverso ordine di acquisto presente nel carico warehouse. Inoltre, ciascuna Purch. Rcpt. Header contiene tutte le righe presenti nel carico warehouse, valorizzando la quantità solo per quelle relative all'ordine di acquisto a cui la Purch. Rcpt. Header fa riferimento.
Questo comportamento rende la consultazione dei documenti registrati molto difficoltosa. 
Nell'immagine sotto, a fronte della stessa bolla fornitore sono state registrate 7 testate
![image](https://user-images.githubusercontent.com/98471651/151830762-4529de9d-e100-4eee-9d51-fb4f9b6a764e.png)

La situazione nelle righe di ciascun documento è la seguente:
![image](https://user-images.githubusercontent.com/98471651/151831008-4224a866-60d6-4ec2-86eb-1d964af3572f.png)
![image](https://user-images.githubusercontent.com/98471651/151831088-0b0a6174-6b66-46a3-8238-211603027464.png)

**Comment by AndreaDiCeglie** [comment]
"Questo comportamento rende la consultazione dei documenti registrati molto difficoltosa."
non è chiara la richiesta

**Comment by nmoreggio** [comment]
> 

Ciao, la richiesta è:
è possibile eseguire una unica registrazione (Purchase Receipt Header) per un carico warehouse, in modo da avere tutte le righe del carico warehouse all'interno della stessa Purchase Receipt Header?
In alternativa, è possibile avere uno strumento di ricerca righe di carico che aggreghi le informazioni (ad es. una page stile "Riepilogo documenti vendita")?

**Comment by AndreaDiCeglie** [comment]
"è possibile eseguire una unica registrazione (Purchase Receipt Header) per un carico warehouse, in modo da avere tutte le righe del carico warehouse all'interno della stessa Purchase Receipt Header?" -> No, non è possibile. E' lo standard

"E' possibile avere uno strumento di ricerca **righe di carico** che aggreghi le informazioni (ad es. una page stile "Riepilogo documenti vendita")?
-Sulle righe non c'è un riferimento che raggruppi i dati, bisognerebbe fare una query che faccia la join di testate e righe ma poi l'oggetto query non è utilizzabile direttamente in page.

Al momento non è prevista l'implementazione di una feature del genere
