### ISSUE TITLE
Integrazione app ADR e CMS (WI 9591)

### ISSUE THREAD

**Issue by FedericoEos93** [EOS-Solutions/IDEAS#82]
Buongiorno, come da suggerimento dei labs riguardante il ticket EOS:0261000011256, si chiede di poter modificare le app ADR e CMS, con eventuali app aggiuntive di integrazione che permettano l'invio di documenti (soprattutto solleciti) tramite ADR ad indirizzi mail relativi agli agenti setuppati tramite CMS. Ad ora, il setup indirizzi mail adr permette solo di richiamare il campo agente presente sull'anagrafica cliente, in maniera quindi scollegata dal cms.

![image](https://user-images.githubusercontent.com/85099759/152944264-acf849a9-4f1d-4772-a8d5-23343dbecba2.png)

grazie in anticipo

**Comment by AndreaDiCeglie** [comment]
We are evaluating the priority of this request.  Will be planned for future release
