### ISSUE TITLE
Add Field in a report EOS Calc. and Post VAT Settl.

### ISSUE THREAD

**Issue by ghost** [EOS-Solutions/IDEAS#83]
Buongiorno,
si chiede l'aggiunta del campo Descrizione della tabella "VAT Product Posting Group (324)", siccome il codice è già presente manca solo la relativa descrizione nel Dataitem.

**Comment by AndreaDiCeglie** [comment]
Il campo può essere aggiunto nel dataitem ma non nel layout per non impattare sul parco istallato.
Il campo nel dataitem può essere aggiunto con Report Extensions.
Essendo out of scope la modifica del layout standard la conclusione è che il tutto va realizzata come customizzazione

**Comment by ghost** [comment]
Io sto lavorando con una BC14, dove i report extension non sono permessi e quindi mi sono indirizzato su una soluzione non proprio idonea, modificando il codice del report builder.

Da: Andrea Di Ceglie ***@***.***>
Inviato: mercoledì 16 febbraio 2022 15:59
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Giovanni Bergo ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] Add Field in a report EOS Calc. and Post VAT Settl. (Issue #83)


Il campo può essere aggiunto nel dataitem ma non nel layout per non impattare sul parco istallato.
Il campo nel dataitem può essere aggiunto con Report Extensions.
Essendo out of scope la modifica del layout standard la conclusione è che il tutto va realizzata come customizzazione

-
Reply to this email directly, view it on GitHub<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FEOS-Solutions%2FIDEAS%2Fissues%2F83%23issuecomment-1041580990&data=04%7C01%7Cgiovanni.bergo%40eos-solutions.it%7C7d85bfce4bd44e293fd208d9f15ceba5%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806203672766881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NSVnODdo1Ij2bVVmMAWda7i76beiLK0yV2eCkXTqBYE%3D&reserved=0>, or unsubscribe<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXXCGV4B2EQG7SDSDQQP2NTU3O3UTANCNFSM5OES4DRA&data=04%7C01%7Cgiovanni.bergo%40eos-solutions.it%7C7d85bfce4bd44e293fd208d9f15ceba5%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806203672766881%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=NKIh84%2FgxC7eMC5qpISxKLpHon208B2OqFWqXwPJTX4%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cgiovanni.bergo%40eos-solutions.it%7C7d85bfce4bd44e293fd208d9f15ceba5%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806203672923088%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=l0dICKbtwvOgNAvpuZOW%2FqpMVf9o%2FF69ybs2L5tNnks%3D&reserved=0> or Android<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cgiovanni.bergo%40eos-solutions.it%7C7d85bfce4bd44e293fd208d9f15ceba5%7Ccdd2b2ff69af49e39161680fb58a011d%7C0%7C0%7C637806203672923088%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=SzJIclECoCZUvj888F5kSJzgVsOLnAqC0t8HNDlAweU%3D&reserved=0>.
