### ISSUE TITLE
PSU SSU  Riepilogo documenti cambiare tipo pagina in "lista" WI8709

### ISSUE THREAD

**Issue by AndreaDiCeglie** [EOS-Solutions/IDEAS#84]
Change type of pages from "worksheet" to "list".

This enable:
- Saved views (and filters)
- Export in Excel
- Use on Phone Device

Changing to list the filter field in page header will be lost.

Add preset of UserView for Document Types:
- quote
- order
- etc...

**Comment by AndreaDiCeglie** [comment]
NOTE : Export in Excel  starting from BC19 is supported on all page types.

Add preset of UserView for Document Types:

Open orders
Invoices
Cr Memo

**Comment by hemisphera** [comment]
Available in 20.0.15
