### ISSUE TITLE
Aggiorna tipo reddito non imponibile ritenute - CU2022

### ISSUE THREAD

**Issue by CristianCorega-Lutech** [EOS-Solutions/IDEAS#85]
Buongiorno, come da suggerimento di labs riguardante il ticket EOS:0261000011793, chiedo supporto in merito alla funzionalità “Aggiorna tipo reddito non imponibile”.
Ho visto che è stata aggiornata per supportare i nuovi codici previsti ma, secondo me, per come è impostata oggi, risulta poco utile. Considerando le variazioni dei codici di quest’anno (da 7 a 21, etc), sarebbe bello avere una sostituzione massiva, prendendo in considerazione sia la tabella “Withholding Tax” (12116) che la “EOS Withh. Non-taxable Amounts” (18059817) - in app/"Withh. Non-taxable Amounts" (18008184) - pre BC.
Se possibile, suggerirei di aggiornarla nel seguente modo:
•	In request page avere il campo “Vecchio tipo reddito non imponibile” e “Nuovo tipo reddito non imponibile” lasciando la possibilità di impostare eventuali altri filtri sulle ritenute.
•	Per ogni ritenuta nel filtro, sostituire il “Tipo reddito non imponibile” solamente se questo è uguale al “Vecchio tipo reddito non imponibile”. Nello stesso tempo, fare il rename dei record “Importi ritenuta non imponibili” che hanno “Tipo reddito non imponibile” uguale al “Vecchio tipo reddito non imponibile”.
Su clienti con tanti movimenti ritenuta nell’anno potrebbe essere noioso dover rincorrere le varie schede e così potrebbero sistemare l’anno 2021 con soli 3 passaggi di aggiornamento.
Grazie e buon lavoro.

**Comment by alessandrovecchio** [comment]
Buongiorno Cristian,
procederemo a breve con la modifica. Ti tengo aggiornato tramite questa issue.

Buona giornata

**Comment by alessandrovecchio** [comment]
questo punto
`In request page avere il campo “Vecchio tipo reddito non imponibile” e “Nuovo tipo reddito non imponibile” lasciando la possibilità di impostare eventuali altri filtri sulle ritenute.`
non mi è chiaro, non è già possibile lanciando il report da object designer o collegandolo a menu?

Grazie

**Comment by CristianCorega-Lutech** [comment]
Ciao, sì, è già possibile lanciare il report dalla lista delle ritenute e va bene così.
Lo imposterei però come da screen sottostante:
![image](https://user-images.githubusercontent.com/99826466/154652986-376c59b8-7e1e-4de4-88d5-a2a5831a6d41.png)
In questo modo, lanciandolo per esempio per il 2021, puoi sostituire il vecchio valore con il nuovo valore sia nella tabella delle ritenute che in quella dei tipi reddito non imponibili.
Sulla base dei filtri e della sostituzione vecchio valore-nuovo hai infinite possibilità: sostituire per esempio massivamente 7 con 21, impostare massivamente il 24 al posto di valori rimasti blank, etc..

Spero di essere riuscito a spiegarmi meglio.
Grazie e ciao, Cristian

**Comment by alessandrovecchio** [comment]
Buongiorno Cristian, in app abbiamo apportato una modifica la report in oggetto in modo da aggiornare anche le righe di dettaglio importi non reddituali, in alternativa all'aggiornamento della tabella ritenute.
Purtroppo abbiamo rilevato un bug Microsoft per cui non è possibile filtrare sul campo "tipo reddito non imponibile", quindi l'utilizzo del report è limitato da questo.

In C/AL non è stato riportato nulla. 

Grazie
