### ISSUE TITLE
Implementazione CMS da CC- Trade

### ISSUE THREAD

**Issue by apezzano** [EOS-Solutions/IDEAS#86]
Buongiorno, chiedo supporto in merito alla possibilità di implementare due nuovi campi alla CMS. 
Nell’ipotesi che un cliente acquisti il CMS e voglia fornire possibilità a tutti gli agenti vendita di inserire offerte sui propri clienti e potere visualizzare solo i propri documenti (possibilmente con una licenza team-member), propongo l'implementazione di 2 campi nella “User Setup (T91)”: 

o	Filtro ruolo: campo tabellato alla T18008296 (Ruoli agenti)
o	Filtro agente: campo tabellato alla T13 (Agenti)

![richiesta](https://user-images.githubusercontent.com/99964320/154674621-57b5fa6b-2218-483d-b774-abb95ba2587d.png)

Questo definirà un filtro “non rimovibile” di tipo “and” sull’utente per:
• Lista contatti, lista clienti, lista indirizzi spedizione, lista ordini vendita, Lista spedizioni registrate, lista fatture, Lista fatture registrate.

![richiesta 2](https://user-images.githubusercontent.com/99964320/154703116-640d04a9-e96f-494c-992c-e8c969b4ef83.png)

Grazie e buon lavoro.

**Comment by AndreaDiCeglie** [comment]
Ciao,

Per quanto la richiesta sia sensata, non è riconducibile allo scopo dell'app CMS ma al tema di poter gestire in BC :
- SFA accesso agenti
- (Estendendo il concetto) un customer access

il problema tecnico che si pone è quello di rilasciare una soluzione che sia coerente filtrando effettivamente i dati anche delle tabelle correlate e non fermandosi alla facciata delle liste clienti / contatti /documenti.

La feature indicata va considerata una nuova app.
