### ISSUE TITLE
BANK OF ITALY - Descrizione Fatture diverse  tracciato SEPA (WI 8710)

### ISSUE THREAD

**Issue by ErikaC82** [EOS-Solutions/IDEAS#88]
Si richiede la possibilità di decidere in caso di Bonifico fornitori cumulativo , se indicare la descrizione delle singole fatture o il "fatture diverse" 
Attualmente il file mette solo il fatture diverse

**Comment by Chuucommie** [comment]
Ciao, 
per effettuare la modifica è necessario un evento nel codice della funzione di esportazione standard, questo evento al momento non c'è. È stata effettuata richiesta a Microsoft di aggiungere l'evento necessario. 
( https://github.com/microsoft/ALAppExtensions/issues/16641 )

**Comment by Chuucommie** [comment]
Ciao, 

l'evento è stato inserito nella versione di BC 20.1, la modifica sarà effettuata ma sarà disponibile solo da BC20.1 in poi

Saluti,
Ricardo

**Comment by ErikaC82** [comment]
Buonasera l'evento è stato inserito nel Esporta Floppy ( file txt posizionale 12175 ) che non è il tracciato SEPA cioè XML che avevo richiesto io ( 1220 ).


[EventRequest] report 12175 "Vendor Bills Floppy", procedure RECORD50 #16641



Da: chuucommie ***@***.***>
Inviato: mercoledì 15 giugno 2022 10:42
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Erika Cuocci ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] BANK OF ITALY - Descrizione Fatture diverse tracciato SEPA (WI 8710) (Issue #88)


Ciao,

l'evento è stato inserito nella versione di BC 20.1, la modifica sarà effettuata ma sarà disponibile solo BC20.1 in poi

Saluti,
Ricardo

-

**Comment by Chuucommie** [comment]
Buongiorno,

la modifica è stata effettuata e pubblicata onprem per BC19, BC20 e BC20.1 nelle versioni 19.0.17 , 20.0.13 e 20.1.6 , l'app è aggiornabile 
facci sapere se è corretta

Grazie,
Saluti

**Comment by ErikaC82** [comment]
Buongiorno ho fatto un test è non tronca ai 143 char

Forse si può aggiungere un setup per escludere il tipo documento? Comunque nel caso va troncato.

Avete aggiunto un setup per disattivarlo temporaneamente?

***@***.***

Da: chuucommie ***@***.***>
Inviato: lunedì 1 agosto 2022 10:38
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Erika Cuocci ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] BANK OF ITALY - Descrizione Fatture diverse tracciato SEPA (WI 8710) (Issue #88)


Buongiorno,

la modifica è stata effettuata e pubblicata onprem per BC19, BC20 e BC20.1 nelle versioni 19.0.17 , 20.0.13 e 20.1.6 , l'app è aggiornabile
facci sapere se è corretta

Grazie,
Saluti

-

**Comment by matteomontanari** [comment]
Ciao
Poco fa ci siamo accorti anche noi della svista.
Stiamo buildando le app con il fix al problema. Tra pochi minuti rilasciamo sui feed (smeagol) e lanciamo la pubblicazione su Saas.

{UPDATE: tutto rilasciato, stiamo procedendo con il SAAS}

fix disponibile:
- da 19.0.20 e successive
- da 20.0.14 e successive
- da 20.1.7 e successive
- 
Matteo

**Comment by ErikaC82** [comment]
Grazie Matteo!

Da: Matteo Montanari ***@***.***>
Inviato: martedì 2 agosto 2022 15:12
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Erika Cuocci ***@***.***>; Author ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] BANK OF ITALY - Descrizione Fatture diverse tracciato SEPA (WI 8710) (Issue #88)


Ciao
Poco fa ci siamo accorti anche noi della svista.
Stiamo buildando le app con il fix al problema. Tra pochi minuti rilasciamo sui feed (smeagol) e lanciamo la pubblicazione su Saas.

fix disponibile:

  *   da 19.0.20 e successive
  *   da 20.0.14 e successive

Matteo

-
