### ISSUE TITLE
APP EX020 VMI - Gestione Lettere di intento su Modulo Service WI8705

### ISSUE THREAD

**Issue by Yuri-Giacchetto-EOS** [EOS-Solutions/IDEAS#89]
E' stata rilevata la completa assenza della gestione delle lettere di intento su Fatture e Note Credito assistenza.

Per cui si richiede l'implementazione della gestione EOS Vat Management e dei relativi campi anche nel modulo Service come già avviene nel modulo Vendite. 
Anche il file XML della fatturazione elettronica deve riportare i riferimenti della lettera di intento come da indicazione ministeriale

La richiesta è abbastanza urgente in quanto il cliente in questione, Viteria 2000 (che di recente è passato alla versione 19.2), è partito il 3/1/2022 e nel mese di Febbraio ha 5/6 fatture di assistenza da emettere in esenzione.

Versione: IT Business Central 19.2 (piattaforma 19.0.32956.33475 + applicazione 19.2.32968.33504)

Grazie per l'attenzione.
Yuri Giacchetto - yuri.giacchetto@eos-solutions.it

**Comment by AndreaDiCeglie** [comment]
Richiesta accolta e aggiunta in backlog ma difficilmente può essere rilasciata con urgenza, da analizzare  dettagli di implementanzione

**Comment by Yuri-Giacchetto-EOS** [comment]
Buongiorno,
il Cliente sta sollecitando e ci sarebbe la necessità di avere una indicazione circa la data di rilascio che prevedete. E' possibile avere un'indicazione di massima?
Grazie

**Comment by alessandrovecchio** [comment]
Ciao Yuri,
purtroppo al momento non riesco a darti indicazioni a riguardo perché l'attività devo ancora iniziarla, quindi abbiamo recepito l'esigenza ma devo ancora approfondirla tecnicamente.
Ti aggiornerò prima possibile.

Grazie
AV

Da: Yuri Giacchetto ***@***.***>
Inviato: lunedì 11 aprile 2022 09:45
A: EOS-Solutions/IDEAS ***@***.***>
Cc: Alessandro Vecchio ***@***.***>; Assign ***@***.***>
Oggetto: Re: [EOS-Solutions/IDEAS] APP EX020 VMI - Gestione Lettere di intento su Modulo Service WI8705 (Issue #89)


Buongiorno,
il Cliente sta sollecitando e ci sarebbe la necessità di avere una indicazione circa la data di rilascio che prevedete. E' possibile avere un'indicazione di massima?
Grazie

-

**Comment by alessandrovecchio** [comment]
Ciao, piccolo aggiornamento: mi hanno approvato oggi un evento richiesto a MS necessario per l'implementazione. Controllerò nelle prossime versioni la presenza per poi continuare lo sviluppo.

**Comment by alessandrovecchio** [comment]
Modifica rilasciata per la versione 20
