### ISSUE TITLE
EX003 EDS Disable "Release" and "Reopen" buttons according to the area (WI 7037)

### ISSUE THREAD

**Issue by MatCive** [EOS-Solutions/IDEAS#9]
When EDS is active users still can Release and/or Reopen the documents using the standard buttons. This is a problem because users can bypass the EDS locks.
A workaround is to remove the buttons via a customized app.
My proposal is to disable the page "Release" and "Reopen" buttons according to the related table by adding a boolean field in the EDS table.

**Comment by AndreaDiCeglie** [comment]
Button cannot be removed using an ISV solution since it would break compatibility with third party apps.
We'll give a try disabling the fields and adding a specific setup on EDS Status Setup table to disable release and reopen actions

**Comment by ElioCometto** [comment]
Change done.
App version with update: 19.0.42
