### ISSUE TITLE
APP EX020 VMI - Stampa Registri IVA e Registri IVA raggruppati con opzione di scelta data su cui filtrare

### ISSUE THREAD

**Issue by Yuri-Giacchetto-EOS** [EOS-Solutions/IDEAS#90]
Nella request form della stampa dei registri IVA e registri IVA raggruppati sarebbe interessante aggiungere un'opzione per far scegliere all'utente su quale data filtrare i dati : se data Registrazione (default) o Data effettuazione operazione.
Ovviamente anche quanto stampato dovrà essere coerente con la scelta effettuata dall'utente.

Il concetto è molto simile a quello espresso nel Setup in uscita (FTE) dove si sceglie quale data esportare nel Tag Dati Documento Mgt.

La richiesta parte da un'esigenza del cliente Viteria 2000 che è partito il 03/01/2022
Versione: IT Business Central 19.2 (piattaforma 19.0.32956.33475 + applicazione 19.2.32968.33504)

Grazie per l'attenzione.
Yuri Giacchetto - yuri.giacchetto@eos-solutions.it

**Comment by AndreaDiCeglie** [comment]
E' stata valutata con il competence circle finance e rifiutata

**Comment by Yuri-Giacchetto-EOS** [comment]
Ciao, si può avere una minima motivazione del rifiuto?

**Comment by AndreaDiCeglie** [comment]
La stampa registri IVA al momento ancora una stampa fiscale e va prodotta con filtri coerenti per data registrazione.
Quanto richiesto da te è normalmente associato all'esigenza di quadrare i totali con la liquidazione iva che va invece per Data effett operazione (correggimi se sbaglio).
Aggiungere filtri per date diverse, apre alla possibilità di uso improprio della stampa Reg IVA stessa.

E' da tempo allo studio la realizzazione di una page che supporti le quadrature e non abbia impatti rischiosi sugli output con valenza fiscale.
Per ogni ulteriore dubbio vi rimando al competence circle Finance
Andrea

**Comment by Yuri-Giacchetto-EOS** [comment]
Grazie Andrea, gentilissimo.
Buona giornata, Yuri
