### ISSUE TITLE
CDW - Annulla carico non permesso

### ISSUE THREAD

**Issue by cesariniGS** [EOS-Solutions/IDEAS#91]
Ciao,
in Ord.Acq., usando funzione CDW 'criterio di registrazione'=Non scrivere fatturazione e mov.contabili:
a) registro un carico
b) eseguo funzione standard 'Annulla Carico'
---> non è permesso annullare il carico perchè 'già fatturato'. E' prevista l'implementazione della funzione?
Grazie

**Comment by AndreaDiCeglie** [comment]
Ciao,

 E' prevista l'implementazione della funzione? No non è al momento prevista
