### ISSUE TITLE
ECS Combine shipment for free goods (WI 9224)

### ISSUE THREAD

**Issue by alessandrovecchio** [EOS-Solutions/IDEAS#93]
In ECS app is missing the functionality to create invoices for sales free goods. This feature was available in old CAL platform version 2016

**Comment by alessandrovecchio** [comment]
vedere TDAG44484 Masidef (Mirko?)

**Comment by Chuucommie** [comment]
The feature has been developed and implemented to the Sales Free Goods app (EX043) as a new report named "Free Gift Self-Invoice Creation" managed by the "Self Invoice Setup" in the "Free Gift Setup" page.
It has been published to BC19 and BC20 in the 19.0.9 and 20.0.33 versions.

Best Regards,
Ricardo
