### ISSUE TITLE
Electronic Invoice for Italy (FTE)

### ISSUE THREAD

**Issue by IlariaEos** [EOS-Solutions/IDEAS#96]
Viene richiesta, se possibile, l'aggiunta e visualizzazione nella stampa XML alternativo della <Data SDI> e del <Nr. SDI> del documento, in particolare per le fatture di acquisto.
Per alcuni clienti è fondamentale.
Grazie.

**Comment by alessandrovecchio** [comment]
L'informazione dell'ID SDI non è presente nell'xml e il template di visualizzazione è quello fornito da Abletech, da noi non modificato.
