### ISSUE TITLE
Withholding Tax Certificazioni Uniche for Italy - Inserimento ritenute In Fattura (WI 8605)

### ISSUE THREAD

**Issue by ragusale** [EOS-Solutions/IDEAS#97]
Un cliente mi ha fatto notare che la parte relativa alla gestione "TIpo di reddito non imponibile" non è presente sulla page di inserimento  "Ritenute-INPS" dalle fatture di acquisto.

Per loro sarebbe importante avere la gestione già a partire dall'inserimento della fattura.

**Comment by alessandrovecchio** [comment]
Ciao, dopo verifica interna, il punto è stato approvato e verrà sviluppato, seppur con priorità bassa. Al momento non saprei indicare un apossibile data di rialascio.
