### ISSUE TITLE
CONAI - modificabile per ogni cliente/fornitore

### ISSUE THREAD

**Issue by MarkusMoserEOS** [EOS-Solutions/IDEAS#98]
Il contabile di Enoitalia vorebbe gestire la Conai tutto in questa schermata:
•	Esenzione dovrebbe essere un campo modificabile
•	E vorrebbe anche poter decidere per ogni fattura se applicare la Conai / o scrivere la Conai come righe (con i flag come nel setup acq. / ven CONAI)
 
![image](https://user-images.githubusercontent.com/101793608/158763010-2a0f8ec6-dae8-4ab6-b7eb-cc52c5727eea.png)

 
![image](https://user-images.githubusercontent.com/101793608/158763024-885fcfeb-473d-4b85-986f-8c094d90295d.png)

 
 
 Penso che anche altri clienti hanno questi bisogni visto che il contabile ha detto che in teoria non ci sono mai eccezioni, ma nella pratica lui ha bisogno di poter modificare per ogni fattura in questa schermata se la conai viene calcolata / o quale esenzione c'è. 

Grazie Mille!

**Comment by Giuliano-Velludo-EOS** [comment]
Abbiamo discusso internamente e deciso di non realizzare l'implementazione richiesta.

**Comment by MarkusMoserEOS** [comment]
Grazie mille per l'info.

Von: Giuliano Velludo ***@***.***>
Gesendet: Donnerstag, 23. Juni 2022 15:13
An: EOS-Solutions/IDEAS ***@***.***>
Cc: Markus Moser ***@***.***>; Author ***@***.***>
Betreff: Re: [EOS-Solutions/IDEAS] CONAI - modificabile per ogni cliente/fornitore (Issue #98)


Abbiamo discusso internamente e deciso di non realizzare l'implementazione richiesta.

-
